### ISSUE TITLE
Calendario tareas?

### ISSUE THREAD

**Issue by naquiroz** [IIC2133-PUC/2019-1#1]
Hola! Hay algun calendario con las fechas de las tareas?

**Comment by alopez7** [comment]
Hola, es difícil hacer un calendario de tareas porque depende del ritmo en que avanza la clase y el taller. Te puedo contar los temas de las tareas:
T0: introductoria a C y a sus estructuras básicas (se publicará pronto)
T1: investigación de una estructura de datos que no se ve en el curso
T2: backtracking
T3: búsqueda en el espacio de estados (hashing y búsqueda)
T4: grafos

**Comment by alopez7** [comment]
A veces incluso cambia el orden dependiendo de el orden en que yadran ve la materia

**Comment by naquiroz** [comment]
Ok gracias.
