### ISSUE TITLE
Problema con la instalación de GTK-3 en Mac

### ISSUE THREAD

**Issue by jerosalazar** [IIC2133-PUC/2019-1#10]
Tengo un problema al instalar GTK-3. Al correr `brew install gtk+3 gtk+ --without-x --without-x11`, me dice que `--without-x` no es una opción válida. ¿Qué podrá ser?

**Comment by alopez7** [comment]
@ignaciohermosillacornejo te podría ayudar ya que el tiene mac. La otra opción es que uses una máquina virtual de linux

**Comment by fdominguezclaro** [comment]
@jerosalazar yo lo corrí sin parámetros y se instaló bien. Aún no pruebo a correr el código en C eso sí.

**Comment by ignaciohermosillacornejo** [comment]
@fdominguezclaro te funcionó?

**Comment by jiaranda** [comment]
Me pasa lo mismo, al compilar con `make` me muestra el error `src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found`. Para solucionarlo instalé gtk+ y gtk+3 con brew: `brew install gtk+` y `brew install gtk+3` y sigo teniendo el mismo error. ¿Alguien sabe cómo solucionarlo?.

PD: también estoy en mac

**Comment by ranieto** [comment]
@jiaranda Estaba en lo mismo. Encontré [esta página](https://codeday.me/es/qa/20190220/211851.html) con una supuesta solución.
Corrí la línea `export PKG_CONFIG_PATH=/usr/local/Cellar/cairo/1.12.16/lib/pkgconfig/` (Probablemente la tengas que modificar un poco, por ejemplo mi versión era la 1.16.0), y al intentar compilar me dijo
```
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
```
Así que hice eso, con `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/`

Después de eso me funcionó :)

**Comment by jiaranda** [comment]
@ranieto Seguí tus instrucciones y funciona perfectamente! Muchas gracias! 😃

**Comment by nlvargas** [comment]
@ranieto ¿Cómo se debe modificar el export y cómo saber qué versión se pone? Puse los dos comandos tal cual y no pasó nada en la terminal y sigo teniendo el mismo problema. ("src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found")

**Comment by ranieto** [comment]
@nlvargas Todo esto es asumiendo que el mensaje de error que te sale es el mismo que el mío. El error tiene varias líneas y la primera es `Package libffi was not found in the pkg-config search path.`. Si te sale otra cosa, el problema es otro.

Lo que cambia en el export es la versión del programa, que es parte del path donde está instalada la aplicación. Entonces, si tu versión de `libffi` es la 3.2.0, el comando sería
```
export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.0/lib/pkgconfig/
```
Todo eso son carpetas, incluyendo la versión. Asi que si no sabes qué versión de `libffi` tienes, revisa qué hay en la carpeta!
```
ls /usr/local/Cellar/libffi/
```
Y si por esas cosas de la vida, la carpeta no existe, entonces no tienes instalado `libffi`, y lo puedes instalar con homebrew.
```
brew install libffi
```

**Comment by jerosalazar** [comment]
Gracias por todos los comentarios! me funcionó todo bien ahora 😊

**Comment by mduhalde1** [comment]
Hola, qué tal? Seguí todos los pasos que dijeron, es decir: 
1.- `brew install gtk+ gtk+3
`
2.- `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/
`
 - en mi mac- y aún así me sigue tirando este error: 
`make: *** [obj/beholder/main.o] Error 1
`
Alguien a pesar de seguir todos los pasos le pasó lo mismo ?

**Comment by JoseRomeroi** [comment]
@mduhalde1 Yo segui todos los pasos, y me sigue apareciendo este error:

` /bin/sh: pkg-config: command not found `
` clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]`
`src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found`
`#include <gtk/gtk.h>`
         `^~~~~~~~~~~`
`1 error generated.`
`make: *** [obj/beholder/main.o] Error 1`

**Comment by fedetaladriz** [comment]
Yo sigo con este mismo problema. Intenté todo lo que sale en este post y nada. Alguna ayuda?

**Comment by JoseRomeroi** [comment]
@fedetaladriz @mduhalde1 Pude hacerlo. Había seguido los pasos anteriores y no me había funcionado. Lo que hice fue lo siguiente:

`brew install pkg-config`

Despues puse make y me tiro el siguiente error:

`Package libffi was not found in the pkg-config search path`

Y lo solucioné con lo que puso @ranieto más arriba.

Ojala les sirva
