### ISSUE TITLE
Asistencia Talleres

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2133-PUC/2019-1#100]
Hola!

Existe la posibilidad de que se actualice la tabla con las asistencias a los talleres? :pray:

**Comment by alopez7** [comment]
Hola, estamos revisando los criterios de corrección para no perjudicarlos innecesariamente. Trataremos de que estén pronto.

**Comment by MarceloSaldias** [comment]
Muchas Gracias!

**Comment by kenzoak** [comment]
Hola! 
Me parece que tengo un error en la asistencia del taller del 10/05. Con quién podría hablar de esto?
Gracias!

**Comment by alopez7** [comment]
Cual es el error? no se te corrigió?

**Comment by baarratia** [comment]
> Hola!
> Me parece que tengo un error en la asistencia del taller del 10/05. Con quién podría hablar de esto?
> Gracias!

A mi me sale que no tengo asistencia, siendo que si entregué la actividad (Lo comprobé viendo que si  subí la respuesta a siding...) y recuerdo haber firmado lista en todas las oportunidades. Halp :(
