### ISSUE TITLE
Cambio en makefile y directorios tarea 

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2133-PUC/2019-1#101]
Hola,

No me lograba compilar bien los utils que nos entregaron no sé porque, pero luego los cambie de carpeta a una nueva "utils" y la añadi al makefile para que la compilara y me funcionó.

Mi pregunta va a si esto afectará la corrección de mi tarea.

Gracias

**Comment by vichoeq** [comment]
No te funcionaba `#include "util.h"` ??

**Comment by pdesolminihac** [comment]
Lo incluia en uno de mis archivos y utilizaba una de sus funciones, pero al tratar de compilar me tiraba el error: 
undefined reference to ´position_shift´

Y la forma que logre que funcionara fue con lo que dije anteriormente, por eso la pregunta

**Comment by pdesolminihac** [comment]
Hola,
No me han respondido si es que los cambios que hice afectaran o no la correción de mi tarea. Por mientras voy a entregarla así.

**Comment by vichoeq** [comment]
Perdona. No, no deberia afectar. Corregimos usando la Makefile que ustedes suben.

**Comment by pdesolminihac** [comment]
Ok! Gracias
