### ISSUE TITLE
Tarea3 cairo.h

### ISSUE THREAD

**Issue by Dyoma3** [IIC2133-PUC/2019-1#103]
hola, acabo de empezar a ver la tarea y me sale este error en el make:
![image](https://user-images.githubusercontent.com/17127676/59109005-372ec100-890a-11e9-994e-7f9f2feab49a.png)
no se encuentra cairo.h
primera vez que uso mac para una tarea de eedd, hay que instalar algo?

**Comment by fdominguezclaro** [comment]
Lee la issue #10, tienes que incluir el path de `PKGCONFIG`

**Comment by Dyoma3** [comment]
@fdominguezclaro buena gracias
