### ISSUE TITLE
Formato Output

### ISSUE THREAD

**Issue by MrEarle** [IIC2133-PUC/2019-1#104]
Hola,

Para el output con la solucion del problema no me queda claro la convención de las direcciones, especificamente con UP y DOWN.

Asumo que UP es hacia arriba como se vería en la interfaz gráfica, pero podria ser aumentar el indice en la matriz que representa al problema (lo que significaría hacia abajo en la interfaz grafica).

Cual opcion es la correcta?

**Comment by vichoeq** [comment]
La interfaz y el modulo util.h trabaja los indices como la fila y columna de una matriz

Siguiendo esa convencion tenemos.que la primera fila (row = 0) es la de mas arriba y la primera columna (col = 0) es la de mas a la izquierda.
