### ISSUE TITLE
T3 - borde tablero

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2133-PUC/2019-1#105]
Hola, podemos asumir que ninguna solución requerirá extender un puente de forma tal que no se alcance a expandir por completo dentro de los bordes del tablero?
Es decir, que no será necesario realizar un mivimiento del tipo

1 X X X X X X
X X 4 X X X X
G X X X X X X
X X X X X X X
X X X X X X X

--->

1 X X X X X X
OOO X X X X
G X X X X X X
X X X X X X X
X X X X X X X

Gracias!

**Comment by vichoeq** [comment]
No, no puedes asumirlo, ya que eso depende de las otras jugadas que has
heho. Al igual que en el juego original, si una extensión se sale del
tablero no pasa nada grave: se pintan las celdas correspondientes que
quedan dentro del tablero solamente.
