### ISSUE TITLE
T3 - Heuristicas del Informe

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#106]
Hola!

En el informe, se pueden analizae dos heuristicas para las direcciones?, o es necesario que sea una heuristica para los puentes y otra para las direcciones?

Gracias!

**Comment by vichoeq** [comment]
Puedes analizar ambas para las direcciones, pero lo ideal es que sean suficientemente distintas y ambas tengan "sentido"
