### ISSUE TITLE
Plazo Tarea 3

### ISSUE THREAD

**Issue by nvielva** [IIC2133-PUC/2019-1#109]
Estimados, quería preguntar si existe la posibilidad de extender el plazo de la entrega de la tarea o en su defecto aplicar un castigo a la nota por atraso de la misma manera que se hizo para la tarea pasada. Se agradecería mucho tener esta posibilidad.

**Comment by alopez7** [comment]
Incluso si se parte la terea hoy hay tiempo suficiente para resolver los tests fáciles y el plazo extra del informe es suficiente para implementar podas o heurísticas y escribir un buen informe. No se dará tiempo extra.

**Comment by mbfuster** [comment]
¿No hay alguna forma de reemplantearse esto? Aún no puedo desarrollar bien el algortimo Naive del problema. Por favor.

**Comment by cafuentes1** [comment]
Estoy cerca de la solución pero no creo que alcance a entregar dentro del plazo, ¿Es posible considerar un descuento por día de atraso?

**Comment by shantifabri** [comment]
Me paso lo mismo, no logre terminar antes del plazo pero senti que estaba cerca de hacerlo. ¿podrían hacer algo como la tarea anterior? Quizas solo con 1 día.

**Comment by alopez7** [comment]
Luego de los resultados de la tarea pueden mandar a recorregir agregando lo que les falte para el método naive y se aplicará el descuento correspondiente.
