### ISSUE TITLE
Posible error en la correccion T3

### ISSUE THREAD

**Issue by Dyoma3** [IIC2133-PUC/2019-1#110]
Tuve un error al hacer el make, el que muestro en la issue #103, lo solucione segun lo que dijieron en #10, pero si clono mi repo denuevo tengo el mismo error y tengo que hacer de nuevo lo que dicen en la issue. Para corregir van a tener esto en consideracion ?

**Comment by vichoeq** [comment]
En general, a la hora de corregir si tu tarea no compila tiene un 1 pero puedes solicitar recorrección para identificar y/o solucionar el problema y volverla a corregir. Según la naturaleza del error puede llevar un descuento si tienes que arreglar algun error en tu código, pero en el caso que me describes no debería haber problema.

**Comment by Dyoma3** [comment]
ya dale, porque en el codigo no tengo errores
