### ISSUE TITLE
Error GIT

### ISSUE THREAD

**Issue by mericci** [IIC2133-PUC/2019-1#111]
Estoy tratando de subir mi tarea a git y me aparece el siguiente error: 

![image](https://user-images.githubusercontent.com/42249674/59161324-426f2180-8aaf-11e9-8bbf-b497d5d4e02f.png)

He estado buscando como solucionarlo pero me lleva a otros errores. No se si alguien sabe como se puede arreglar esto.

Muchas gracias

**Comment by vichoeq** [comment]
Por que estás intentando subir tu tarea al repositorio base y no a tu propio repositorio?
