### ISSUE TITLE
T3 - Estudio Empírico de Complejidad

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#112]
Hola!

Para efectos del estudio empírico, sería aceptable hacer los gráficos solo con una ejecución del programa por nivel?, o recomiendan ejecutarlo múltiples veces por nivel?

Gracias!

**Comment by vichoeq** [comment]
A veces el tiempo que toma un programa puede fluctuar según lo que está pasando en tu computador, asi que es razonable correr un mismo test unas 3 veces y tomar el promedio o la mediana, lo que te parezca apropiado. Ahora, si ese tiempo son 10 minutos, en realidad  basta con correrlo una vez para afirmar que efectivamente se demora mucho. En casos como esos incluso sería razonable poner un limite de tiempo para poder recolectar los datos en un tiempo razonable.

Ahora, si tu programa toma decisiones aleatorias, tal como hicimos con el analisis de quicksort, lo ideal seria probar cada nivel unas 100 veces y analizarlo caso a caso. Para el análisis global de ese método deberias incluir el mejor caso, peor caso y caso promedio, tanto para el tiempo como para la cantidad de UNDOs.

Asegurate de comparar los rendimientos entre puzzles de similar dificultad, es decir, de igual N.
