### ISSUE TITLE
Corriendo mitad de los test básicos e Informe 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2133-PUC/2019-1#113]
Hola, qué tal? 
No alcancé a terminar todos los test básicos por tema de tiempo y me preguntaba que si aún así puedo entregar un informe ya que se me habían ocurrido ciertas heurísticas y podas pero no las alcancé a hacer :( . 
Salu3.

**Comment by inmadariaga** [comment]
Me paso lo mismo, corro 8/10 de los test básicos

**Comment by alopez7** [comment]
Si se corregirá el informe. La única situación en que no se corrige es si no se entrega código (no se acepta informe sin código)
