### ISSUE TITLE
T3 - Modificar Heurística para el Informe

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#114]
Hola!

Me acabo de dar cuenta que implementé una de mis heurísticas que voy a estudiar de forma sub-óptima. Podría arreglarla solo para poder realizar un mejor informe? (No utilicé esa heurística en mi solución final)

Gracias!

**Comment by vichoeq** [comment]
Si, la idea de los días extra es que modifiques y experimentes con tu código.
