### ISSUE TITLE
T3 - Exhaustividad del Informe

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#115]
Hola!

Que tan exhaustivo debería ser el informe?, Hay que explicar en detalle cada poda, cada heurística, cada combinación y justificar también en detalle teórica y empíricamente?, o podemos "resumir" algunas explicaciones?

Saludos!

**Comment by alopez7** [comment]
Hola, el detalle que se espera de la exolicación es que sen entienda cómo funviona la poda o heurística cosa que cualquiera pueda imolementarlo. No es necesario que expliques la imolementación a no ser que algún detalle de la imolementación sea importantr para la complejidad de la poda o heurística.
