### ISSUE TITLE
[T03 - Informe] Test con poda/heuristica vs sin ella

### ISSUE THREAD

**Issue by Regenschrim** [IIC2133-PUC/2019-1#116]
Tengo una duda con respecto al informe y el análisis de las podas y heurísticas. Claramente, si mi algortimo no resuelve algo de los 10 primeros test (en mi caso el 7, 9 y 10) algo debe estar mal. Sin embargo, al colocar una heurística el 7 si lo resuelve (todavía estoy probando las podas). ¿Cómo hacer el análisis en este caso? No tengo un tiempo sin heuristica para compararlo con el que obtenga al usarla :/ ¿O solo muestro la comparación de tiempos de los otros test?

Gracias! :)

**Comment by alopez7** [comment]
Tu programa debería poder resolver todos los tests (aunque sea en muucho tiempo). Para comparar los tests 7, 8 y 9 pon como referencia el tiempo que demoren aunque sea mayor a 10 segundos. Y si es demasiado tiempo ponle un límite (por ejemplo 2 minutos) y explicas que después de ese tiempo aún no termina

**Comment by Regenschrim** [comment]
¿Y si me entrega segmentation fault? jaja :( Creo que mi programa se marea cuando son muchos puentes y se cae (caso del 9 y 10), pero con la poda de ordenamiento creo que funcionan (aun no la termino de implementar). ¿Tendré que corregir mi codigo hasta que funcione?

**Comment by alopez7** [comment]
Creo que no es terrible no usar todos los tests fáciles pero creo que al menos deberías usar uno con cada cantidad de puentes

**Comment by Regenschrim** [comment]
Yap, gracias!
