### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by Regenschrim** [IIC2133-PUC/2019-1#117]
Se que es algo tarde en el semestre para preguntar esto, pero ¿existe algun debugger o nos recomiendan alguno en particular para revisar nuestro código? Siento que resulta muy difícil y es muy mala práctica ir usando prints en el programa para ver donde ocurre el problema (lo cual me ha jugado en contra en las ultimas 2 tareas).

Gracias de antemano  :)

**Comment by alopez7** [comment]
Si, el debuguer que hemos recomendado desde el principio es valgrind. Puedes usarlo en linux o rn la consola de linux en windows pero en mac tiene algunos problemas para funcionar bien.

**Comment by vichoeq** [comment]
Valgrind debería cubrir casi todas tus necesidades ya que te avisa de errores de memoria (los que por lo general son los que más causan estragos, y silenciosamente)

Si no tienes errores de memoria y quieres es revisar errores de lógica, lo más desenredado es usar prints, con `getchar()` para detener tu programa, y usar `assert()` para asegurar ciertas invariantes dentro de tu código. (Por ejemplo, el funcionamiento de alguna función asume que el parámetro X nunca jamás es mayor a 3 y en caso de serlo se rompe toda tu lógica.) -> Si el assert falla, corta el programa y avisa que fue lo que lo hizo fallar.

Si eso no es suficiente para tí, existe una herramienta llamada GDB. En general no le hago mucha publicidad porque es tremendamente complicada de usar, pero debería permitirte hacer watch de variables y extablecer break points en tu código para revisar los valores de las variables en un punto dado... pero recuerda que esto es por consola así que es sumamente tedioso.

La alternativa que tienes es instalar alguna IDE para trabajar en C, como Netbeans y CLion. Ellas te ofrecen una interfaz de usuario más comoda para trabajar con el debugger (GDB). En general tampoco les hemos hecho publicidad porque significa que además de tener que aprender a programar en C tienen que aprender a usar estas IDEs, las cuales pueden ponerse mañosas y overall dificultar el proceso en lugar de facilitarlo.

Eso.

Saludos!

**Comment by Regenschrim** [comment]
Me referia mas a lo que decia vicente, ya que he estado teniendo unos pequeños problemas con mi logica: ciertos casos en particular no funcionan de mi programa, o que las cosas se den en un orden determinado afecta mucho si se resuelve o no. Busqué algo de GDB el otro día pero me di cuenta que de verdad es un cacho entenderlo. 
Gracias de todos modos por la info!
