### ISSUE TITLE
T03 - Recorrección

### ISSUE THREAD

**Issue by Regenschrim** [IIC2133-PUC/2019-1#118]
Me acabo de dar cuenta que mi algoritmo consigue la respuesta correcta, pero olvide colocar que en el output pusiera el número de movimientos, por lo que solo escribe los movimientos. ¿Cómo afecta en caso de querer recorregir? (si es que fuera solo agregar una línea de código)

**Comment by ignaciohermosillacornejo** [comment]
Tendrías que solicitar recorreción, independiente del tamaño del arreglo. Ahora para un arreglo tan menor te descontarían 0 o 1 decimas de la nota.

Saludos
