### ISSUE TITLE
Gráfico Informe

### ISSUE THREAD

**Issue by Cschavez** [IIC2133-PUC/2019-1#120]
Hola! Una duda, para graficar los datos respecto al tiempo que se demora y la cantidad de puentes que tiene un test, como hay niveles que tienen la misma cantidad de puentes, debo diferenciar en que nivel estoy graficando? por ejemplo haciendo un gráfico para cada test o solo gráfico cantidad de puentes vs tiempo sin identificar a que test corresponde cada tiempo?. Espero se entienda mi pregunta, es que mi duda surge de que puedo tener dos test con cantidad de puentes igual a 5 pero no por eso se demoran parecido, ya que depende de la estructura del nivel.  O también puedo tener niveles con distinta cantidad de puentes que se demoran lo mismo

Gracias!

**Comment by alopez7** [comment]
Podrías hacer un gráfico de puntos donde un eje es el número de puentes y el otro es el tiempo

**Comment by Cschavez** [comment]
y cada punto representa un nivel?

**Comment by vichoeq** [comment]
Todo depende el orden en el que pruebas las variables.

En todo caso, si se demoran distinto trata de argumentar por qué. Por ejemplo, que tiene mas peso, la estructura o el tamaño.
