### ISSUE TITLE
T4 - Fecha de Inicio

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#122]
Hola!

Considerando lo poco que queda de semestre (y lo poco que queda para el examen), tienen una idea de cuando subirán la T4? (si es que está lista, obvio.)

Gracias!

**Comment by alopez7** [comment]
La tarea 4 se publicará la próxima semana y el plazo es hasta prácticamente el final de semestre ya que es una competencia de programación y se corrige muy fácil. Cubrirá todo lo que no se ha evaluado del curso con mini problemas de distintas materias (no hay que hacerlo todos).

**Comment by vichoeq** [comment]
Esta semana está complicada, pero estamos intentando tenerla para el viernes, pero probablemente salga del horno a principios de la otra semana (a más tardar martes).

El formato de la tarea será una especie de "examen de tareas": les daremos 10 problemas simples de distintas temáticas y tendrán que resolver al menos 6 para tener un 7. Problemas adicionales valdrán 0.5 puntos extra para una nota máxima de 9.

Para que les cunda más el tiempo, cada problema se puede hacer en C, C++ o Python, el que más les acomode.

En terminos de plazo no lo hemos decidido todavía pero es posible que se les dé hasta el final del semestre.
