### ISSUE TITLE
Error excel controles

### ISSUE THREAD

**Issue by Okhan97** [IIC2133-PUC/2019-1#126]
Hola,

Viendo el excel de notas noté algo extraño, mis notas son hasta el momento:
65, 60, 50, 45, 57.5, 52.5

Calculando el promedio a mano (suponiendo que elimino el C7) me da 55, sin embargo en el excel me aparece un 4.92 ¿Se me está pasando algo o efectivamente el excel está errado?

PD: Mi numero de alumno es 15635333

**Comment by vichoeq** [comment]
Toda la razón. La formula que había en el excel dependía de que existiera una nota para el C7. Como estaban las cosas estaba reemplazando la peor de tus notas existentes por un 1. Ahí la arreglé.

**Comment by vichoeq** [comment]
Dejo la issue abierta por si acaso alguien vio su nota antes del cambio.
