### ISSUE TITLE
Preguntas Controles

### ISSUE THREAD

**Issue by matiaseche** [IIC2133-PUC/2019-1#127]
Hola, podrían subir los controles? Durante el semestre fui descargando todas las pautas pero ahora quería ver algunas preguntas y no están en algunos controles (C1, C3 y C5 pregunta 2).

Gracias!

**Comment by alopez7** [comment]
Chuta, no se como buscarlos tampoco...

**Comment by alopez7** [comment]
Los buscaré igual

**Comment by matiaseche** [comment]
Vale, gracias!

**Comment by alopez7** [comment]
[controles.zip](https://github.com/IIC2133-PUC/2019-1/files/3316421/controles.zip)
Aqui estan todos los controles
