### ISSUE TITLE
Duda asistencias talleres

### ISSUE THREAD

**Issue by Regenschrim** [IIC2133-PUC/2019-1#129]
Es un pequeña duda. Para la fecha del paro no se considero la asistencia a la ayudantia (por que no fue taller al fin y al cabo), pero dentro del excel esa fecha aparece y es como que todos estuvieran ausentes. Quizas sea un poco estupido preguntar pero, ¿se considerará dentro del total de asistencias? Es solo para estar seguro y ver que nota al final tendría uno en las asistencias.

Gracias!

**Comment by vichoeq** [comment]
Hola, el excel de asistencias esta sujeto a cambios ya que hay fechas que se perdieron como esa y otras mas. Cuando calculemos la nota se hara solo respecto a los talleres que hubo y se pasó asistencia. Ahi les avisaremos para que revisen su nota.

**Comment by Regenschrim** [comment]
Yaa, gracias!
