### ISSUE TITLE
Tarea 0 - Movimiendo dentro de un Toro

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#13]
Hola!

Por lo que tengo entendido del movimiento dentro de un Toro representado como plano, el movimiento vertical se devuelve verticalmente y el movimiento horizontal horizontalmente, pero qué pasa cuando nos salimos exactamente en diagonal? (por ejemplo, del 0,0 al -1,-1 )

Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Una combinación de los dos, del (0,0) si te muevez en diagonal a la izquierda llegas a la posición (M-1, N-1)

**Comment by KnowYourselves** [comment]
Muchas gracias!
