### ISSUE TITLE
A - A Saltar

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#130]
Acá pueden hacer sus dudas respecto a la pregunta A

**Comment by ignaciohermosillacornejo** [comment]
Complejidad esperada de la solución: O(n)

**Comment by B-Dominguez** [comment]
Se supone que el input viene en "una línea" o líneas vienen separadas por '\n' o '\r'?
Porque en cuadro de ejemplo se ven como que estuvieran separadas por '\n' pero al hacer copy paste como sugiere el enunciado, quedan en una línea.
Al subir la solución me arroja runtime error, pero mi solución sí está en O(n) y no se informa qué tan lejos está del tiempo esperado.

**Comment by caespinoza5** [comment]
¡Hola!

Vienen en líneas separadas por '\n'.

**Comment by B-Dominguez** [comment]
Gracias, ahora me funcionó al 4to intento.
Solicito no aplicar descuento de tiempo porque mi único error en este fue seguir el enunciado

> Naturalmente querrán probar su código antes de subirlo al servidor, la mejor manera de hacer esto es crear un archivo in.txt en la misma carpeta que su código, copiar y pegar input de ejemplo y correr el siguiente comando:
~python3 a.py < in.txt

**Comment by HenryBlairG** [comment]
Hola!! yo lo contemplé como '\n' y también me arroja el runtime Error en el servidor a pesar de que en local me funciona muy bien. ¿Cómo se espera que sea la captura del input? o puedo mostrarles cómo lo hice de alguna manera para que me ayuden con esto? Mi algoritmo no tiene problemas, es en la captura del input, estoy seguro (Estoy siguiendo la captura de input de acuerdo al enunciado)

**Comment by caespinoza5** [comment]
La captura es, como dices, de acuerdo al enunciado; un "input()" por línea. Si tu input es por ejemplo el siguiente:
```
1
2
3 4
0

```
Un archivo en python que lo lee sería:
```
while True:
    x = input()
    if x == "0":
        print("Termino aquí")
        break
```

**Comment by mramirez7** [comment]
Hola! alguien de los que tenía el problema del Runtime error lo pudo solucionar? A mi por consola me funciona perfecto pero no se porque el corrector me lo rechaza

**Comment by HenryBlairG** [comment]
En mi caso fue por usar librerías (numpy) en mi código, se me arregló una vez que reemplacé todo lo que usaba de esa librería por equivalentes de la librería estándar de python

**Comment by mramirez7** [comment]
No uso ninguna librería :( gracias igual @HenryBlairG

**Comment by ignaciohermosillacornejo** [comment]
@mramirez7 revisa los ejemplos de código de como leer input. 
Puedes ir leyendo el input caso a caso, no tienes que leer todo el input de una.

**Comment by mramirez7** [comment]
El input lo tenia igual a como caespinoza5 lo puso. Creo que el problema es la forma de entregar el output, pero he probado haciendo print en cada iteracion sin nada entre medio, print con \n entremedio y con espacio, pero también tengo runtime error

**Comment by ignaciohermosillacornejo** [comment]
Tu programa se cae leyendo el input. Prueba con esto que es básicamente el ejemplo del enunciado repetido varias veces

```
3
1
-4 -8
4 8 9
2
-2
3 1
3
1
-4 -8
4 8 9
2
-2
3 1
3
1
-4 -8
4 8 9
2
-2
3 1
3
1
-4 -8
4 8 9
2
-2
3 1
3
1
-4 -8
4 8 9
2
-2
3 1
0
```

**Comment by ignaciohermosillacornejo** [comment]
Tu problema no es de output, es de como lees el input. Haces:

```python
if linea == "0":
```
cuando lo que quieres hacer es:
```python
if linea == "0\r":
```

\r es un caracter especial que se llama carriage return y se usa en los inputs para separar las lineas. Te recomiendo nuevamente seguir el formato que puse del input de ejemplo, te va a facilitar la hacer la tarea y no perder tiempo con problemas de leer/escribir input. Todos los problemas están pensados para funcionar bien y de manera facil con los ejemplos que pusimos de leer/escribir output.

**Comment by mramirez7** [comment]
Gracias! me resultó
