### ISSUE TITLE
B - Bajando la montaña

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#131]
Acá pueden hacer sus dudas respecto a la pregunta B

**Comment by ignaciohermosillacornejo** [comment]
Complejidad esperada de la solución (peor caso): O(n) donde n es el número de nodos

**Comment by B-Dominguez** [comment]
Hola, se puede asumir que las lineas vendrán en orden como en el ejemplo? Es decir que no habrá una linea con un sendero del hito 2 al 3 antes de la linea del sendero del X al 2

**Comment by B-Dominguez** [comment]
Otra cosa: el enunciado dice "f, n" pero luego en el ejemplo se ve que se entregan al revés: "n, f"
cómo se evalúa?

**Comment by B-Dominguez** [comment]
otra duda: puede ser que haya un hito al que no se pueda llegar solo bajando desde el 1?
ej:
           1
 5      2  3
    4

**Comment by ignaciohermosillacornejo** [comment]
Hola @B-Dominguez 

No puedes asumir eso.

Saludos

**Comment by B-Dominguez** [comment]
> Hola @B-Dominguez
> 
> No puedes asumir eso.
> 
> Saludos

Eso se refiere a esto?

> puede ser que haya un hito al que no se pueda llegar solo bajando desde el 1?

Es decir que sí habrían tests en que no se puede llegar solo bajando a un amigo?

**Comment by ignaciohermosillacornejo** [comment]
Hola @B-Dominguez 

> Otra cosa: el enunciado dice "f, n" pero luego en el ejemplo se ve que se entregan al revés: "n, f"
> cómo se evalúa?

Se evalúa como N y después F, ahora arreglé el enunciado para indicar más claramente eso.

> otra duda: puede ser que haya un hito al que no se pueda llegar solo bajando desde el 1?
> ej:
> ------ 1
> 5----2--3
> -- 4

Te voy a citar el enunciado acá: 
```Existen senderos que conectan pares de hitos de tal manera que existe una  única ruta (secuencia de senderos consecutivos) entre la cumbre y cualquier otro hito.```

Saludos

**Comment by ignaciohermosillacornejo** [comment]
Hint:

Como se la energía gastada? Se que tengo que visitar a todos los nodos con amigos menos el último (no tengo que regresar a la cumbre después de visitar a mi útlimo amigo). Tengo que si o si visitar todos los nodos, y el orden no importa excepto cual es el último, dado esto, cual amigo visito último con tal de minimizar la energía gastada?

**Comment by B-Dominguez** [comment]
Hola, leyendo el hint y dado que todos los casos de pruebas que ideé me corren bien, pero el servidor me da runtime error, puede ser que haya un error en el corrector? Han revisado los casos de prueba?
Leyendo el hint, puede ser que el caso de prueba esgté "cuentando doble" las partes que se repiten? Es decir haciendo volver siempre hasta la cumbre en vez del nodo necesario.

**Comment by ignaciohermosillacornejo** [comment]
Hola! 

Todos los casos de prueba fueron testeados multiples veces. En particular, este problema ha sido testeado con más de tres 3 soluciones distintas. Creeme que no estamos contando dos veces las aristas compartidas por  distintos montañistas, hacer que tu solución no cuente las aristas repetidas mas de una vez es parte de la dificultad.

Nuevo hint: Este problema tiene soluciones recursivas e iterativas, te recomiendo usar la iterativa fuertemente por que es más facil.

Saludos

**Comment by santilaguna** [comment]
Tengo dos dudas,
1) ¿podemos asumir que el 1 es la raiz siempre??
2) ¿podemos asumir las aristas vienen ordenadas como en el ejemplo? (ej: si me dan la arista: 2 3 c, necesariamente, me dieron la arista: a 2 c' antes)

**Comment by ignaciohermosillacornejo** [comment]
Hola @santilaguna 

1 Si! Sale en el enunciado creo.
2. No, las aristas te las dan en cualquier orden

Saludos

**Comment by mramirez7** [comment]
@B-Dominguez, estoy igual que tu hace un par de días, el programa me corre bien con los tests que dieron y con otro creados por mí pero me tira runtime error. Me puedes contar mas o menos como lo solucionaste? era error de lectura de input, caso borde, etc... Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Si estas trabajando con Python te recomiendo hacer tu código iterativo en vez de recursivo, puede que estes haciendo muchas llamadas recursivas y se caiga por eso.

**Comment by HenryBlairG** [comment]
Yo lo hice en python de manera iterativa y también me arroja Runttime Error

**Comment by mramirez7** [comment]
@ignaciohermosillacornejo Cambié todas las recursiones por while's o stacks pero sigo con el runtime error y estoy casi 100% seguro que mi programa anda bien

**Comment by achadwicka** [comment]
Me pasa lo mismo que a los demás, probe con múltiples test propios y corre bien, arreglando casos bordes y sigue arrojando Runtime Error.
Porfavor alguien avise si lo puede solucionar!

**Comment by HenryBlairG** [comment]
Si lo están haciendo en python, no se si al resto le sirva o no, pero metí mi función en un try/except y el servidor siguió lanzando Runtime Error. Creo que el error debe estar en cómo capturamos el input

**Comment by HenryBlairG** [comment]
Hola!!!

Me pueden ayudar con Time Limit Exceeded? estoy usando la version iterativa, con deque en python y no sé qué más optimizar de mi código. Solucioné el Runtime Error, pero no se me ocurre nada para optimizar mi código. Tienen algún tip o algun consejo?

**Comment by ignaciohermosillacornejo** [comment]
Hola, 

Si usas un try except para capturar el EOF tu programa va a andar bien lento, los try/except van a hacer que tu programa corra muy lento y definitivamente los revisaría. Para este problema en particular pueden hacer 
```python3
N, F = [int(x) for x in input().split()]
if (N == 0 and F == 0):
    break
```
Para saber cuando pueden terminar de leer input

Suerte
