### ISSUE TITLE
C - Caballo-PQ 

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#132]
Acá pueden hacer sus dudas respecto a la pregunta C

**Comment by ignaciohermosillacornejo** [comment]
Complejidad esperada: O(N x M)

**Comment by B-Dominguez** [comment]
Hola, primero se dice "Un caballero normal de ajedrez entonces es un caballo-(2,1)" pero luego se dice "0 ≤ p ≤ M ≤ 1000,0 ≤ q ≤ N ≤ 1000", como que p fuera para eje x y q para eje y, necesariamente. 
Cómo se espera en realidad? Para cada estado hay 4 u 8 movimientos posibles?

**Comment by B-Dominguez** [comment]
Aprovecho de pedir ayuda. En mi computador el programa me corre bien, pero cada vez que subo la solución me dice "runtime error"
Estoy probando con este test
![image](https://user-images.githubusercontent.com/26129405/59981016-fc947c00-95cb-11e9-99ab-0cf6584bdb37.png)

Y tengo este output en consola
![image](https://user-images.githubusercontent.com/26129405/59981023-15049680-95cc-11e9-8086-f85f5f8ca91b.png)

Así leo el input
![image](https://user-images.githubusercontent.com/26129405/59981035-2ea5de00-95cc-11e9-82e0-7428d4e3bc3e.png)
En mi computador termina por m==0 and n==0

**Comment by B-Dominguez** [comment]
Además, me confunde el uso primero de la notación MxN como que m son filas y N columnas, pero luego se asocia x (usualmente nro de columna) <= M e y (usualmente nro de fila) <= N, o es más bien como que x es un i e y un j? -> (x,y) = (i,j)?

**Comment by alopez7** [comment]
Sobre el input y output no te puedo ayudar mucho, se lo dejo a @ignaciohermosillacornejo pero sobre la duda del movimiento, el caballo puede moverse p en x y q en y o al revés. Si p y q son distintos entonces tiene 8 posibles movimientos.

**Comment by B-Dominguez** [comment]
Pensando en casos bordes, si en un caso se pide ir y volver a uno mismo, lo estoy retornando como 0 pasos. Esto se evaluaría correcto?

**Comment by alopez7** [comment]
Si

**Comment by ignaciohermosillacornejo** [comment]
> Además, me confunde el uso primero de la notación MxN como que m son filas y N columnas, pero luego se asocia x (usualmente nro de columna) <= M e y (usualmente nro de fila) <= N, o es más bien como que x es un i e y un j? -> (x,y) = (i,j)?

El caballo se puede mover en 8 direcciones distintas como comento @alopez7. Sobre el input/output no entiendo tu pregunta

**Comment by baarratia** [comment]
Hola, programé este problema en C y he probado con distintos casos y me funciona todo rápido y con respuestas correctas. Al momento de subirlo, igual que mi compañero que comentó más arriba, el servidor me tira runtime error. Algún tip para poder solucionarlo? Llevo harto rato probando y realmente no tengo idea qué podría ser.

Muchas gracias!

> Aprovecho de pedir ayuda. En mi computador el programa me corre bien, pero cada vez que subo la solución me dice "runtime error"
> Estoy probando con este test
> ![image](https://user-images.githubusercontent.com/26129405/59981077-c60b3100-95cc-11e9-9348-af2ecd9d3ffe.png)
> 
> Y tengo este output en consola
> ![image](https://user-images.githubusercontent.com/26129405/59981082-d3282000-95cc-11e9-9487-72bb186d7aea.png)
> 
> Así leo el input
> ![image](https://user-images.githubusercontent.com/26129405/59981035-2ea5de00-95cc-11e9-82e0-7428d4e3bc3e.png)
> En mi computador termina por m==0 and n==0

**Comment by ignaciohermosillacornejo** [comment]
Prueba correrlo con valgrind, puede ser que tengas un problema de memoria que esté botando tu código. El servidor es bastante estricto con eso tengo entendido.

**Comment by baarratia** [comment]
Valgrind me dice esto:
![image](https://user-images.githubusercontent.com/11417516/60410124-b96e7600-9b94-11e9-9de8-268baeee3800.png)

Estoy tratando de cachar como mejorar la cosa haciendo los "free" correspondientes para las cosas que uso, pero al probarlo no cambia mucho :/

**Comment by ignaciohermosillacornejo** [comment]
Te recomiendo por simplicidad hacer tu solución en `Python` si estas muy pegado con errores en C.

**Comment by Cadagan** [comment]
Hola @ignaciohermosillacornejo , podrian por favor aclarar si M es columnas o filas? lo mismo con el N

El input segun el ejemplo que viene en el enunciado, indica que los indices van desde 1 a M y de 1 a N, por lo que si trabajamos con coordenadas, debiesemos restarle 1 a los numeros entregados (menos a M, N, p y q) para trabajar correctamente con los indices en una matriz. 

No se si esto puede que sea el problema, porque me ocurre lo mismo que a los de arriba, en los test que pruebo funciona bien, pero al subirlo falla, probablemente por temas de indices :(

**Comment by ignaciohermosillacornejo** [comment]
M es el número de columnas y N el número de filas. 

Hint: Se the cae tu código por problemas de índices.
Hint 2: Prueba un caso de prueba en que el tablero no es cuadrado

**Comment by Cadagan** [comment]
Muchas gracias! :)

**Comment by ignaciohermosillacornejo** [comment]
De seguro confundiste filas con columnas en algún lado. Si estas muy pegado debugeando, lo mejor es partir de 0 tu código, vas a programar con la mente muy clara en cuanto a lo que quieres hacer y tú código va a ser mucho mejor de una.

**Comment by Cadagan** [comment]
ok mas tarde intenatre de nuevo, muchas gracias! :)

**Comment by baarratia** [comment]
> M es el número de columnas y N el número de filas.
> 
> Hint: Se the cae tu código por problemas de índices.
> Hint 2: Prueba un caso de prueba en que el tablero no es cuadrado

Hola, he intentado de todo y todavía me sigue tirando runtime error, me podrías ayudar con algún hint de este estilo? jajaj di vuelta ya todas las filas y columnas porque al parecer ese era mi problema, pero sigue con problemas :( please help

**Comment by jeharcha** [comment]
> > M es el número de columnas y N el número de filas.
> > Hint: Se the cae tu código por problemas de índices.
> > Hint 2: Prueba un caso de prueba en que el tablero no es cuadrado
> 
> Hola, he intentado de todo y todavía me sigue tirando runtime error, me podrías ayudar con algún hint de este estilo? jajaj di vuelta ya todas las filas y columnas porque al parecer ese era mi problema, pero sigue con problemas :( please help

Tambien lo agradecería !
Llevo mucho rato, cambiando filas por columnas, optimizando el algoritmo, pero nada.
Localmente me funciona.
Existe alguna posibilidad de que se nos entregue el caso de prueba con el que falla nuestro prgrama?
Graciass

**Comment by ignaciohermosillacornejo** [comment]
Hola!

Decidimos no publicar los casos de pruebas para la tarea, la idea es que piensen en detalle que está haciendo su código y que podría suceder con el. Esto es intencional y parte de la dificultad de la tarea. 

En cuanto a sus preguntas de filas/columnas, *X* representa la columna en que estamos e *Y* la fila. Cuando les damos *i*, *j* esto generalmente es fila columna, en los enunciados sale especificados, en este en particular dice 1 <= x1, x2, <= M, 1 <= y1, y2 <= N

En el issue de la G hice una analogía con este problema y explique por que ambos son parecidos, además de entregar un boilerplate de problemas de busqueda de estados usando BFS para python3 que les puede ser util. 

Suerte en sus problemas

**Comment by jeharcha** [comment]
Ignacio,
Disculpa lo burdo y explícito de mi ejemplo, pero es sólo para aclarar.

Si se nos dice que se quiere llegar a la posición (x, y) = (2, 100),  
este elementos estaría en una matriz de python en matriz[100][2] ??

**Comment by ignaciohermosillacornejo** [comment]
Hola @jeharcha 

Va a depender totalmente de tu solución. X va con M e Y con N.

Si definiste tu tablero de esta forma por ejemplo:
```python3
board = [[0 for _ in range(N)] for _ in range(M)]
```
Siginifica que tu posición final corresponde a 
``` python3
board[x2][y2]
```
Ahora, si creaste tu matriz de la siguiente forma
```python3
board = [[0 for _ in range(M)] for _ in range(N)]
```
tu posición final corresponde a:
```python3
board[y2][x2]
```

Lo imporante es que X está asociado a M e Y a N, el orden en verdad no es relevante, si no mantener la consistencia en tu código.

Saludos

**Comment by Tibrahm** [comment]
tengo una duda de como el servidor lee el archivo in.txt porque cuando se lo paso por consola de la siguiente forma si me lo toma

`python ejemplo.py in.txt`

pero de esta forma no

`python ejemplo.py < in.txt`

**Comment by ignaciohermosillacornejo** [comment]
De seguro es lo que dices tú, te referiría a #152 donde tengo un ejemplo de cual es la mejor manera de leer input y entregar output.

**Comment by Tibrahm** [comment]
Efectivamente por eso se caía mi codigo !
