### ISSUE TITLE
D - ¿Dónde se fue el agua?

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#133]
Acá pueden hacer sus dudas respecto a la pregunta D

**Comment by ignaciohermosillacornejo** [comment]
Complejidad de la solución: O(E log E + E log V)

**Comment by nachocontreras** [comment]
Hola!

Tengo unas dudas con respecto a los inputs y outputs:

- Si no hay fuentes, entonces el flujo máximo sería 0 ya que hay que minimizar la cantidad de arreglos.
- Si no hay estanques, entonces el flujo es 0.
- Si ya están las fuentes reparadas entonces no hay que seguir aumentando el flujo (usando otras cañerías).
- Si 2 fuentes están conectadas y un estanque está conectado a una de esas fuentes, entonces sólo bastaría con usar esas dos cañerías (la de entre fuentes y fuente-estanque) para arreglar ambas fuentes.

Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Hola @nachocontreras 

Te respondo punto a punto:
> Si no hay fuentes, entonces el flujo máximo sería 0 ya que hay que minimizar la cantidad de arreglos.

Siempre va a haber una fuente, no tienes que preocuparte por este caso.

> Si no hay estanques, entonces el flujo es 0.

Siempre va a haber un estanque.

> Si ya están las fuentes reparadas entonces no hay que seguir aumentando el flujo (usando otras cañerías)

Correcto, queremos que todas las fuentes esten conectadas a un estanque maximizando el flujo. Si ya estan todos las fuentes conectadas, no debes seguir aumentando el flujo.

> Si 2 fuentes están conectadas y un estanque está conectado a una de esas fuentes, entonces sólo bastaría con usar esas dos cañerías (la de entre fuentes y fuente-estanque) para arreglar ambas fuentes.

No te entendí mucho la pregunta, creo que esto aclararía la duda pero si no avisame: Si tengo dos fuentes conectadas entre si, me basta con conectar una de las dos a un estanque para arreglar ambas fuentes.

Saludos

**Comment by nachocontreras** [comment]
Gracias!

**Comment by HenryBlairG** [comment]
Hola

No me queda claro cómo identifico una fuente y un estanque a partir del input.

> Para identificar si el nodo es fuente o estanque, se tiene lo siguiente:
> • Un nodo i ∈ 0, . . . , a − 1 es fuente.
> • Un nodo i ∈ 0, . . . , a + b − 1.

No comprendo como sabré si un nodo es fuente o estanque a partir de eso

Desde ya gracias por el apoyo

**Comment by ignaciohermosillacornejo** [comment]
Esta pregunta es totalmente lograble, sale con un algorítmo visto en clases con algunas modificaciones muy menores. Hint: la complejidad te debiera dar una pista importante a que algorítmo usar

**Comment by ignaciohermosillacornejo** [comment]
Les dejo otro hint: 

Cuando hagan su algorítmo, van a tener que evaluar si unir u con v.  Para hacer esto tienen que revisar dos condiciones:

- Unir u con v si es que sus representantes son distintos (no están ya conectados) y que no se cumpla que ambos representantes son estanques.
-Al hacer una unión, asegurarse de dejar siempre como el representante del grupo al estanque

Saludos

**Comment by fedetaladriz** [comment]
Hola! 
Tengo una duda en el caso de que se conecten dos fuentes. 
Poniendo el caso en que conecto una fuente 1 al estanque, con una cañería de capacidad c1, la cantidad de agua total sería c1. Luego, si conecto la fuente 2 a la fuente 1 con una cañería de capacidad c2, la cantidad de agua total sería c1 (La capacidad c1 se reparte entre las fuentes) o c1 + c2? (Llegan c1 a la fuente 1 y una fracción c2 se lleva a la fuente 2?

Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Hola @fedetaladriz 

Respondiendo a tu pregunta, sería la segunda opción, c1 + c2. Dicho de forma más general, tu respuesta tiene que ser la suma de todas las cañerias que repares y solo las que repares.

Saludos

**Comment by diegomendieta** [comment]
Hola, no me queda claro el enunciado. Entiendo que el objetivo es reparar todas las fuentes, pero, qué se debe priorizar, maximizar la cantidad de agua o minimizar el número de cañerías reparadas?

**Comment by ManuelBeckerT** [comment]
Hola @diegomendieta, como dice el enunciado, el objetivo del problema es maximizar el agua que llegue a las fuentes a partir de los estanques, pero siempre minimizando el número de cañerías a reparar. En el ejemplo que diste, sería mejor reparar 9 cañerías siempre que esta no sea "redundante" o que conecte múltiples estanques a través de la red. Debes tener cuidado de que al momento de agregar una cañería a tu solución sigas respetando todas las restricciones del problema.

**Comment by santilaguna** [comment]
@ignaciohermosillacornejo @ManuelBeckerT o algún otro ayudante,
Hola tengo una duda, cuál es la capacidad máxima de las cañerias ??

**Comment by diegomendieta** [comment]
Cuando en el enunciado, en el apartado de Input, dice: "Un nodo i pertenece a {0, ..., a + b - 1}, donde los nodos 5 y 6 representan estanques", supongo que es un error de tipeo. Asumo que los nodos {0, ..., a-1} son las fuentes, y los nodos {a, ..., a+b-1} son los estanques. Es esto correcto?

**Comment by ignaciohermosillacornejo** [comment]
> @ignaciohermosillacornejo @ManuelBeckerT o algún otro ayudante,
> Hola tengo una duda, cuál es la capacidad máxima de las cañerias ??
> Otra duda, las aristas pueden tener costo negativo o cero??

Hola @santilaguna, te contesto tus dos preguntas, las aristas tienen pesos que van desde 0 hasta 999.

> Cuando en el enunciado, en el apartado de Input, dice: "Un nodo i pertenece a {0, ..., a + b - 1}, donde los nodos 5 y 6 representan estanques", supongo que es un error de tipeo. Asumo que los nodos {0, ..., a-1} son las fuentes, y los nodos {a, ..., a+b-1} son los estanques. Es esto correcto?

Hola @diegomendieta , es un error de tipeo efectivamente, la linea debiera decir:

- Un nodo i pertenece {a, ..., a + b - 1} es estanque

Saludos
