### ISSUE TITLE
E - Evitando multiplicar

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#134]
Acá pueden hacer sus dudas respecto a la pregunta E

**Comment by HenryBlairG** [comment]
Hola!!

Tengo una inquietud con respecto a la submission.

Sucede que con los tests del enunciado mi programa funciona perfecto, sin embargo cuando hago la submission me arroja Wrong Answer. He cubierto varios casos borde y sin embargo me sigue sucediendo esto. De verdad que no entiendo este error, tengo entendido que he hecho bien mi función, capturo bien el input y entrego correctamente el output. 

Asi capturo y entrego mi input y output respectivamente

```python
if __name__ == "__main__":
    N = int(input())
    stream = []
    while N:
        try: 
            stream.append(int(input()))
        except EOFError:
            break
    print(solver(stream))

```

**Comment by ignaciohermosillacornejo** [comment]
Wrong answer es que tu programa entregó una respuesta (es decir, no se cayo ni nada) pero la respuesta que entrega es incorrecta. Eso siginifica que tienes un error en tu código, para buscarlo la mejor forma es create un caso de prueba tu mismo más grande y hacerlo a mano.

Saludos

**Comment by fedetaladriz** [comment]
Hola! Que complejidad se espera para este problema? 
Gracias!

**Comment by ignaciohermosillacornejo** [comment]
> Hola! Que complejidad se espera para este problema?
> Gracias!

O(N^3)

**Comment by santilaguna** [comment]
Hola, cuál es el mínimo valor de N?

**Comment by ignaciohermosillacornejo** [comment]
Hola @santilaguna 

N <= 10 <= 500

Saludos

**Comment by santilaguna** [comment]
@ignaciohermosillacornejo supondré que te refieres a 10 <= N <= 500, gracias !

**Comment by ignaciohermosillacornejo** [comment]
Si perdón, ahora arreglo mi respuesta

**Comment by santilaguna** [comment]
@ignaciohermosillacornejo estoy teniendo problemas con hacer submissions en c++ (E.cpp), la página simplemente deja de funcionar cuando intento subirlo, qué puedo hacer al respecto? (que no sea escribir el código nuevamente en otro lenguaje)
