### ISSUE TITLE
F - Finalizando el ramo

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#135]
Acá pueden hacer sus dudas respecto a la pregunta F

**Comment by caespinoza5** [comment]
Para ayudarlos a resolver el problema, les daré un ejemplo concreto y un par de tips.

**Ejemplo**

Supongamos que tenemos 3 alumnos y 3 problemas, en base al siguiente input:
```
3 3
2 2 2
4 2 1
4 4 1
```
Esto se traduce a la siguiente tabla:

**Tabla 1**

| Alumno | Tiempo P1 | Tiempo P2 | Tiempo P3 |
| --- | --- | --- | --- |
| 1 | 2 | 2 | 2 |
| 2 | 4 | 2 | 1 |
| 3 | 4 | 4 | 1 |

Queremos ver cuál es el mejor ranking posible de cada alumno. Para esto, debemos iterar sobre el tiempo _t_ desde el cual serían reemplazados los tiempos. Por ejemplo:

Supongamos que el tiempo que reemplazan es con` t = 1`. Recordamos que el puntaje total es la suma de los problemas de cada tiempo, y la posición de un alumno es el número de alumnos que obtuvieron una posición menor o igual que dicho alumno. Los tiempos totales y posiciones serían las siguientes (ver definición de posición y puntaje total de acuerdo a enunciado):

**Tabla 2**

| Alumno | Tiempo P1 | Tiempo P2 | Tiempo P3 | Puntaje total | Posición |
| --- | --- | --- | --- | --- | --- |
| 1 | 1 | 1 | 1 | 3 | 3 |
| 2 | 1 | 1 | 1 | 3 | 3 |
| 3 | 1 | 1 | 1 | 3 | 3 |

Supongamos que el tiempo que reemplazan es con` t = 2`. Los tiempos totales y posiciones serían las siguientes:

**Tabla 3**

| Alumno | Tiempo P1 | Tiempo P2 | Tiempo P3 | Puntaje total | Posición |
| --- | --- | --- | --- | --- | --- |
| 1 | 2 | 2 | 2 | 6 | 3 |
| 2 | 2 | 2 | 1 | 5 | 2 |
| 3 | 2 | 2 | 1 | 5 | 2 |

Supongamos que el tiempo que reemplazan es con` t = 3`. Los tiempos totales y posiciones serían las siguientes:

**Tabla 4**

| Alumno | Tiempo P1 | Tiempo P2 | Tiempo P3 | Puntaje total | Posición |
| --- | --- | --- | --- | --- | --- |
| 1 | 2 | 2 | 2 | 6 | 2 |
| 2 | 3 | 2 | 1 | 6 | 2 |
| 3 | 3 | 3 | 1 | 7 | 3 |

Supongamos que el tiempo que reemplazan es con` t = 4`. Los tiempos totales y posiciones serían las siguientes:

**Tabla 5**

| Alumno | Tiempo P1 | Tiempo P2 | Tiempo P3 | Puntaje total | Posición |
| --- | --- | --- | --- | --- | --- |
| 1 | 2 | 2 | 2 | 6 | 1 |
| 2 | 4 | 2 | 1 | 7 | 2 |
| 3 | 4 | 4 | 1 | 9 | 3 |

De todas estas tablas, podemos ver que **la máxima posición** del alumno 1 es 1 (Tabla 5), **la máxima posición** del alumno 2 es 2 (Tabla 4 o 3), **la máxima posición** del alumno 3 es 2 (Tabla 3),  luego el output será:


**Tips**
