### ISSUE TITLE
G - Guardar

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#136]
Acá pueden hacer sus dudas respecto a la pregunta G

**Comment by ignaciohermosillacornejo** [comment]
Complejidad de la solucion O(tamaño del tablero)

**Comment by ignaciohermosillacornejo** [comment]
Este problema es muy parecido al C con algunas modificaciones.

En ambos problemas tenemos un estado inicial y un estado final y queremos buscar el camino más corot entre estos estados. Para encontrar el camino, nos basta hacer un simple BFS desde el estado inicial y detenernos cuando encontremos el estado final. El problema es representar un estado, en el problema C un estado puede ser represetando con la posición X,Y. Acá no, ya que una caja puede estar en una posición X,Y de varias formas distintas (¿De cuantas formas?) por lo que necesitamos codificar más información en el estado.

Una buena forma de ordenar esto y reciclar código del problema C es estructurar su problema de la siguiente forma

```python

def moves(tablero, estado):
    # dado un estado y un tablero, retorna una lista de todos los posibles 


def bfs(tablero, estado inicial, estado final):
     
      # inicializar bfs

      while(q):
           next_states = moves(tablero, current state)
           for next_state in next_states:
                # procesar siguiente estado

```

Si se fijan, la función BFS es agnóstica al problema por lo que esté boilerplate les puede servir para el problema C, solo tienen que cambiar su definición de estado, tablero y la función moves

**Comment by HenryBlairG** [comment]
para leer el input, cada símbolo debería estar rodeado de espacios?
Me refiero a que el input si lo copio del enunciado es el siguiente:
>3 4
.C ..
.E #.
....
4 8
........
.. C .. E ..
........
........
0 0

debería ser así o mas bien como lo mostraré ahora?
>3 4
. C . .
. E # .
. . . .
4 8
. . . . . . . .
. . C . . E . .
. . . . . . . .
. . . . . . . .
0 0

**Comment by ignaciohermosillacornejo** [comment]
Hola! los números estan separados por espacios, los símbolos del tablero no.

Saludos

**Comment by HenryBlairG** [comment]
otra consulta

La caja siempre empezará apoyada en su cara de 1x1? (es posible que en el input se de por ejemplo `....EE....`?)
La salida siempre será una sola casilla? (es posible que en el input se de por ejemplo `......CC....` ?)

**Comment by ignaciohermosillacornejo** [comment]
La cara siempre parte apoyada en su cara 1x1 en la posición C y siempre tiene que terminar en la cara 1x1 en la posición E

**Comment by KnowYourselves** [comment]
Es esta pregunta lograble en Python? :eyes: llegué a una solución que creo que es bastante eficiente pero me tira timeout igual, podría hacer cosas mejor o simplemente mejor hacelro en C?

**Comment by ignaciohermosillacornejo** [comment]
Todas las preguntas son logrables en Python, nos aseguramos de eso. Ojo que si te da TLE y crees que tu solución es rápida, lo más probables es que tu código se quede atascado en un loop infinito o algo del estilo y por eso te de TLE.

**Comment by KnowYourselves** [comment]
En esta pregunta en específico dudo que sea el caso, ya que estoy ocupando la misma estructura BFS que ocupe para los otros ejercicios que la necesitaban, por lo cual sería raro que cayera en un loop 🤔

**Comment by HenryBlairG** [comment]
Me ocurre lo mismo!!

**Comment by ignaciohermosillacornejo** [comment]
El caso más grande es de 1000 x 1000, la respuesta tiene 300.000 pasos y la pauta se demora 300.000 segundos con un BFS sencillo. Cosas a revisar sería:

-  Que estructura usan para guardar su estado, yo use tuplas
-  Como reconstruyen el camino, para reconstruir el camino basta con tener un diccionario que use los estados como llave y guarde como value la movida que se uso para llegar. Después pueden usar una cola para guardar la secuencia de movidas y imprimirla al reves por ejemplo.

En general asegurarse de que entiendan las complejidades de los built-ins de python que esten usando, y usar los adecuados. Por ejemplo piensen en estos dos casos:

```python

# caso 1
q = deque()
q.popleft()
# caso 2
q = []
q.pop(0)

```

En estas dos implementaciones de una cola, hay mucha diferencia entre ellas. El caso 1 tiene complejidad O(1) mientras que la segunda tiene O(k) donde K es el número de elementos en la lista.

**Comment by ignaciohermosillacornejo** [comment]
Hola

Revisé varias de sus códigos y un par estaban bastante cerca del tiempo de la pauta por lo que incremente el márgen de tiempo ligeramente y volví a rejuzgar las soluciones enviadas.

Saludos

**Comment by KnowYourselves** [comment]
Sigo sin poder alcanzar el tiempo requerido y ya no se por donde más optimizar:( Respecto a lo siguiente:

> Como reconstruyen el camino, para reconstruir el camino basta con tener un diccionario que use los estados como llave y guarde como value la movida que se uso para llegar. Después pueden usar una cola para guardar la secuencia de movidas y imprimirla al reves por ejemplo.

No entiendo a que te refieres con guardar la secuencia de movidas en una cola, te refieres a tener una cola de listas con todos los paths que están explorando actualmente?

**Comment by ignaciohermosillacornejo** [comment]
Si tienes guardas en cada estado un puntero al estado padre, tienes dos opciones para generar el camino en sentido padre -> hijo. 
La primera es crear una función e iterar recursivamente haciendo llamadas al padre hasta llegar al primer estado o estado de partida.
La segunda opción es usar una cola, insertando cada estado al inicio de la cola a medida que avanzas, hasta llegar al primer estado o estado de partida.

Sobre lo de optimizar, la verdad es que no sé, para esta pregunta di casí 4 veces el tiempo de la solución de pauta, revisa bien todo. Si usas cosas como deque y otras funciones de python, googlea sus complejidades.

Saludos

Saludos
