### ISSUE TITLE
H - Herencia Sanguínea 

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#137]
Acá pueden hacer sus dudas respecto a la pregunta H

**Comment by santilaguna** [comment]
Hola, cuál es la complejidad esperada?

**Comment by ignaciohermosillacornejo** [comment]
Es un poco complicado, en cada caso de prueba, N determinará el tamaño del grafo y Q el número de consultas. Para cada caso de prueba tienes que crear el grafo inicial O(N^2) y después añadir las N conexiones O(N). 
Luego tienes las consultas, cada una de las Q consultas puede ser resueltas en O(N^2) en el peor de los casos (usamos la peor implementación en la solución de pauta). 

Saludos

**Comment by HenryBlairG** [comment]
Sobre el input, la idea es que en los tests N y Q van a respetar sus intervalos (N &isin; [1, 100]; Q &isin; [1, 40]) o hay que de alguna manera controlar que esto sea así?

**Comment by ignaciohermosillacornejo** [comment]
Los tests respetan los intervalos del enunciado.
