### ISSUE TITLE
I - Indiana Jones y el laberinto de torres 

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#138]
Acá pueden hacer sus dudas respecto a la pregunta I

**Comment by nmaturana97** [comment]
En el enunciado aparece este testcase y muestra como output 9.

4
1 5 2 8
9 7 1 9
3 1 2 1
5 3 5 7
1 0
0

Sin embargo, si seguimos esta linea, ¿no debería ser 7?
1 **5** **2** 8
9 7 **1** 9
3 **1** **2** 1
5 **3** **5** **7**

**Comment by nmaturana97** [comment]
Me di cuenta de que entregaban (i,j) y no (x,y), es decir, empieza en (0,1)

**Comment by ignaciohermosillacornejo** [comment]
Complejidad solución O (E log V)

**Comment by HenryBlairG** [comment]
no entiendo el enunciado donde dice esto

> Las siguientes N lıneas ser´an de largo 2 ∗ N − 1 y tendran un numero que represente la altura de la torre en esa posicion, separados por un espacio

**Comment by Jamidd** [comment]
@HenryBlairG son 2*N-1 ya que se consideran los espacios entre cada número. La  idea es que usen los espacios como separadores entre los números.

**Comment by ajahr95** [comment]
Pruebo con los ejemplos de input del enunciado y me funciona  con sus respectivos outputs, pero me entrega Wrong Answer en el servidor, alguien sabe qué podría pasar? o alguien tiene test para probarlo más?

**Comment by inmadariaga** [comment]
x2 @ajahr95

**Comment by Jamidd** [comment]
Enjoy.

Problemas:

3
2 1 3
2 3 3
4 2 3
1 0
4
0 1 1 1
2 3 2 3
2 6 0 1
4 2 3 4
2 1
5
2 5 4 1 2
1 5 1 1 0
0 3 1 1 2
5 3 3 2 5
3 3 4 2 1
1 2
5
1 5 4 5 3
0 1 0 2 1
0 0 0 0 3
0 5 2 3 3
0 2 2 4 0
0 0
6
6 0 5 6 5 4
4 1 6 6 0 4
4 2 0 7 3 0
0 5 1 5 3 5
0 7 1 7 4 7
3 2 6 3 5 6
0 2
7
5 0 6 7 5 5 1
1 4 5 6 7 1 4
3 3 5 6 3 9 4
5 7 2 8 6 5 3
8 2 3 3 3 5 3
3 8 7 5 7 9 5
2 3 6 2 2 3 1
0 3
9
8 6 5 10 7 5 9 8 3
5 7 8 5 5 10 10 10 2
1 7 10 2 9 10 9 7 11
8 2 4 10 4 4 8 8 1
3 2 2 4 7 11 9 7 7
8 1 5 5 10 7 4 8 5
4 3 1 6 9 1 8 7 1
4 2 9 6 4 7 9 8 7
2 9 1 2 3 5 0 9 7
2 4
10
10 7 2 6 9 5 5 9 10 6
9 8 2 10 10 8 10 4 9 3
1 4 0 2 2 1 0 7 4 0
0 2 1 9 8 0 7 5 10 9
1 5 2 10 0 1 4 0 3 8
8 5 2 7 9 7 8 5 3 6
6 6 7 9 9 9 6 2 4 8
0 6 2 2 6 2 2 4 0 5
5 5 1 8 2 5 4 4 4 6
4 4 10 6 3 2 6 6 5 5
4 1

Resultados:

3
3
5
8
8
9
10
13

**Comment by ajahr95** [comment]
@Jamidd Me entrega exactamente el mismo resultado y aun asi me entrega Wrong Answer en el servidor, no entiendo

**Comment by ajahr95** [comment]
hay alguna posibilidad que sea problema del servidor?

**Comment by Jamidd** [comment]
@ajahr95 Que era? Quizás a alguien más le pueda servir.

**Comment by ajahr95** [comment]
@Jamidd era un error en una linea de mi codigo, en una direccion tenia una igualdad en un elif donde comparaba un x+1 con x+1(debia ser con x solo) por lo que nunca iba a entrar al else.

**Comment by inmadariaga** [comment]
> Enjoy.
> 
> Problemas:
> 
> 3
> 2 1 3
> 2 3 3
> 4 2 3
> 1 0
> 4
> 0 1 1 1
> 2 3 2 3
> 2 6 0 1
> 4 2 3 4
> 2 1
> 5
> 2 5 4 1 2
> 1 5 1 1 0
> 0 3 1 1 2
> 5 3 3 2 5
> 3 3 4 2 1
> 1 2
> 5
> 1 5 4 5 3
> 0 1 0 2 1
> 0 0 0 0 3
> 0 5 2 3 3
> 0 2 2 4 0
> 0 0
> 6
> 6 0 5 6 5 4
> 4 1 6 6 0 4
> 4 2 0 7 3 0
> 0 5 1 5 3 5
> 0 7 1 7 4 7
> 3 2 6 3 5 6
> 0 2
> 7
> 5 0 6 7 5 5 1
> 1 4 5 6 7 1 4
> 3 3 5 6 3 9 4
> 5 7 2 8 6 5 3
> 8 2 3 3 3 5 3
> 3 8 7 5 7 9 5
> 2 3 6 2 2 3 1
> 0 3
> 9
> 8 6 5 10 7 5 9 8 3
> 5 7 8 5 5 10 10 10 2
> 1 7 10 2 9 10 9 7 11
> 8 2 4 10 4 4 8 8 1
> 3 2 2 4 7 11 9 7 7
> 8 1 5 5 10 7 4 8 5
> 4 3 1 6 9 1 8 7 1
> 4 2 9 6 4 7 9 8 7
> 2 9 1 2 3 5 0 9 7
> 2 4
> 10
> 10 7 2 6 9 5 5 9 10 6
> 9 8 2 10 10 8 10 4 9 3
> 1 4 0 2 2 1 0 7 4 0
> 0 2 1 9 8 0 7 5 10 9
> 1 5 2 10 0 1 4 0 3 8
> 8 5 2 7 9 7 8 5 3 6
> 6 6 7 9 9 9 6 2 4 8
> 0 6 2 2 6 2 2 4 0 5
> 5 5 1 8 2 5 4 4 4 6
> 4 4 10 6 3 2 6 6 5 5
> 4 1
> 
> Resultados:
> 
> 3
> 3
> 5
> 8
> 8
> 9
> 10
> 13

@Jamidd  
Me dan los output correctos en el local para estos test también :c

**Comment by almabeta** [comment]
@inmadariaga pudiste arreglarlo? Tenemos un problema idéntico parece :(

**Comment by inmadariaga** [comment]
@almabeta Nop

**Comment by ignaciohermosillacornejo** [comment]
@almabeta @inmadariaga 

Revisen este caso de prueba:

13
0 6 11 6 10 8 7 0 2 7 6 2 3
1 0 7 14 6 11 2 7 11 8 8 10 13
10 11 6 10 4 5 1 9 11 12 7 9 13
3 10 8 12 13 6 12 10 0 3 10 13 12
11 7 8 9 10 8 11 6 9 13 4 11 12
8 1 11 11 10 10 9 13 2 7 8 14 8
6 6 2 12 9 10 1 10 7 9 8 11 14
9 0 1 3 10 14 9 3 2 12 12 5 8
8 6 4 11 9 14 10 13 14 9 11 9 2
5 1 7 12 12 8 9 11 13 2 13 9 12
8 8 11 8 10 8 9 10 0 8 1 11 1
11 13 11 9 9 14 9 10 6 5 9 6 4
11 10 8 13 0 10 2 12 0 13 10 8 10
3 2
7
6 0 6 0 3 7 3
5 4 0 0 1 2 5
6 1 0 2 1 2 1
6 5 0 6 6 2 7
6 6 2 2 5 5 5
7 4 1 2 1 2 5
4 3 3 2 1 3 5
1 1
0

El output debiera ser 
23
10

Saludos y suerte!

**Comment by inmadariaga** [comment]
@ignaciohermosillacornejo Tenia un error al final, lo solucione, me imprime lo mismo para todos los test que tengo, me volvio a tirar wrong answer

**Comment by Jamidd** [comment]
Revisa bien los limites, las diferencias de alturas (para subir y bajar).

**Comment by ignaciohermosillacornejo** [comment]
último caso,

9
0 4 1 3 7 2 5 4 4
5 4 5 0 0 0 2 3 0
2 5 1 2 7 3 0 3 2
3 1 6 0 8 1 3 1 5
5 3 1 9 8 6 0 2 7
7 6 9 9 1 1 2 5 0
3 2 8 3 8 7 4 4 6
1 7 7 8 8 3 2 6 7
1 1 1 3 5 1 3 0 6
2 1
0

El output es:
17

Muchas suerte
