### ISSUE TITLE
J - Juan y la misteriosa carta 

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#139]
Acá pueden hacer sus dudas respecto a la pregunta J

**Comment by B-Dominguez** [comment]
¿Qué complejidad se espera?

**Comment by josemlira** [comment]
Hola @B-Dominguez , se espera una complejidad de O(LNLog(L)) en el peor de los casos, con L el largo promedio de las palabras y N la cantidad de palabras del test.
