### ISSUE TITLE
Tarea 0 - problema GTK y numero de generaciones

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2133-PUC/2019-1#14]
Hola! me pasa que al correr mi código con ````$time ./simulate test/test_XX.txt  Gens````  me queda abierto y esperando a que yo cierre la ventana cuando Gens es un numero pequeño (menos de 28). Esto es un problema que yo debería poder arreglar de alguna manera suponiendo que mi limite de tiempo es de hasta un segundo por generación? Me llama la atención que agregarle los sleeps soluciona el problema, sin embargo al muy alto costo de que mi código queda con sleeps :( Ayudaaaa

**Comment by alopez7** [comment]
Para medir el tiempo de tu programa puedes no llamar a las funciones del watcher para que la ventana no se abra

**Comment by vichoeq** [comment]
Busca como medir el tiempo de una función usando el módulo <time.h>.

**Comment by vichoeq** [comment]
Los sleeps son necesarios para actualizar la ventana, ya que sino es posible que se quede pegado. Eso es un tema de GTK que puede que estorbe un poco pero no es tan terrible.

**Comment by KnowYourselves** [comment]
@vichoeq 

> Busca como medir el tiempo de una función usando el módulo <time.h>.

Podemos utilizar el comando `time` de bash?

**Comment by vichoeq** [comment]
Si puedes pero ese comando mide el tiempo desde fuera de tu programa, es decir, desde que lo lanzas hasta que termina. Si como dices tu programa se queda pegado debido a la ventana, entonces no te sirve medir con eso.

La opcion que dije mide el tiempo _dentro_ de tu programa, por lo que puedes medir especificamente la parte que te interesa medir.

La otra opción como dijo antonio es no abrir la ventana, y en ese caso el comando `time` te sirve.
