### ISSUE TITLE
Dudas administrativas

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#140]
Ej, dudas del scoreboard, calculo de nota, fechas, etc

**Comment by frvalenzuela** [comment]
Tengo una duda con el calculo de nota, en el enunciado de la tarea dice que se podrá tener un máximo de nota igual a 9, pero también dice :

> Su nota dependerá de cuantos problemas logren resolver, donde cada problema vale un punto, y pasado el séptimo, valen 0.5 (su nota se calcula como 1 + Puntaje). 

Basado en eso, si pasado el séptimo valen 0.5 eso quiere decir que el octavo, el noveno y el décimo valen 0.5 no? Eso signficaria que el máximo posible es 8.5, por lo que mi duda es si el máximo o el calculo de puntaje esta incorrecto.

**Comment by ignaciohermosillacornejo** [comment]
Hola!

Si tienes 6 problemas, tienes 6 puntos
7 son 6,5 puntos
8 son 7
9 son 7,5
10 son 8 puntos

Tu nota es 1 + Número de puntos

Saludos

**Comment by smargozzini** [comment]
El output debe ser en un archivo o solo prints en consola?

**Comment by ignaciohermosillacornejo** [comment]
Prints, tal como sale en el enunciado

**Comment by ptflores1** [comment]
Hola ! como compila el servidor el codigo c++ ?

**Comment by mfanselmo** [comment]
Hola! Queria saber cuales son los criterios para seleccionar a los primeros lugares, especificamente si incluye quien resuelve los problemas primero. Digo esto porque ese criterio depende demasiado de que examenes tengamos antes o despues, para darnos tiempo de hacer la tarea.

**Comment by alopez7** [comment]
> Hola! Queria saber cuales son los criterios para seleccionar a los primeros lugares, especificamente si incluye quien resuelve los problemas primero. Digo esto porque ese criterio depende demasiado de que examenes tengamos antes o despues, para darnos tiempo de hacer la tarea.

Los primeros lugares son los que tengan más problemas resueltos. En caso de empate el con menos penalización. La penalización es igual al tiempo que se demoran en resolver cada problema desde el inicio del contest y un pequeño extra por cada intento fallido.

**Comment by mfanselmo** [comment]
> > Hola! Queria saber cuales son los criterios para seleccionar a los primeros lugares, especificamente si incluye quien resuelve los problemas primero. Digo esto porque ese criterio depende demasiado de que examenes tengamos antes o despues, para darnos tiempo de hacer la tarea.
> 
> Los primeros lugares son los que tengan más problemas resueltos. En caso de empate el con menos penalización. La penalización es igual al tiempo que se demoran en resolver cada problema desde el inicio del contest y un pequeño extra por cada intento fallido.

Osea que si empiezo a resolver ahora tengo muchas mas posibilidades de ganar? Encuentro un poco injusto esto porque hay gente con menos exámenes ahora (al menos yo tengo martes, miércoles y jueves) y mas la otra semana. Entonces imposible partir ahora. Se que es un premio extra (y se agradece mucho), pero con ese criterio de penalizacion se le da una ventaja muy grande a algunos alumnos.

**Comment by alopez7** [comment]
Es por eso que no da nota la posición que sacas, sino que es un premio extra. De alguna manera hay que desempatar también.

**Comment by ignaciohermosillacornejo** [comment]
Tu ranking en el scoreboard no afecta en nada tu nota.

**Comment by mfanselmo** [comment]
Sise sise jajajaja, yo solo queria el otro premio 😅

**Comment by ignaciohermosillacornejo** [comment]
> Hola ! como compila el servidor el codigo c++ ?

gcc -std=c++14 -static -O2 [ARCHIVO]

**Comment by HenryBlairG** [comment]
Pregunta vanidosa,

Cómo hicieron los del scoreboard para incluir su nombre?

**Comment by ignaciohermosillacornejo** [comment]
Tienes que completar el campo "Fullname" en options
