### ISSUE TITLE
Problemas servidor

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#141]
Acá podemos ver problemas que tengan como, no puede acceder al servidor, no me entrega una respuesta, se cayó (ojalá no), no se como hacer algo, perdí acceso a mi cuenta.

**Comment by nmaturana97** [comment]
Hola, llevo ya por lo menos 30 minutos esperando respuesta de un problema. Me sale como "Not answered yet".

**Comment by ignaciohermosillacornejo** [comment]
Si, estoy revisando que está pasando con el autojudge

**Comment by nmaturana97** [comment]
Ok,
Si puedes comentar la issue cuando ya lo hayan arreglado lo agradecería
Saludos

**Comment by ignaciohermosillacornejo** [comment]
Ahora esta andando nuevamente @nmaturana97

**Comment by IchottMano** [comment]
@ignaciohermosillacornejo Hola!
Al intentar enviar mi código para el problema C, la página me lanza lo siguiente:
![f](https://user-images.githubusercontent.com/26393051/59969311-6a7f6b80-9518-11e9-9e19-474f9a68251a.png)
 A que se podrá deber esto?
Saludos!

**Comment by ignaciohermosillacornejo** [comment]
Se ve como un problema de tu lado ya que no tengo registro en el servidor de que hayas subido tu código o nada la verdad.
Prueba reiniciar chrome

**Comment by IchottMano** [comment]
@ignaciohermosillacornejo Ya lo he intentado todo, limpiar las cookies y caché, reiniciando chrome, usando firefox, usando modo incógnito, con distintas conexiones a internet, reiniciar el internet, reiniciar el computador y nada funciona :(

**Comment by ignaciohermosillacornejo** [comment]
Resulta que tu código se cae al subirlo al servidor, probablemente por un segfaul o algo parecido y el juez se cae y no entrega respuesta. Prueba haciendo tu problema de nuevo!

**Comment by ptflores1** [comment]
Hola !
Tengo un problema parecido al de @IchottMano, pero subi un archivo que solo imprimia "hola" y aun asi el servidor no responde, puede ser que se haya caido?
Gracias !

**Comment by ignaciohermosillacornejo** [comment]
El servidor está andando, mándame el archivo por interno a mi mail porfa para ver que está pasando.

Saludos

**Comment by ignaciohermosillacornejo** [comment]
Hola @ptflores1 

Revisé que está pasando y el servidor está teniendo problemas compilando tu archivo, se debe está cayendo por algún error de este estilo. En cuanto a la causa específica, no te puedo decir por lo que te recomiendo que te cambies a Python y lo resuelvas así.

Saludos

**Comment by ptflores1** [comment]
Ok, gracias !

**Comment by santilaguna** [comment]
@ignaciohermosillacornejo estoy teniendo problemas con hacer submissions en c++ (E.cpp), la página simplemente deja de funcionar cuando intento subirlo, qué puedo hacer al respecto? (que no sea escribir el código nuevamente en otro lenguaje). Estoy casi seguro que es un problema de la página pq no me acepta algunos archivos solamente

**Comment by ignaciohermosillacornejo** [comment]
Mandame tu código por interno para revisar que está pasando @santilaguna
