### ISSUE TITLE
Tiempo y extension de los tests

### ISSUE THREAD

**Issue by nmaturana97** [IIC2133-PUC/2019-1#143]
Hola, quería saber si podían subir el tiempo máximo y el tamaño de los inputs para los tests de la última tarea, para probar por cuanto se está excediendo el tiempo en casos similares.
Saludos

**Comment by ignaciohermosillacornejo** [comment]
Hola @nmaturana97 

Comente las complejidades adecuadas para cada solución, lo que de ya es un hint. 

Saludos
