### ISSUE TITLE
Test con respuesta correcta T4

### ISSUE THREAD

**Issue by nmaturana97** [IIC2133-PUC/2019-1#144]
Hola, queria saber si podían dar algunos tests públicos para probar que esten haciendo lo correcto nuestros algoritmos, debido a que probar a mano con números tan grandes es imposible.
Gracias

**Comment by ignaciohermosillacornejo** [comment]
Hola @nmaturana97 

No vamos a publicar los casos de prueba, parte de la dificultad de esta tarea es que ustedes piensen los casos bordes y no que simplemente se los demos o digamos. 

Saludos
