### ISSUE TITLE
Tip para los que estan partiendo

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#145]
Vean el scoreboard y revisen cuales son los problemas que más se han resuelto, probablemente quieran partir por ahí.

**Comment by HenryBlairG** [comment]
Para los que escriben las respuestas en python2/3, se pueden usar librerías como numpy o algo parecido para emular arreglos? no es que sea necesario, solo quiero saber para comprender los limites del servidor

**Comment by ignaciohermosillacornejo** [comment]
Puedes usar todas las librerias que vienen por defecto con python. Por ej: Collections, Functools, etc

**Comment by mramirez7** [comment]
Usando python 3, se le puede competir en tiempo a un programa en c? o c va a ser siempre considerablemente más rápido?

**Comment by ignaciohermosillacornejo** [comment]
C y C++ siempre van a ser conciderablemente más rápidos. Los tiempos para cada problema fueron calibrados para todos los lenguajes de programación y testeados por lo que puedes elegir el que más te acomode.
