### ISSUE TITLE
Arbol negro rojo, examen

### ISSUE THREAD

**Issue by Dyoma3** [IIC2133-PUC/2019-1#146]
uno puede hacer las inserciones en un arbol rojo negro segun un arbol 2-3 equivalente. Es decir, puedo hacer las inserciones segun el 2-3 y luego pasarlo a rojo y negro. Esta es una forma valida por si me piden hacer inserciones en un rojo-negro en una pregunta? en la ayudantia, de esta forma, me quedo  el arbol asi
![103E2B43-2B39-4098-AE09-90D096843FE3](https://user-images.githubusercontent.com/17127676/59981147-a45e7980-95cd-11e9-92a5-848f78c0d05d.jpeg)
Es distinto a su solucion pero no esta mal.

**Comment by alopez7** [comment]
Tendrías que hacerlo en un 2-4 ya que el rojo negro puede transformarse siempre a un 2-4 pero no siempre a un 2-3

**Comment by Dyoma3** [comment]
@alopez7 tambien, pero la forma que me refiero es practicamente usar un 2-3, hago la insercion en el 2-3 y simplemente paso de este formato al rojo-negro, ya que siempre puedo pasar un 2-3 a un rojo-negro.

**Comment by alopez7** [comment]
Si se te pide por ejemplo insertar o eliminar podrías hacerlo usando un 2-4, pero si se pide mostrar alguna propiedad en el rojo negro debe ser usando un rojo negro

**Comment by B-Dominguez** [comment]
En la solución de la ayudantía, no debería el 9 ser negro? Como en la diapo 27-28 y en la 29-30 de clases (7 - Arboles RN) al cambiar el color del padre rojo a negro también se cambia el del tío rojo a negro

**Comment by B-Dominguez** [comment]
En la solución de la ayudantía, no debería el 9 ser negro? Como en la diapo 27-28 y en la 29-30 de clases (7 - Arboles RN) al cambiar el color del padre rojo a negro también se cambia el del tío rojo a negro
