### ISSUE TITLE
Versión de python3 para la tarea 4

### ISSUE THREAD

**Issue by Drpinto1** [IIC2133-PUC/2019-1#147]
Hola,
Tengo una duda sobre la versión específica de python 3 que se usará para probar los códigos en el servidor, pues existen funcionalidades que fueron introducidas en ciertas versiones.
Un ejemplo de lo anterior son los _f-strings_, que fueron introducidos en python 3.6

**Comment by ignaciohermosillacornejo** [comment]
Buena pregunta @Drpinto1 

La versión instalada de Python es la 3.6.8

Saludos
