### ISSUE TITLE
Duración examen

### ISSUE THREAD

**Issue by rakarachon** [IIC2133-PUC/2019-1#149]
Hola, es posible saber cuantas horas durará el examen?

**Comment by alopez7** [comment]
Hola, no te puedo asegurar mucho pero 2 horas 30 debería ser lo máximo que dure el examen.

**Comment by JoseRomeroi** [comment]
Hola, en la planilla de notas actualizaron el control 7 con la nota de una pregunta. A qué pregunta corresponde? a la 1 o a la 2? Saludos

**Comment by vichoeq** [comment]
@JoseRomeroi Corresponde a la pregunta 1. Tenemos las planillas conectadas de antemano, ya les avisaremos cuando esté la nota final del C7.
