### ISSUE TITLE
Problema instalación GTK-3 Windows

### ISSUE THREAD

**Issue by kenzoak** [IIC2133-PUC/2019-1#15]
Hola! estoy tratando de correr el código base y me tira error. Instalé xming y corrí el comando "export DISPLAY=:0" en el bash. Pero al ejecutar el make me tira el siguiente error:

Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
src/beholder/main.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:111: recipe for target 'obj/beholder/main.o' failed
make: *** [obj/beholder/main.o] Error 1

Se me genera el simulate, pero al correrlo dándole un test y número de iteraciones no me abre una ventana.  Me sale `Debemos calcular 5 generaciones
Segmentation fault (core dumped)`

**Comment by Regenschrim** [comment]
A mi me sale lo mismo, pero yo no he instalado nada. Solo trate de corre el make para ver como funcionaba el programa pero me sale esto :(

**Comment by bjbarias** [comment]
A mi el make no me tira error, pero me sale lo de 
Debemos calcular 30 generaciones
Segmentation fault (core dumped)

**Comment by alopez7** [comment]
@kenzoak pero instalaste GTK como se explicaba en la guía?

@Regenschrim ... instala GTK

@bjbarias si `make` no tira error, entonces no debería haber problema con GTK. Cómo estás llamando el programa?

**Comment by kenzoak** [comment]
@alopez7  Sí, hice la instalacion de xming y ejecuté el comando en el bash.

**Comment by vichoeq** [comment]
@kenzoak xming no es GTK. Por eso la pregunta es si instalaste GTK, ya que make dice que no lo encontró.

**Comment by bjbarias** [comment]
> @kenzoak pero instalaste GTK como se explicaba en la guía?
> 
> @Regenschrim ... instala GTK
> 
> @bjbarias si `make` no tira error, entonces no debería haber problema con GTK. Cómo estás llamando el programa?

Estaba llamando mal el programa!! ponia test_00.txt en vez de test/test_00.txt.
gracias!

**Comment by kenzoak** [comment]
> @kenzoak xming no es GTK. Por eso la pregunta es si instalaste GTK, ya que make dice que no lo encontró.

Sí, lo instalé desde el bash pero sigo con el mismo error :/

**Comment by kenzoak** [comment]
Me ayudaron en la ayudantía, se había instalado con errores, gracias!

**Comment by vichoeq** [comment]
@Regenschrim al final como te fue?

**Comment by jjaguillon** [comment]
Hola. Estoy teniendo el mismo problema de @kenzoak Me pueden explicar como lo solucionaron.

**Comment by B-Dominguez** [comment]
También tengo el mismo problema que @kenzoak. Además, al instalar gtk no pude instalarlo como libgtk3.0 como dice en la guía porque me sale:

_Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libgtk3.0-dev
E: Couldn't find any package by glob 'libgtk3.0-dev'
E: Couldn't find any package by regex 'libgtk3.0-dev'_

Por lo que lo instalé como gtk3.0

**Comment by caespinoza5** [comment]
¡Hola!

En particular, pueden intentar correr estos dos comandos:
`sudo apt-get update`

Y luego:
`sudo apt-get install libgtk-3-dev --fix-missing`

Además, si tienen problemas, recordar correr el comando
`export LD_LIBRARY_PATH=/usr/include/gtk-3.0/`

Como aparece en la guía.

**Comment by B-Dominguez** [comment]
Hola, ya he intentado las tres opciones
