### ISSUE TITLE
Bellman-Ford

### ISSUE THREAD

**Issue by Cschavez** [IIC2133-PUC/2019-1#150]
Hola! Si bien Bellman-Ford no lo vimos en clases (por lo que recuerdo) en el temario mencionan las rutas más cortas y como este algoritmo está en las clases de años anteriores que nos subieron me entró la duda si es parte efectivamente o no del temario.

Muchas gracias!

**Comment by vichoeq** [comment]
Este semestre no lo vimos, asi que no entra :)

**Comment by JoseRomeroi** [comment]
y Floyd warshall @vichoeq ? Entra?

**Comment by Jiparavich** [comment]
Sumándome a la pregunta de arriba, dado que lo vimos en contexto de programación dinámica, no debería entrar cierto ?

**Comment by vichoeq** [comment]
@Jiparavich exacto. Floyd Warshall no entra.
