### ISSUE TITLE
Calculo de Promedio Final

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#156]
Hola! 

Considerando que las tareas tienen nota máxima mayor a 7, cuando se calcula la nota máxima del curso, se acota el promedio de tareas, o la nota final?

Es decir, si el promedio de tareas me da mayor a 7 se le sumará la nota de cátedra y se dividirá por dos?

Gracias!

**Comment by ignaciohermosillacornejo** [comment]
La fórmula de calcular la nota está publicada en el README de este repositorio.

**Comment by KnowYourselves** [comment]
Mis disculpas, si lo vi, pero no noté el min al final.

Gracias!
