### ISSUE TITLE
Fecha entrega Tarea 4

### ISSUE THREAD

**Issue by vbarros2** [IIC2133-PUC/2019-1#157]
Para cuando es la tarea 4, busque en el enunciado y creo que no sale.

Muchas gracias,

Vicente Barros

**Comment by cafuentes1** [comment]
Hasta el domingo. En la esquina superior derecha de la pagina del servidor sale el tiempo restante.

**Comment by ignaciohermosillacornejo** [comment]
Hola @vbarros2 

Tienes toda la razón, la fecha de entrega debería estar en el enunciado que subimos al repo, de todas formas en el servidor sale el tiempo restante y como comenta @cafuentes1 es para el domingo. Ahora arreglo en enunciado del repo.

Saludos
