### ISSUE TITLE
Perdí mi clave de acceso

### ISSUE THREAD

**Issue by JoseDaroch** [IIC2133-PUC/2019-1#158]
Hace un par de días me metí a la pagina de la T4 y cambie la clave (como sugirieron) pero por alguna razón no logro acordarme cual clave puse 😅, hay alguna solución? 

Muchas gracias!

**Comment by alopez7** [comment]
:/ @ignaciohermosillacornejo

**Comment by ignaciohermosillacornejo** [comment]
Hola @JoseDaroch 

Te reinicié la clave. 

Saludos

**Comment by kenzoak** [comment]
Hola!

Tuve el mismo problema 😭

**Comment by ignaciohermosillacornejo** [comment]
Dame tu usuario @kenzoak

**Comment by kenzoak** [comment]
@ignaciohermosillacornejo  es kandrade

**Comment by ignaciohermosillacornejo** [comment]
Listo, clave reiniciada @kenzoak, suerte en la tarea

**Comment by kenzoak** [comment]
Gracias!
