### ISSUE TITLE
Aproximación notas finales

### ISSUE THREAD

**Issue by zrhftc** [IIC2133-PUC/2019-1#159]
Hola!

Las notas finales de cátedra y tareas se aproximan considerando el segundo decimal? 
Por ej: si una nota de cátedra de 3,95 resultaría en 4.

Gracias!

**Comment by KnowYourselves** [comment]
![image](https://user-images.githubusercontent.com/26102039/60746250-e7183e00-9f4b-11e9-903a-f92da16bda32.png)
Al parecer no.
