### ISSUE TITLE
Tarea 0 - Semillas aleatorias

### ISSUE THREAD

**Issue by firulais33** [IIC2133-PUC/2019-1#16]
Hola,

No entiendo a lo que el enunciado se refiere cuando dice "semillas aleatorias". Que son?

Gracias

**Comment by ignaciohermosillacornejo** [comment]
Que las imagenes que produce el generador son hechas al azar. Sin embargo para empezar a generar numeros al azar hay que elegir una "semilla" o estado inicial. Por ejemplo, los tests que les subimos estan todos hechos con la semilla 1, por lo que si generas tests nuevos con esa semilla, te van a dar los mismos casos que estan en tu repo. Cuando generemos nuevos casos de prueba para corregir su tarea, los haremos con otra semilla al azar (el primer numero entre 100 y 1000 que se me venga a la cabeza). Puedes leer mas del tema acá: https://en.wikipedia.org/wiki/Pseudorandomness
