### ISSUE TITLE
T4 - Citar Codigo

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#160]
Hola!

Para los distintos problemas de esta tarea, podemos utilizar código encontrado en internet y citarlo adecuadamente?

Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Si,

Por ejemplo si vas a hacer el problema H y quieres usar un algorítmo de flujo máximo, esta bien copiar una implementación para usar en el problema (por ejemplo: https://www.geeksforgeeks.org/ford-fulkerson-algorithm-for-maximum-flow-problem/) mientras referencias tu fuente.

Saludos
