### ISSUE TITLE
Uso de Lubuntu en vez de Ubuntu

### ISSUE THREAD

**Issue by fguinez** [IIC2133-PUC/2019-1#17]
Hola!

Hasta ahora estoy usando Ubuntu en una máquina virtual desde OS X, sin embargo está corriendo con lag (a veces muucho lag). Tengo 4 GB de RAM, así que la repartición entre la VM y OS X es ajustada; asumo que eso produce el problema.

Probé también desde un USB Booteable y el rendimiento mejoró un poco, pero no demasiado. Y sin contar los problemas de persistencia y compatibilidad implica.

Así que, **¿habrá algún inconveniente en usar una máquina virtual de [Lubuntu](https://lubuntu.net/)? ¿funcionará Valgrind correctamente en esta distribución?**

La RAM que pide Lubuntu es muchísimo menor (512 MB por lo que he leído), así que sería ideal para mi. Pero dado que las tareas están pensadas para ejecutarse en Ubuntu, no estoy bien informado de hasta donde llega la similitud entre ambas distribuciones.

Un saludo ✌️

**Comment by vichoeq** [comment]
Lubuntu es simplemente ubuntu con un distinto motor gráfico, asique la funcionalidad **debería** ser idéntica.

**Comment by alopez7** [comment]
Ojo que el lag se puede deber al poder gráfico que le estás asignando a la máquina virtual. Puedes probar dándole más tarjeta de video

**Comment by vichoeq** [comment]
@fguinez Al final como te fue?

**Comment by JoseRomeroi** [comment]
@fguinez Me pasaba lo mismo usando maquina virtual desde OS X. Se me arreglo editando la configuración y asignándole más procesadores. (Por default solo usa 1)

**Comment by fguinez** [comment]
Finalmente probé Lubuntu, Xubuntu y Kubuntu.

Lubuntu  y Xubuntu funcionaban bien, así que me quedé con el último pq es un poco más completo.

Probé distribuyendo la tarjeta gráfica de diferentes formas y no hizo gran diferencia. Lo que sí **sirvió mucho fue aumentar los procesadores**, no me había dado cuenta que solo estaba usando 1.

Gracias a todos!
