### ISSUE TITLE
Instalación GTK

### ISSUE THREAD

**Issue by Regenschrim** [IIC2133-PUC/2019-1#18]
Sorry lo perdido pero por lo que entendí hay una guía para instalar gtk y la he buscado en todos los repos y en todos lados pero sigo sin encontrarla. Se que podría googlear como hacerlo, pero no se si tendrán algún tipo de configuración que es especifica, entonces preferí no arriesgarme. Uso windows btw.
Gracias de antemano.

**Comment by alopez7** [comment]
Está en la wiki del repositorio
