### ISSUE TITLE
Cuando usar Type Casting en C

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#19]
hola!

Estudiando de las guías y por mi cuenta me surgió esa duda. Aparte de los casos obvios (como hacer cast de un `int` a un `float` en una división) en que otros casos es verdaderamente útil esta herramienta? 

Gracias!

**Comment by alopez7** [comment]
Son pocos los casos en que castea en general. Cuando se trabaja con punteros void se castean antes de usarlos pero es un caso que no se va a usar mucho en el curso.

**Comment by alopez7** [comment]
En general uno trabaja con el tipo que va a usar desde el comienzo. Si haces un cast probablemente pudiste usar el tipo final desde el principio

**Comment by vichoeq** [comment]
C tambien tiene typecasting implicito para algunos tipos.

Eso hace que puedas asignar `ints` a variables `float`, por ejemplo. O, lo que es equivalente, pasarlos como parametro a una funcion:

```c

double pow(double base, double exponent)
{
    // Calcular la potencia
}

// Y en alguna parte de tu codigo...

int a = 7;
int b = 2;

int c = pow(a, b);

```

**Comment by vichoeq** [comment]
Lo que puede ser inesperado es que al asignar un `int` con un valor `double` se guarda solo la parte entera. (Por ejemplo 7.999999 pasa a ser 7)

**Comment by KnowYourselves** [comment]
Muchas gracias!, ahí me quedó clarísimo!

**Comment by jmwielandt** [comment]
¿El Type Casting gasta ciclos CPU (por ejemplo de uint8_t a int)? 🤔
Es que tengo que hacerlo para un par de cálculos 😰😰

**Comment by vichoeq** [comment]
@jmwielandt https://stackoverflow.com/questions/16539412/does-typecasting-consume-extra-cpu-cycles

Por qué necesitas castear de uint8_t a int?

**Comment by jmwielandt** [comment]
@vichoeq porque necesito restarlos y tener la opción de que me salgan negativos, además `-1%4 == -1`
En el mejor o peor caso, tendría que cambiar varias variables por uint32_t para asegurarme que los tamaños estén bien siempre
Pero sigo teniendo el problema de que necesito restarlos con signo

**Comment by vichoeq** [comment]
@jmwielandt si no me equivoco los cálculos se hacen todos usando el tamaño de los registros (32 o 64 bits) y solamente a la hora de guardarlo en la variable se trunca (a 8bits en este caso)
