### ISSUE TITLE
Tarea 0 - Colores en Beholder

### ISSUE THREAD

**Issue by jmwielandt** [IIC2133-PUC/2019-1#20]
Hola, creo que tienen un bug en el main.c de beholder. Me puse a modificar los colores que quería y en la función change_pixel_color los parámetros entran, supuestamente, en el orden RGB, sin embargo descubrí que en la práctica entran como BGR (al revés).

Para arreglarlo, tienen que cambiar esto en `beholder/main.c`:
![imagen](https://user-images.githubusercontent.com/37153467/54872592-147a1b00-4da5-11e9-9b1b-1b206aefcb38.png)

Si ponemos estos colores para la piedra, el papel y la tijera:
![imagen](https://user-images.githubusercontent.com/37153467/54872602-468b7d00-4da5-11e9-8a87-e8ab4c125b47.png)
Piedra -> 0xFF0000
Papel -> 0x00FF00
Tijeras -> 0x0000FF

Imagen test 2 antes del fix:
![imagen](https://user-images.githubusercontent.com/37153467/54872569-b0efed80-4da4-11e9-803b-ed3fe3c17d03.png)

Imagen test 2 luego del fix:
![imagen](https://user-images.githubusercontent.com/37153467/54872558-6cfce880-4da4-11e9-8476-b67452d718f3.png)

Para mí es más cómodo poder modificar los colores a unos más intuitivos :D

**Comment by vichoeq** [comment]
Hola, si, efectivamente es al revés.

Originalmente esta interfaz gráfica trabajaba con blanco y negro, por lo que no importaba el orden, pero al adaptarla para esta tarea se nos fue ese detalle.

Gracias por hacerlo notar. No vamos a subir un update al respecto porque no afecta en nada para la tarea, pero si alguien quiere modificar los colores de su ventana le puede servir esto :)
