### ISSUE TITLE
Tarea 0 - Problema abriendo archivos

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2133-PUC/2019-1#21]
Hola! Al momento de abrir los archivos correspondientes a los test 5, 6 y 7, no ocurre nada. Siendo que si abro otros archivos, se abre bien, y hace todo lo que pido.
```c
int main(int argument_count, char** arguments)
{
	if (argument_count != 3)
	{
		printf("Modo de uso: %s <estado inicial> <generaciones>\n\n", arguments[0]);
		printf("\testado inicial: archivo de texto plano que contiene la descripción inicial de la comunidad bacteriana\n\n");
		printf("\tgeneraciones: número de generaciones totales que deberán simularse\n");
		return 1;
	}

	
	char* filename = arguments[1];

	
	uint32_t generation_count = atoi(arguments[2]);
	printf("Debemos calcular %d generaciones\n", generation_count);

	
	FILE* file = fopen(filename, "r");
	// Haciendo printf's, llega hasta esta linea
	
	uint8_t height, width;
	// No imprime nada aca
```

No he modificado nada de estas primeras lineas del main. Y en la consola no muestra ningún error, solo termina _exitosamente_.

[Edit 1] Lo corrí en el servidor de la universidad que pasan para Sistemas Operativos, y en un Raspberry PI (Ubuntu 16.04 ambos) y el mismo error. 
Gracias!!

**Comment by ignaciohermosillacornejo** [comment]
Hola, prueba haciendo esto y dime que sucede:

```C
int main(int argument_count, char** arguments)
{
	if (argument_count != 3)
	{
		printf("Modo de uso: %s <estado inicial> <generaciones>\n\n", arguments[0]);
		printf("\testado inicial: archivo de texto plano que contiene la descripción inicial de la comunidad bacteriana\n\n");
		printf("\tgeneraciones: número de generaciones totales que deberán simularse\n");
		return 1;
	}

	
	char* filename = arguments[1];

	int generation_count = atoi(arguments[2]);
	printf("Debemos calcular %d generaciones\n", generation_count);

	
	FILE* file = fopen(filename, "r");
	
	int height, width;
	fscanf(file, "%d", &height);
	fscanf(file, "%d", &width);
         
        printf("height: %d", height);
        printf("height: %d", width);
```

**Comment by smargozzini** [comment]
A mi me pasa lo mismo, me corre el print 1 y 2 pero el 3 no, y en la consola me aparece esto:

Debemos calcular 3 generaciones
1
2
Segmentation fault: 11

no e cambiado el código 
```
/* El primer parametro es el nombre del archivo */
	char* filename = arguments[1];

	/* El segundo parametro es la cantidad de generaciones a simular */
	uint32_t generation_count = atoi(arguments[2]);
	printf("Debemos calcular %d generaciones\n", generation_count);

	/* Abrimos el archivo y creamos el stream de lectura */
	FILE* file = fopen(filename, "r");
	
	printf("1\n");

	/* Las variables donde guardaremos el alto y ancho */
	uint8_t height, width;

	printf("2\n");

	/* Leemos el alto y el ancho */
	fscanf(file, "%hhu %hhu", &height, &width);

	printf("3\n");

	/* Abrimos la ventana con las dimensiones dadas */
	watcher_open(height, width);

	/* Variable donde iremos guardando lo que leamos del archivo */
	uint8_t value;
```

**Comment by santiagocruzb** [comment]
@ignaciohermosillacornejo no es eso. @velubascher descubrió que es un problema con el watcher. 

**Si se comenta la línea** `watcher_set_cell(row, col, value);`, entonces funciona bien. Como estoy ejecutando el programa en servidores por ssh, no sé si tiene que ver con eso. Tampoco sé que pasará al momento de correrlo con el `watcher`.
Quedo atento a sus comentarios

**Comment by vichoeq** [comment]
@santiagocruzb 

Obviamente no vas a poder abrir una ventana si estas trabajando por ssh. Y si se llega a abrir no la vas a poder ver. 

¿Por qué no estás usando tu computador?

**Comment by B-Dominguez** [comment]
Hola, estaba corriendo la simulación completa en con el test 1 (o 0, no estoy seguro) y corría bien. Luego quise cambiar al test 7 y tuve el segmentation fault. El error es en la misma línea que @smargozzini . No revisé con Valgrind cuando corría, pero ahora el mensaje de Valgrind es:

> ==132== error calling PR_SET_PTRACER, vgdb might block
> Debemos calcular 20 generaciones
> file abierto
> leere height y width
> ==132== Invalid read of size 4
> ==132==    at 0x4EB824D: __isoc99_fscanf (isoc99_fscanf.c:30)
> ==132==    by 0x108B61: main (main.c:39)
> ==132==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
> ==132==
> ==132==
> ==132== Process terminating with default action of signal 11 (SIGSEGV)
> ==132==  Access not within mapped region at address 0x0
> ==132==    at 0x4EB824D: __isoc99_fscanf (isoc99_fscanf.c:30)
> ==132==    by 0x108B61: main (main.c:39)

**Comment by vichoeq** [comment]
Asegurate de pasar el nombre del archivo correctamente como parámetro. 

¿Cómo lo estas llamando?

**Comment by B-Dominguez** [comment]
Fue un typo lo siento, revisé mucho antes de comentar la issue, pero creo que es hora de acostarme
