### ISSUE TITLE
Tarea 0 - Duda tipos de datos

### ISSUE THREAD

**Issue by svergara1** [IIC2133-PUC/2019-1#22]
Hola! Entiendo que el valor máximo de un unsigend char (uint8_t) es 255 y ese es el que nos entregan en el main. 
¿Puedo cambiar uint8_t por uint16_t para mi programa?

**Comment by alopez7** [comment]
Si puedes. La idea es que uses el tipo adecuado para lo que necesites

**Comment by vichoeq** [comment]
Si, no hay problema, tu escribe tu programa como mas te acomode. Lo que si no puedes modificar es el watcher, ya que está fuera de la carpeta simulate.
