### ISSUE TITLE
watcher_refresh deja de hacer efecto

### ISSUE THREAD

**Issue by fnquinteros** [IIC2133-PUC/2019-1#23]
Hola!

Es normal que después de algunas iteraciones, watcher_refresh deje de actualizarme la pantalla?

Estoy ejecutándolo siempre antes de empezar cada generación y me funciona durante al rededor de 10 generaciones. Estoy printeando el resultado numérico de cada generación y veo que cambia, pero no hay cambios en la interfaz gráfica :confused: 

**Edit**:

Falla sólo cuando pongo menos de 1 segundo de sleep entre una generación y otra. :disappointed: 

Saludos

**Comment by vichoeq** [comment]
Si, desgraciadamente, eso está fuera de nuestro control. Usamos GTK porque está en C y corre en todas las plataformas, pero tampoco está diseñada para el uso que le damos.

Yo lo pienso como que si se le mandan request muy seguidos la ventana se stunea... 

No te preocupes que a la hora de correjir no vamos a abrir realmente la ventana, asi que eso no será problema.

**Comment by nachocontreras** [comment]
Lo mismo me ocurre con el watcher_close(), para los test 0, 1 y 2, la ventana no se cierra si es que se ejecutan pocas generaciones. Por lo que el tiempo de ejecución no termina hasta cerrar la ventana manualmente 😞.

Si no abren la ventana no habrá problema según yo.  
O no? 🤔
