### ISSUE TITLE
Error Recurrente

### ISSUE THREAD

**Issue by Jiparavich** [IIC2133-PUC/2019-1#24]
Hola!!
Llevo un buen rato intentando arreglar un error que me sale inmediatamente después de abrir la ventana de la GUI, básicamente, se abre la GUI,  luego se mete a un for (que yo implemente) y muere a la primera iteración...
Alguna idea que puede ser? 

El error es:

"Segmentation Faul( core dump ) "

**Comment by ignaciohermosillacornejo** [comment]
Probablemente tienes un error en tu código, lo que esta haciendo que se caiga tu programa. Prueba debugearlo poniendo un print y moviendolo hasta encontrar la linea que hace que tu código se caiga
