### ISSUE TITLE
Tarea 0 - Problema con test_07.txt

### ISSUE THREAD

**Issue by firulais33** [IIC2133-PUC/2019-1#25]
Hola, 

Mi programa funciona bien para todos los test excepto el test_07, donde despues de 11 iteraciones el programa se cae con el error Segmentation Fault (core dumped). Esto solo pasa con este test, y no se bien porque. Alguien sabe?

EDIT: Cuando corro el programa con el comando // $ valgrind --tool=memcheck --leak-check=yes ./simulate test/test_07.txt 50 // corre perfectamente.

Muchas gracias!

**Comment by vichoeq** [comment]
Corre perfectamente con valgrind? No reporta niun error de memoria?

Estas usando arreglos de heap o de stack? Recuerda que si cometes errores usando arreglos de stack valgrind no es capaz de detectarlos.
