### ISSUE TITLE
Error: Violación de Segmento ('core' generado)

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2133-PUC/2019-1#26]
Hola, qué tal? 
Para la T0 estoy generando una matriz a partir del código:
```c
uint8_t **mat_i = (uint8_t **)malloc(height * sizeof(uint8_t*));

for (int i = 0; i < height; i++)`
{
	mat_i[i] = (uint8_t *)malloc(width * sizeof(uint8_t));
}
if (mat_i==NULL)
{
	printf("Error encontrando memoria\n");
	return 1;
}
```
Se puede encontrar en internet así que supongo que no estoy revelando nada importante.
A esta matriz le doy valores y luego de eso los imprimo:
```c
for(uint8_t row = 0; row < height; row++)
{ 	
	 /*Para cada columna*/ 
	for(uint8_t col = 0; col < width; col++)
	{	
		mat_i[row][col] = "valor"; //Este valor no lo doy ya que es irrelevante con respecto a mi error
		printf("%d ",mat_i[row][col]);
	}
	printf("\n");
}
```
Hasta acá ningún problema, pero luego, al momento de hacer un segundo intento dentro de un "for" de la siguiente forma: 
```C
for(uint8_t rec = 0; rec < generation_count; rec++)
{	
	for(uint8_t row = 0; row < height; row++)
	{ 	
	      /*Para cada columna*/ 
	        for(uint8_t col = 0; col < width; col++)
		{	
			mat[row ][col] = valor;
			printf("%d ",mat[row][col]);
		}
		printf("\n");
	}
	//// VIOLACION DE SEGMENTO ////
	printf("%d Estamos aca", mat_i[0][0]);
         ...
}
```

El programa logra printear todo pero llega hasta VIOLACION DE SEGMENTO y luego el resto del código no lo ejecuta. ¿A qué se debe esto?
Gracias

**Comment by alopez7** [comment]
Se ve bien excepto porque usas mat en vez de mat_i

**Comment by nfbalbontin** [comment]
Ese fue un error de tipeo al pasarlo a esta issue, pero está como mat_i y aún así me arroja el error

**Comment by nfbalbontin** [comment]
ahora revisé mejor y se cae cuando llega a: 
`printf("%d Estamos aca", mat_i[0][0]);`

**Comment by nfbalbontin** [comment]
Por alguna extraña razón - a pesar de que llevo desde ayer tratando de debugearlo - ya no arroja el error .-. 
Gracias

**Comment by ignaciohermosillacornejo** [comment]
Muy extraño, probablemente tienes comportamiento no definido en tu tarea. Asegurate de correrla en Ubuntu antes de subirla para revisar que este todo bien

**Comment by ajahr95** [comment]
Yo tengo un mac y no me genera ese problema al correrlo en ios pero al probarlo en linux ubuntu, si bine me deja compilar, al correr el ./simulate  me entrega el mensaje de violación de segmentos por lo que no retorna nada.
