### ISSUE TITLE
Precorregir la T0

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2133-PUC/2019-1#27]
### Instrucciones generales

La motivación para hacer esto es que el semestre pasado hubieron muchas recorreciones menores por errores muy tontos y ahora son demasiados alumnos, por lo que queremos reducir eso, además recibimos feedback de los alumnos que les hubiera gustado poder corregir sus tareas de antemano para saber como estaban sus tareas.

Para obtener el 7 su tarea debe cumplir las siguientes tres cosas: 
1. Que su código sea correcto
2. Que su código sea eficiente
3. Que valgrind reporte que no tienen errores de memoria y leaks posibles

#### MUY IMPORTANTE es que corran su programa en Ubuntu por lo menos una vez y revisen que este todo bien, no importa que en su OS la tarea les corra perfecto y sin errores, si no la prueban en Ubuntu y se les cae el programa, van a tener un 1 y se les penalizará la nota al recorregir

Adjunto instrucciones para revisar cada item, **leanlas con cuidado por favor**:

### Las instrucciones para revisar que su código esté **correcto** son las siguientes:

1.1 Eliminar o comentar todos los `printf` de su código (no impriman nada en consola)
1.2 Reemplazar el archivo `watcher.c`con el que estoy adjuntando en esta issue (el que se encuentra actualmente lo pueden poner debajo de la carpeta `Programa` mientras tanto)
1.3 Colocar el código `judge.py` que estoy adjuntando en esta issue adentro de la carpeta `Programa` en su repositorio
1.4 Colocar la carpeta `solutions` que estoy adjuntando en esta issue adentro de la carpeta `Programa` en su repositorio
1.5 Compilar su código con `make`
1.6 Ejecutar el siguiente comando, donde `[test_xx.txt]' es el path al caso de prueba que quieren revisar.
```bash
./simulate [test_xx.txt]  10 > output.txt
```
1.7 Ejecutar el siguiente comando, donde `[solution_xx.txt]` es el path al archivo de solución correspondiente al caso de prueba que ejecutaron en el paso 1.6
```bash
python3 judge.py output.txt [solution_xx.txt]
```
1.8 El output del paso 1.7 es su nota para ese caso de prueba.
1.9 Si quieren revisar otro caso de prueba, deben borrar el archivo `output.txt` y volver a ejecutar los pasos del 1.6 en adelante

###  Las instrucciones para revisar que su código esté **eficiente** son las siguientes:

1. Eliminar todos los `sleep` y `usleep` de su código
2. Compilar usando make
3. Ejecutar el siguiente comando,  donde `[test_xx.txt]` es el path al caso de prueba que quieren revisar.
```bash
time ./simulate [test_xx.txt]  10 > output.txt
```
Les va a entregar un output del tipo 
`./simulate test/test_07.txt 10 > output.txt  0.15s user 0.02s system 99% cpu 0.175 total`
done se tienen que fijar que el tiempo al lado de `total` sea menor a 10 segundos. En el ejemplo pueden ver que es 0.175.

###  Las instrucciones para revisar que su código no tenga problemas de memoria
1. Compilar usando make
2. Ejecutar el siguiente comando,  donde `[test_xx.txt]` es el path al caso de prueba que quieren revisar.
```bash
valgrind ./simulate [test_xx.txt]  10 > output.txt
```
![valgrind](https://user-images.githubusercontent.com/11488721/55265817-ab891c00-5258-11e9-98ef-c967a0816c60.jpg)

- Si valgrind dice _"ERROR SUMMARY: 0 errors from 0 contexts"_ entonces tienen el puntaje de errores de memoria
- Si valgrind dice _"All blocks were freed -- no leaks are possible"_ entonces tienen el puntaje de _memory leaks_

Finalmente, cualquier pregunta, la pueden hacer en este issue, pero **lean primero en detalle todas las instrucciones!**

Éxito en sus tareas!

Pueden descargár los archivos acá: [Archive.zip](https://github.com/IIC2133-PUC/2019-1/files/3024860/Archive.zip)

**Comment by fgbruna** [comment]
Tengo dos dudas:
+ Cada una de las mediciones requiere haber hecho lo anterior?, es decir, para medir el tiempo es necesario que hayamos reemplazado watcher.c y así sucesivamente...
+ No encuentro una versión de time que muestre algo distinto a los sgtes tiempos:
    ```bash
     real    <t0>
     user    <t1>
     sys     <t2>
    ```
Es alguno de ellos equivalente al tiempo que mencionas ?

**Comment by ignaciohermosillacornejo** [comment]
Hola!

Para medir el tiempo en verdad no afecta mucho si reemplazas el watcher o no, pero al momento de corregir lo vamos a reemplazar.


Sobre tu otra pregunta, el tiempo es el que dice "real"

**Comment by nfbalbontin** [comment]
Hola, qué tal? 
Una pregunta. Para facilitar la corrección, si realizamos la pre-corrección, ¿dejamos los archivos cambiados en el repositorio o los dejamos como la carpeta original? - es decir con el watcher.c original, sin la carpeta solutions y sin el judge.py - 
Gracias

**Comment by ignaciohermosillacornejo** [comment]
No importa en los dos casos

**Comment by Drpinto1** [comment]
Hola!
Tenemos que borrar también el/los `printf` que venían en el main? (el que indica cuantas generaciones se van a calcular)

**Comment by alopez7** [comment]
Eso no afecta a la corrección

**Comment by fnquinteros** [comment]
Hola!
Es normal que mi programa tome más tiempo en ejecutarse con el nuevo watcher.c que con el antiguo?

**Comment by ajahr95** [comment]
El output no me genera nada, solo el "Debemos calcular 10 generaciones". Cambie el archivo watcher.c y todo lo que se dijo en las instrucciones. De todas maneras se me sigue abriendo la interfaz no se si eso está bien.

**Comment by alopez7** [comment]
@ajahr95 debes compilar denuevo

**Comment by alopez7** [comment]
@fnquinteros mientras no sea demasiado tiempo extra no es un problema

**Comment by ajahr95** [comment]
@alopez7 lo compile nuevamente, pero aun así no hay cambios, lo único que pude hacer para probar mi programa es reemplazar los watcher por los respectivos prints de cada función, pero los tendré que quitar al subir la tarea, por ende no se si a ustedes no se les generará nada en el archivo output finalmente.

**Comment by Sgwa** [comment]
Hola! creo que hay un problema con las soluciones adjuntas.

![image](https://user-images.githubusercontent.com/20805372/55282998-291f5b80-532f-11e9-901a-9985b20af599.png)

En el test 01 tenemos que el primer numero es 0 y esta solo rodeado por dos 1 y un 2, por lo que no se cumple tener 3 o mas vecinos que lo derroten, sin embargo en el archivo solution_01.txt, en la primera iteracion aparece cambiado a 1.

![Screenshot from 2019-03-30 21-05-45](https://user-images.githubusercontent.com/20805372/55283036-0b062b00-5330-11e9-8554-9db12a3cdf1d.png)

Tambien se puede ver que el tercer valor correspondiente a 1 originalmente es cambiado a 2, cuando solo tiene dos 2, dos 1 y un 0 de vecinos, otra vez, no hay tres 2 de vecinos para derrotar al 1. 
Esto causa que me marque mal mi solucion.

**Comment by Dunkan1** [comment]
Hola, es un toro asi que siempre hay 9 numeros que los rodean
espero que con este dibujo quede mejor explicado
![IMG_20190330_215820](https://user-images.githubusercontent.com/26102365/55283306-92ef3380-5336-11e9-9a55-f8f6b899060e.jpg)

**Comment by Sgwa** [comment]
aaa, se me paso eso, gracias!

**Comment by shantifabri** [comment]
Hola, estoy tratando de precorregir mi tarea pero me ocurre un error al correr el judge.py. El error es el siguiente:
![error](https://user-images.githubusercontent.com/37163566/55284121-c1cdcf80-535f-11e9-9903-45e52273bcc9.png)

Además me entró la duda de si la cantidad de generaciones a simular incluye al estado base? O es la generación base más las generaciones a simular, siendo el total el parametro ingresado +1 ?

**Comment by Sgwa** [comment]
comenta el print: `printf("Debemos calcular %d generaciones\n", generation_count);` para que no te aparezca ese error.

por lo que vi del las solutions, hay 11 estados, 10 son las generaciones nuevas y 1 el estado inicial, ingresando 10 como las generaciones a simular.

**Comment by shantifabri** [comment]
El judge.py me estaba dando siempre como output 1.55 a pesar de tener bien las iteraciones. Revisé y comparé los archivos solution_xx.txt con el output.txt y me di cuenta que en este último aparece lo que imprimen las funciones watcher_open(height, width) y watcher_close(), y que en la solución no aparece. Después de comentar todos los watcher_open y watcher_close el judge.py entregó el output correspondiente, asi que creo que tambien es necesario comentar esas funciones en el main.c.

**Comment by Cadagan** [comment]
@shantifabri tengo tambien el mismo problema con judge.py

Traceback (most recent call last):
  File "judge.py", line 36, in <module>
    output_board   = load_board(sys.argv[1])
  File "judge.py", line 22, in load_board
    m, n = [int(x) for x in f.readline().split()] # sacamos los valores n y m que vienen del WATCHER_OPEN
ValueError: not enough values to unpack (expected 2, got 0)

Comente todos los printf, pero el problema sigue :(

**Comment by shantifabri** [comment]
@Cadagan como lo estas ejecutando?

**Comment by Tyrell-Wellick** [comment]
Hice lo que dicen en las instrucciones, pero se queda pegada mi consola después de ejecutar el comando de la instrucción 1.6. Se me abre una ventana del beholder que muestra el estado final y de ahí no sale.

Gracias de antemano, aiuda

**Comment by mundurragac** [comment]
Hola, cual va a ser el límite de generaciones en cada test?  Para verificar si se pasa o no del tiempo límite (10 segundos)

Gracias de antemano!

**Comment by Sforrego** [comment]
> Hola, cual va a ser el límite de generaciones en cada test? Para verificar si se pasa o no del tiempo límite (10 segundos)
> 
> Gracias de antemano!

Por lo que tengo entendido los 10 segundos son para el caso test_07.txt 10, osea el mas grande con 10 generaciones, ademas las soluciones solo llegan a la 10ma generacion.

**Comment by santiagocruzb** [comment]
En la primera iteración no se imprime el REFRESH, pero después si. Entonces me difiera en todas las iteraciones en una instrucción. Si no se imprime el primer REFRESH, pero el resto si, no veo cómo pueda solucionar eso.

![image](https://user-images.githubusercontent.com/13748925/55290888-35e39400-53af-11e9-9397-84ebcbe682cd.png)

**Comment by shantifabri** [comment]
@santiagocruzb fijate si no borraste o comentaste el watcher_refresh() que venía inicialmente en el main.c.

**Comment by jmwielandt** [comment]
Aporte para facilitar la autocorrección y debuggeo:
Usen este watcher, lo deja como .csv (formato excel)
[watcher.zip](https://github.com/IIC2133-PUC/2019-1/files/3026862/watcher.zip)

Y con esto pueden transformar un test solución a .csv automáticamente
[transformer.zip](https://github.com/IIC2133-PUC/2019-1/files/3026865/transformer.zip)

Con excel pueden usar `=igual(xx;yy)` y les dice si son o no iguales.
Mi error estaba en el orden de los for y así me pude dar cuenta.
En libreoffice creo que se llama parecido.

**Comment by Cadagan** [comment]
> @Cadagan como lo estas ejecutando?

sigo las instrucciones al pie de la letra :/

**Comment by Cadagan** [comment]
@shantifabri exactamente como dicen las instrucciones :/

**Comment by shantifabri** [comment]
@Cadagan fijate en los nombres de los archivos y que le estas pasando la cantidad necesaria. Me pasó un par de veces que ponía solution/solution_xx.txt en vez de solutions/solution_xx.txt

**Comment by Tyrell-Wellick** [comment]
Por qué hay números distintos a 0, 1 y 2 en los archivos de solución? ...

**Comment by fdominguezclaro** [comment]
@Cadagan yo tenía el mismo error en MacOS, por alguna razón al correr make, el watcher nuevo no se compilaba. Lo arreglé eliminando todos los ejecutables y compilando todo de nuevo.

**Comment by fguinez** [comment]
> El output no me genera nada, solo el "Debemos calcular 10 generaciones". Cambie el archivo watcher.c y todo lo que se dijo en las instrucciones. De todas maneras se me sigue abriendo la interfaz no se si eso está bien.

@ajahr95 ¿finalmente pudiste solucionar el problema? A mi me pasa lo mismo al correr la tarea en Ubuntu, solo se guardan en `output.txt`los printf realizados directamente en `main.c`, no los que salen de `watcher.c`.

Sin embargo, si realizo exactamente el mismo procedimiento en MacOS todo sale perfecto.

**Comment by fguinez** [comment]
@ajahr95 Ya encontré la solución. Todo me funcionó correctamente en Ubuntu luego de comentar (o borrar) la quinta línea del nuevo `watcher.c`. Me refiero a:

```
#define WATCHER "./beholder"
```

Al parecer el problema era que se abría la interfaz, pero al ya no estar implementadas las antiguas funciones de `watcher.c` ya no había forma de comunicarse con ella dejando el programa colgado.
