### ISSUE TITLE
Warnings al usar judge y el nuevo watcher

### ISSUE THREAD

**Issue by santilaguna** [IIC2133-PUC/2019-1#29]
![Captura de pantalla 2019-03-30 a la(s) 16 55 26](https://user-images.githubusercontent.com/37159412/55281046-42171500-530d-11e9-9327-a34f5020cc0a.png)

Hola, quería saber si esto es normal y por qué ocurre. Los test corren normalmente, pero antes sólo tenia el primer warning (tampoco sé el motivo).

**Comment by vichoeq** [comment]
Hola, por simplicidad compilamos todos los programas incluyendo los flags de GTK.

El `beholder`, que es la ventana, si ocupa GTK, pero el generador y el simulate no lo ocupan, por eso tu compilador te advierte.

**Comment by santilaguna** [comment]
Ahhh, gracias!!
