### ISSUE TITLE
Libro recomendado?

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2019-1#3]
Hola! me gustaría saber si me recomendarían algún libro guía para estudiar la programación en C.
Saludos!

**Comment by alopez7** [comment]
No hay un libro guía para C que conozca que pero hay buenos tutoriales. Te recomiendo ver las guías que subimos de punteros y arreglos e ir a los talleres

**Comment by naquiroz** [comment]
Yo me leí unos cuantos capítulos de [este libro](https://www.amazon.com/Programming-Language-Brian-W-Kernighan/dp/0131103628). Muy bueno, recomendado. Está en library genesis.

**Comment by alopez7** [comment]
@naquiroz Ojo que nosotros usamos C 2011 o 2018, no ANSI C (un standard antiguo).
