### ISSUE TITLE
Informe

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2133-PUC/2019-1#30]
Hola, en la complejidad de la simulación se refiere al número de comparaciones por iteración? número de comparaciones en algoritmo para determinar si bacteria cambia de estado?

En mi caso el número de comparaciones en el algoritmo es fijo. por lo que el worst case, best case y caso promedio sería siempre el mismo teórica y empíricamente. 

Gracias

**Comment by B-Dominguez** [comment]
Gracias! Hay algún comando para medir esto? o alguna fuente de información donde pueda aprender a hacerlo? Estuve en la ayudantía cuando mostraron algo pero no alcancé a entender desde el principio.

**Comment by alopez7** [comment]
Mide el tiempl de tu programa modificando los parámetros y ve cómo cambia el tiempo segun los valores dados
