### ISSUE TITLE
Intorfe T0 - 'gtk/gtk.h' file not found

### ISSUE THREAD

**Issue by vaguila95** [IIC2133-PUC/2019-1#33]
Hola! 

Por alguna razón ahora no puedo compilar mi tarea, me arroja el siguiente error

`src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found`

Qué puede estar fallando?

**Comment by alopez7** [comment]
Te diría que es que no tienes instalado gtk pero no parece ser eso. Puedes probar escribir make clean y luego make denuevo.

**Comment by vaguila95** [comment]
Fue lo primero que intenté, pero me arroja el mismo error. Finalmente calculé los tiempos para el informe usando el computador de un compañero con mi repositorio.
De todas maneras ¿qué me recomiendas para solucionar esto?

**Comment by alopez7** [comment]
Con tan poca información no tebpuedo ayudar. Tendría que ser en persona. Puede ser después del taller del viernes.
