### ISSUE TITLE
Árbol AVL balance/desbalance

### ISSUE THREAD

**Issue by nmaturana97** [IIC2133-PUC/2019-1#34]
Tenía una duda que me surgió al revisar ejercicios pasados.

Cuando se dice que un árbol es AVL (sin decir nada más), se refiere a un árbol que esta balanceado (1 altura de diferencia máxima entre hijos del mismo nodo), o puede ser que se encuentre desbalanceado?
En otras palabras, si a un árbol AVL se le hace una incersión que lo desbalancea:
¿sigue siendo AVL, pero ahora desbalanceado? 
¿pierde su propiedad de ser árbol AVL hasta que se rebalancea?

Gracias de antemano

**Comment by vichoeq** [comment]
Hola,

Podrías decirlo así, pero seamos formales:

Por definición, el árbol AVL está "balanceado" según el criterio de AVL, es decir, la diferencia de altura entre el sub-árbol izquierdo y el sub-árbol derecho es como máximo 1.

Al insertar un nuevo árbol AVL es posible que violemos esta propiedad, y por eso es necesario reajustarlo, pero no nos interesa si el árbol está balanceado _mientras_ insertemos, solo que esté balanceado al terminar la inserción.

**Comment by nmaturana97** [comment]
Muchas gracias!
