### ISSUE TITLE
[Tarea1][Mac] Problema al hacer make con cairo-pdf.h 

### ISSUE THREAD

**Issue by jerosalazar** [IIC2133-PUC/2019-1#36]
Hola, al correr `make` en la tarea 1 en mi Mac me sale un error con `cairo-pdf.h`
```
src/beholder/drawing/drawing.c:4:10: fatal error: 'cairo-pdf.h' file not found
#include <cairo-pdf.h>
```

Al correrlo en mi maquina virtual de ubuntu no hay problema, así que debe ser de Mac nomás. ¿Tendré que instalar alguna dependencia antes de correrlo?

**Comment by vichoeq** [comment]
Eso se usa para un feature opcional de la interfaz, que es crear una imagen (.pdf) con el contenido de la ventana. Es util para generar imágenes para incluir en tu informe como apoyo para tu analisis. 

Si no lo vas a usar (al menos en mac) puedes ir a `src/beholder/drawing/drawing.c` y comentar ese include y comentar la función `drawing_snapshot` en `drawing.c` y `drawing.h`

**Comment by vichoeq** [comment]
De hecho ahi me equivoqué porque de todos modos la estoy guardando como PNG. (los riesgos de reciclar código :cry: )

Reemplaza la linea 156,

```
  surface = cairo_pdf_surface_create (filename, width, height);
```

por

```
surface = cairo_image_surface_create(CAIRO_FORMAT_RGB24, width, height); 
```

**Comment by vichoeq** [comment]
(Y comenta el include. Con eso debería bastar)

**Comment by santilaguna** [comment]
Hola!
Tuve el mismo problema, intenté comentando sólo eso, luego comentando todo, sacando las carpetas y nada sigo con errores al compilar =(.

**Comment by santiagocruzb** [comment]
Hola! Hice todo lo que @vichoeq mencionó: comentar las líneas, reemplazarlas, etc y nada.
Borré las carpetas `watcher` y `beholder` : creo que son solo para animaciones e interfaz gráfica. 
Después en el `Makefile` la línea 55 la cambié por `PROGRAMS=classifier`  y comenté la 52 que decía `COMMON=watcher`. Eso me funciona.

Esto es válido?

**Comment by alopez7** [comment]
No hay ningun problema con lo que cambiaste, pero no podrás usar la interfaz

**Comment by Jj1martinez** [comment]
Hola, tengo el mismo problema, entiendo que comentando la línea dejaría de funcionar la interfaz. Pero es posible arreglarlo para que funcione?
Lo otro raro  es que estoy usando Ubuntu 18.04 en un mac, por lo que debería estar funcionando.

**Comment by smargozzini** [comment]
hola, hay alguna solución para poder correrlo en mac y poder usar la interfaz? no me funciona comentando lo que mencionaron arriba.
gracias
