### ISSUE TITLE
Parámetros kd_init

### ISSUE THREAD

**Issue by fgbruna** [IIC2133-PUC/2019-1#37]
Es posible agregar un parámetro de eje para que, al construir el árbol, cada hijo sepa que eje debe particionar?

**Comment by alopez7** [comment]
Lamentablemente no puedes cambiar los parámetro pero ¿es necesaria esa información? Solo necesitas los vectores para costruir el kdtree

**Comment by fgbruna** [comment]
Osea, hasta donde he entendido viendo algunas implementaciones de kd-trees en internet todas usan un parámetro de eje o bien un parámetro de profundidad.Esto por el hecho de ir alternando los ejes a particionar.
Ahora bien, puedo crear otra función para crearlo y esa usarla dentro de kd_init partiendo con un eje arbitrario.
Igual me surge la duda de si lo estoy entendiendo bien o por alguna razón que no veo esta info no es necesaria.
Gracias de antemano!

**Comment by alopez7** [comment]
Supongo que puede ser útil pasar ese dato si quieres alternar los ejes, pero alternar no es necesariamente la mejor manera

**Comment by Cschavez** [comment]
Hola! y tampoco se pueden cambiar los parámetros de KNN? solo quiero entregarle las esquinas del plano rectangular, para que no lo tenga que calcular para cada vector _objective_ (para ver si hay colisiones).

**Comment by alopez7** [comment]
Podrías almacenarlas en el kdtree tal vez. No se pueden modificar los parametros
