### ISSUE TITLE
Citar Código 

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#38]
Hola!

En mi investigación acerca de kd-trees encontré un paper que explicaba la creación en tiempo lineal de estos y su implementación. De la implementación me interesa utilizar dos funciones para facilitar ciertas cosas. 

Podría utilizarlas, adaptarlas a mi programa y citarlas debidamente?

Gracias!

**Comment by alopez7** [comment]
Si puedes utilizarlas. Cita el paper en el informe
