### ISSUE TITLE
Clases

### ISSUE THREAD

**Issue by Cschavez** [IIC2133-PUC/2019-1#39]
Hola! 
Podrían actualizar las clases por favoor ? 

Muchas gracias!

**Comment by alopez7** [comment]
Hola, estoy esperando a que me las mande para subirlas.

**Comment by Cschavez** [comment]
Gracias!
Una duda, las clases que vimos de heap no se subirán o es porque aun no las tienen?

Muchas gracias de nuevo! :)

**Comment by vichoeq** [comment]
Aun no las teniamos. Ahi las subí.
