### ISSUE TITLE
Fechas de Ies y controles

### ISSUE THREAD

**Issue by ajahr95** [IIC2133-PUC/2019-1#4]
Hola, lei en otra issue que aun no tienen las fechas de las tareas, pero podrían dar las fechas exactas de las ies, examen y controles?. Gracias

**Comment by alopez7** [comment]
Hola, 
no hay interrogaciones este semestre. El primer control sería el miércoles 20 y el resto de los controles son cada 4 clases contando desde el control anterior (miércoles por medio si no hay feriados).

El examen lo confirmo cuando sepa.

**Comment by alopez7** [comment]
Acabo de subir al repo la clase 1 y actualicé la clase 0. Ahora la clase 0 tiene las fechas de los controles y el examen en la diapo de evaluaciones escritas.

Saludos
