### ISSUE TITLE
[Tarea 1] Duda respecto a cajas y mediana

### ISSUE THREAD

**Issue by vbarros2** [IIC2133-PUC/2019-1#40]
Se puede hacer un KDTree que cada nodo sea una coordenada incluyendo las hojas. Es decir todos los nodos del árbol son coordenadas y todas las coordenadas están en un nodo del árbol. 
De esta manera no hay cajas, importa para el desarrollo de la tarea?

Y mi segunda duda es si importa el calculo de la mediana, es decir, no todos vamos a tener las mismas medianas porque algunos van a tomar la mayor cuando es impar o la menor, también se puede hacer primero vertical y luego horizontal. La duda es si todos tenemos que tener las mismas divisiones en el KDTree o esto no afecta.

Muchas Gracias

**Comment by vichoeq** [comment]
Hola, veamos:

0. Como estructura de datos, el KDTree puede servir para muchas cosas. En nuestro caso, queremos encontrar los _k_ vecinos más cercanos.
1. La idea aquí del KDTree es poder ir descartando sub-árboles que sabes que no contienen la solucion. Para esto necesitas comparar la solucion parcial que tienes con el subarbol a descartar / revisar. Para eso **necesitas** la caja, a menos de que quieras revisar el subarbol entero para saber si lo descartas.
2. Formalmente, la mediana cuando el set de datos es par se define como el promedio entre los dos elementos de al medio. Hacer esto te permite tener mejores cajas, más ajustadas. 
3. El eje divisor y la mediana en este caso solo afectan el rendimiento de la estructura, pero la respuesta deberia ser siempre la misma.

**Comment by vichoeq** [comment]
Si para el punto 1 tienes otro método de descarte me encantaría oirlo.

**Comment by vichoeq** [comment]
En nuestro caso usamos cajas **recangulares y alineadas con los ejes** pq nos permiten decidir el eje divisor con facilidad, y pq se construyen facilmente a partir de los datos.

Es posible usar **esferas**, lo que hace que la revision de colision entre el radio de la solucion y la caja del subarbol sea muy facil y rápida, pero las cajas tienden a tener demasiado espacio vacío.

Es posible usar **elipses**, lo cual entrega cajas bastante compactas, pero la matemática se complica **mucho**. Y no escala muy bien al aumentar el numero de dimensiones.

Es posible usar **rectangulos no alineados a los ejes**, lo cual tambien da cajas compactas, pero tambien se complica mucho la matemática.

En fin, cualquier figura funciona, pero no todas son igual de prácticas.

**Comment by vbarros2** [comment]
Me quedo claro, gracias, algunas otras dudas al respecto
1. Dudas respecto a 1:

-Cual es la primera solución parcial?. 
-Hasta que punto dejo de tener subdivisiones y tengo cajas, es decir las cajas raíces son de 3,4,5, o cuantos vectores?. 

Otras dudas:
-En el enunciado hablan de los k vecinos mas cercanos pero luego en el ejemplo de KNN dicen que se busca una vecindad de tamaño 4 representada por un circulo negro y que dentro de ese circulo hay 4 azules por lo que pasa a ser azul. Los k vecinos mas cercanos se calcula con el radio o se buscan los mas cercanos? En la función dada collision también hay que dar un radio, lo que no entiendo es que es k.

**Comment by vichoeq** [comment]
Dado que el KD-Tree particiona el espacio, al vector _x_ que intentas clasificar le corresponde una hoja según los ejes de división (puedes verlo como la hoja en la que habria quedado ese vector si formara parte del set de training)

La solución parcial son los _k_ vecinos más cercanos **que has visto hasta ahora**. En torno a ellos definimos una esfera de radio _r = distancia del elemento más lejano en la solución parcial_, y debemos seguir revisando los otros subarboles ya que si sus cajas intersectan con esta esfera podrían tener elementos que esten dentro de esta: elementos que quedan aún más cerca.

La primera solución parcial son los _k_ vecinos más cercanos en la hoja que le corresponde a _x_. Si la hoja tiene menos de _k_ elementos entonces esa solución parcial está incompleta por lo que el radio es infinito. (Eso significa que colisiona con todas las cajas), y seguimos buscando recursivamente hacia arriba.

Tu decides cuando dejas de dividir. Prueba como se comporta mejor tu árbol.

Espero que eso tambien haya resuelto tu última duda.

**Comment by mericci** [comment]
Tengo una duda con respecto a esta issue, al investigar sobre los KDTree, cada nodo guardaba una coordenada en la cual se iba comprando con el eje x e y de manera alternada. Bajo esta idea cree mi árbol así como plantea mi compañero en el principio de la issue (agregando más información que solo la coordenada). Lo que entiendo de la respuesta es que en cada nodo debería haber una caja, que al parecer es contario a una coordenada. ¿A que se refieren exactamente cuando hablan de cajas? ¿Los nodos deberían o no guardar la coordenada (según como se espera que se resuelva la tarea)?

**Comment by alopez7** [comment]
Al dividir el espacio con planos paralelos a los ejes, estás definiendo cajas que representan a cada nodo del KDTree. Puedes entenderlo de ambas maneras. Sin embargo, el concepto de las cajas permite hacer la búsqueda de manera más eficiente que solo con los planos. Además, puedes hacer que la caja de cada nodo sea el mínimo espacio que contiene a todos los puntos del sub árbol, lo que achica más las cajas y hace que el algoritmo sea más eficiente.

**Comment by mericci** [comment]
Entonces, ¿la definicion que econtre sobre KDTree no es correcta o hay que complementarla un poco con este tema de las cajas? ¿en ese caso, debería guardar cuatro puntos dentro de cada nodo y no uno solo, cierto? de modo de poder hacer los plano x= x1, x =x2, y=y1, y =y2

**Comment by alopez7** [comment]
La idea es que la caja de un nodo contiene a la caja de sus hijos. Puedes hacer que una caja tenga un solo elemento y tendrías una caja de 0x0, lo que no va a provocar ningun error. La diferencia entre tener nodos solo en las hojas o en las hojas y en los otros nodos es que la búsqueda se modifica un poco. En mi opinión es más fácil hacer la búsqueda guardando los vectores solo en las hojas.

**Comment by mericci** [comment]
Creo que entendí, solo para aclarlo, el nodo raíz sería todo el plano, luego cada nodo hijo sería cada una de las separaciones que se hicieron y asi... cierto? Ya lo tengo hecho con vectores en cada nodo, pero si recomiendan cambiar creo lo haré. Para eso, lo que se debe hacer es guardar 4 puntos que representen el plano. O crees que hay alguna mejor forma de verlo.

De todos modos, teniendo las cajas no entiendo mucho como funciona el método del descarte, ya que puede existir una caja que sea adyacente a otra que esté descartando por estar en otro subarbol, siendo que puede tener a uno de los k vecotres más cercanos

**Comment by alopez7** [comment]
Estás poco en lo correcto:

Cada nodo del árbol tiene su propia caja. Esta caja idealmente tiene las menores dimensiones posibles tal que contiene a los vectores del sub árbol.
Un nodo hoja tiene uno o más vectores almacenados, y un nodo que no es hoja tiene 2 hijos cuyas cajas no se intersectan y están separadas por un plano.
Con respecto al plano, este por simplicidad es paralelo a algun eje, por lo que solo debes almacenar algo que te inque que eje es y el valor del plano. Por ejemplo: eje = 0, value = 3 quiere decir que el plano es x = 3.
Este uso de planos te permite moverte en arbol hacia las hojas segun a qué lado del plano me interesa ir.
Las cajas te permiten descartar nodos del árbol para no tener que revisarlos. La lógica del descarte es: si ya encontré k vectores, de los cuales el mas lejano está a distancia 10, no necesito buscar en las cajas que estén a mas de 10 de distancia.

**Comment by mericci** [comment]
Buenisimo, una ultima pregunta que aún no logro entender, ¿Como está definida la caja? ¿son por los cuatro puntos?¿ o solo necesito ese eje y ese valor para hacer el corte en el plano? (además de conocer mis maximos y minimos para no salir del rango.

Ahora tengo algo definido como vector, pero separo por los valores de x e y dando el eje y el value tal como pusiste en el ejemplo, pero no se si con ese formato basta o hay que definir los 4 puntos entre los cuales está la caja.

**Comment by alopez7** [comment]
Dado que está alineada a los ejes puedes definirla con 2 vectores (punto minimo y maximo). O la posición del centro + ancho y alto.
