### ISSUE TITLE
Modificar data.h y data.c

### ISSUE THREAD

**Issue by Cadagan** [IIC2133-PUC/2019-1#42]
Se pueden modificar los codigos de los archivos data.h y data.c? en especifico para que el struct "data" funcione un poco distinto? o nos tenemos que limitar a solo modificar las funciones kd_init, kn, kd_destroy sumado a cosas que agreguemos al programa?

**Comment by alopez7** [comment]
No puedes modificar la estructura. ¿cual es el cambio que quieres hacer?

**Comment by matiaseche** [comment]
Tengo la misma duda, no quiero modificar la estructura, pero si agregar un método para eliminar un elemento del array de vectores, se puede?

**Comment by Cadagan** [comment]
y podemos hacer que la estructura guarde floats en lugar de doubles para las coordenadas? para facilitar la comparacion de valores :/

**Comment by alopez7** [comment]
Puedes crear ese método en el archivo kdtree. E importar data desde kdtree.

**Comment by Cadagan** [comment]
Es que no he modificado data.c, pero al correr el programa, me arroja segmentation fault en la parte de:
// Leo el numero de vectores
  fscanf(file, "%d", &data -> count);

y pensaba en modificar esa parte hasta que funcione :/

**Comment by alopez7** [comment]
Debes estar dándole mal la referencia del archivo al programa

**Comment by Cadagan** [comment]
Puedo hacer que "colision" me diga true si al hacer el circulo, este se sale de la caja en la que esta? en lugar de revisar si colisiona con una caja externa

**Comment by alopez7** [comment]
Puedes hacer lo que sea con las funciones de kdtree. Yo les di collision para que no tengan que implementarlo ustedes.

**Comment by Cschavez** [comment]
significa que tampoco puedo borrar el "static" de algunas funciones? como la que libera los vectores

**Comment by alopez7** [comment]
La tarea de liberar vectores no debería ser de tu programa. No debes llamar a esa función
