### ISSUE TITLE
uso de static dentro de funciones con operadores atómicos?

### ISSUE THREAD

**Issue by naquiroz** [IIC2133-PUC/2019-1#43]
Hola!

Estuve leyendo y quiero usar una variable estática dentro de una de mis funciones para ir alternando su valor entre llamados. Sin embargo leí en internet que lo anterior no es _thread safe_, por tanto recomendaba restringir su acceso con librerías de operadores atómicos `<stdatomic.h>`, lo que me hizo preguntarme dos cosas:

1. Puedo usar esa librería?
2. Es buena práctica usar `static` dentro de funciones? De no serlo cual podría ser otro _approach_?

**Comment by alopez7** [comment]
No es necesario hacer operaciones thread safe si no usas threads. Si quieres usar cualquier librería es a tu propio riezgo ya que no podemos ayudarte con cualquier problema que tengas con ellas. Puedes usarla.

Con respecto a la variable estática, podrías usar en vez una variable global. Hay una variable global en el programa que puedes usar de ejemplo (N_LABELS)

**Comment by naquiroz** [comment]
Gracias!
