### ISSUE TITLE
[Tarea 1] Precisión de clasificación de los vectores

### ISSUE THREAD

**Issue by rihanuch** [IIC2133-PUC/2019-1#44]
¡Hola!

Estaba probando mi solución del `KDTree` y me surgieron algunas preguntas:

1. La precisión que logra mi código es **mayor**, consistentemente, a la precisión lograda por el método _naive_. En todos los casos que he probado, la precisión es mayor o igual a la que se logra con el método entregado (he probado aproximadamente 50 combinaciones es diferentes con _k_ y _l_ diferentes y en diferentes `datasets`. Mi pregunta es, ¿debería preocuparme de que sea mejor que lo esperado? A pesar de que un KNN debiese dar siempre el mismo % de aciertos, no hay problema en que sea mayor, ¿o no? 🤔 
2. La precisión obtenida por el método _naive_ nuca es de 100%, por lo que mi pregunta es ¿en que % se encontrará el puntaje completo?
3. ¿Podrían darnos un tiempo estimado que se debería demorar el código para un k, l y dataset dados?

¡Muchas gracias y buen fin de semana! 😄

**Comment by vichoeq** [comment]
Hola, 

1 y 2: este curso es de estructuras de datos, no de inteligencia artificial.

Eso significa que lo que a nosotros nos interesa evaluar es el correcto funcionamiento de la estructura de datos, no la precisión del clasificador. El algoritmo de clasificacion es para darles un contexto del uso de  la estructura.

A la hora de corregir tu tarea se llamará a la función de tu KDTree para encontrar los vecinos más cercanos y se evaluará cuantos de ellos estan efectivamente dentro de los _k_ mas cercanos. No habrá clasificador. 

3. @alopez7 te puede ayudar con esto.

Saludos!

**Comment by rihanuch** [comment]
¡Gracias!

**Comment by alopez7** [comment]
Hola, voy a publicar una herramienta para revisar su código y junto con eso publicaré los tiempos de la pauta
