### ISSUE TITLE
Precorrección T1

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-1#45]
Hola, tal como se hizo para la tarea 0, les voy a dar un método para revisar que su tarea funciona correctamente antes de mandar el resultado final.

Primero deben descargar el siguiente zip:
[Precorreccion.zip](https://github.com/IIC2133-PUC/2019-1/files/3100827/Precorreccion.zip)

En el se encuentran 3 archivos:
* `solution.txt`: Tiene la solución de la pauta
* `comparer.py`: Compara el output del alumno con la pauta e imprime el porcentaje de éxito (100% = 7).
* `main.c`: Es el archivo main que se usará para corregir sus tareas. Se usa de la misma manera que el original pero en vez de calcular el porcentaje de vectores clarificados, imprime las distancias de los vecinos más cercanos al momento de consultarlos. De esta manera se puede comparar su solución con la pauta.

Para probar que su tarea funciona bien deben hacer los siguientes pasos:
1. Eliminar todo _printf_ de su programa para no interferir con el corrector.
1. Remplazar el archivo `main.c` original por el nuevo.
2. Volver a compilar.
3. Ejecutar el programa con el comando `./classifier numbers_train.txt numbers_test.txt 50 10 > out.txt`. Esto guardará el output de su programa en el archivo `out.txt`.
4. Poner los archivos `solution.txt`, `out.txt` y `comparer.py` en la misma carpeta. Es importante que los archivos tengan esos nombres.
5. Ejecutar `comparer.py`.

Si todo está bien, `comparer.py` debería imprimir 100%. Si imprime un porcentaje menor es porque su solución tiene algunos vecinos incorrectos.

Se espera que su programa corra en menos de 10 segundos con esos parámetros, por lo que si su programa funciona en más de 10 segundos solo se les dará puntaje por lo que se alcanzó a imprimir.

Cualquier duda o problema con la precorrección me la pueden hacer acá.

**Comment by santiagocruzb** [comment]
Hola! Dónde está el archivo `numbers_train.txt` ????

**Comment by mcorreaiz** [comment]
Hola, que pasa si mi programa demora mas de 10 segundos en inicializar el KD Tree pero menos de 10 en ejecutar KNN?

**Comment by mcorreaiz** [comment]
Y otra pregunta, hay algun problema si cambiamos las signatures de las funciones kd_init y knn? Digo porque tuve que editar el archivo main.c.

**Comment by alopez7** [comment]
Hola, si tu programa se demora más de 10 segundos en solo crear el kdtree tienes algún problema en tu código o en tu algoritmo que lo crea. 
No puedes cambiar los signatures de las funciones que se usan en el main.

**Comment by rihanuch** [comment]
¡Hola!

Se va a corregir corriendo el comando
```sh
./classifier numbers/numbers_train.txt numbers/numbers_test.txt 50 10 > output.txt
```

o con el comando 
```sh
valgrind ./classifier numbers/numbers_train.txt numbers/numbers_test.txt 50 10 > output.txt
```

Esta pregunta surge porque la diferencia de tiempo entre ambos comandos es sustancial (por ejemplo en mi caso paso de demorarme 0,463s a demorarme 14,439s)

¡Saludos!

**Comment by alopez7** [comment]
Hola, se ejecutará sin valgrind para testear la eficiencia de tu programa con el test grande. Luego, las tareas con más de un 4 se ejecutarán con el test chico usando valgrind para ver que no tengan leaks o errores

**Comment by Jiparavich** [comment]
Hola!
Tengo una duda respecto a la precisión esperada (100%), si se supone que el metodo "naive" ,que revisa vector por vector, llega a 0.92%, entonces estas es nuestra cota máxima? o el 100% igual?

Slds

**Comment by Cschavez** [comment]
Hola! Creo que tengo una duda que tiene que ver con la anterior. Para encontrar los 50 vecinos más cercanos probé revisando todas las hojas del árbol. Resulta que tengo aprox 80% bueno, lo que me parece peculiar es que comparé a mano las respuestas de solucion.txt con algunas de out.txt y mi solución difiere de la pauta pero por vecinos que están MÁS cerca. Qué posibilidad hay de que solucion.txt no tenga total precisión ? (pensando en que la distancia la estoy calculando con la distancia que ustedes dan  y estoy revisando todas las hojas)

**Comment by alopez7** [comment]
Ojo que el porcentaje del precorrector es el porcentaje de respuestas correctas de tu porgrama, no porcentaje de labels bien puestos. Saludos.

**Comment by Dunkan1** [comment]
Siento que el comparer.py es muy "estricto" es decir que si las soluciones quedan desfasadas por 1 valor, el porcentaje que arroja es muy bajo a pesar que los vectores esten ahi.

por ejemplo en mi tarea cambie esto
```
def compare(line1, line2):
	line1.sort()
	line2.sort()
	
	for i in range(len(line1)):
		if line1[i] != line2[i]:
			return False
	return True
```
por esto
```
def compare(line1, line2):
    for i in range(len(line1)):
        if line1[i] in line2:
            return True
    return False
```

y mi porcentaje subio de 0.1% a 99.72% porque seguramente las soluciones quedaban desfasadas y eso hacia que no pudiera hacer el 1-1

**Comment by mcorreaiz** [comment]
Dijeron que hoy no van a responder dudas, pero para que te guies ahi solo estas revisando que tengas 1 vector (de los 50) correcto con tu algoritmo. Supongo que la idea es tener los 50 vecinos correctos, y eso es lo que corrige el comparer.py original, de tener un vecino malo ya esta mal el algoritmo

**Comment by Dunkan1** [comment]
tienes razon mi codigo esta mal, pero igual tener un desfase no deberia implicar que la linea entera esta mala

**Comment by alopez7** [comment]
Tu corrector tiene corazón de abuelita

**Comment by Vanana** [comment]
Tengo una duda de que es lo que se evaluará, porque a medida que agrando mi radio de colisión con las cajas, aumenta la precisión.
Por lo tanto, me gustaría saber que debo elegir si tener el 100% (en menos de 10 segundos, aprox 3 segundos) o arriba de 95%  pero con mejor tiempo (aprox 1 segundo).

gracias!!

**Comment by Cschavez** [comment]
Hola! no me quedo claro algo, el método implementado en el código base en knn da las distancias más cercas correctas? como para probarlo como pauta con iris_train.txt ?
Muchas gracias!

**Comment by alopez7** [comment]
Si, es correcto

**Comment by jmwielandt** [comment]
Sé que es muy cerca de "24 horas antes de la corrección", pero estoy teniendo un problema con esto.

Por algún motivo las distancias a los vecinos más cercanos que encuentro son mucho menores a las de la pauta. Al menos eso parece, no sé si tengo mal los archivos a usar o qué pasa exactamente pero tengo `0.0%` y me preocupa...

Probé imprimir los vecinos del primer elemento del test y los 20 vecinos más cercanos que encuentro se ven bastante bien :$

Captura de la comparación...
![image](https://user-images.githubusercontent.com/37153467/56781423-20486b00-67b1-11e9-9313-603b2b0c7827.png)

**Comment by timellado** [comment]
Me pasaba lo mismo!
Al final descubrí que guardaba la misma distancia varias veces. Si te fijas, en el archivo solutions.txt no se repiten distancias por knn hecho. Trata de buscar por ahí!
Saludos

**Comment by Jj1martinez** [comment]
No hay posibilidad de extender esos 10 segundos?

**Comment by alopez7** [comment]
No, pero si tu programa no termina en 10 segundos, se corregirá lo que alcanzó a imprimir

**Comment by jmwielandt** [comment]
@timellado al final lo conseguí, gracias igual
era eso, entraba como 5 veces a cada caja, o más XD

(empecé a escribir esto hace como 3 horas y se me olvidó enviarlo XD)
