### ISSUE TITLE
Problemas con data_init

### ISSUE THREAD

**Issue by Cschavez** [IIC2133-PUC/2019-1#46]
Hola! Estaba intentando precorregir mi tarea usando ./classifier numbers_train.txt numbers_test.txt 50 10 > out.txt como sugirieron. Sin embargo, aunque corre bien para iris_test.txt, en esta ocasión mi computador se queda pegado, pensé que claramente podía ser un error de mi programa pero usando valgrind me dio que tenía problemas al ingresar a data_init (no pude sacarlo pantallazo y ya no me sale eso). Finalmente puse prints para ver cuando saliera de la función data_init y  al parecer nunca sale de ahí _( y por eso el programa no termina de correr :(  Todas mis implementaciones vienen apenas se llama a kd_init por eso sé que el problema no está en ellas. 
Lo corrí en otro computador porque imaginé que podía ser por memoria o algo así (? y pasó lo mismo :(
No sé si pueden tener alguna idea de lo que es.
Agradecería mucho su ayuda!

**Comment by alopez7** [comment]
Shame
