### ISSUE TITLE
[Tarea 1] numbers_train.txt numbers_test.txt

### ISSUE THREAD

**Issue by jnpoblete** [IIC2133-PUC/2019-1#48]
Hola, me surgió una duda con estos dos archivos. Ya tengo parte del árbol implementado y quisiera testearlo. El problema es que no entiendo si estos archivos .txt los debo crear o ustedes los entregan al igual como se hizo en la tarea 0. No sé si estoy muy perdido quizás con la duda. Saludos!

**Comment by alopez7** [comment]
Estos archivos son datos sobre los cuales ee aplica tu algoritmo. Yo les di esos archivos y están en el SIDING. Para la corrección usaré otros archivos pero de similar tamaño.

**Comment by jnpoblete** [comment]
Gracias, no se me habia ocurrido revisar el siding porque pense que no se usaria para este curso como plataforma, pense que era solo con github. Saludos!
