### ISSUE TITLE
[Tarea 1] Extraño problema en C

### ISSUE THREAD

**Issue by vicentecastroa** [IIC2133-PUC/2019-1#49]
Hola. Estoy haciendo la tarea y me veo enfrentado a un problema que no me hace ningún sentido. El programa me funciona bien mientras voy imprimiendo unas cosas, pero si comento o remuevo unos prints, me tira "violación de segmento". Qué podría ser? No se me ocurre por donde enfrentarlo.

![image](https://user-images.githubusercontent.com/13738469/56583272-2e2aa000-65a7-11e9-8b4d-b4f0d487175e.png)

![image](https://user-images.githubusercontent.com/13738469/56583354-616d2f00-65a7-11e9-826a-01ae6778130a.png)

**Comment by alopez7** [comment]
Tienes un error de memoria. A veces se cae el programa y otras veces no pero el error está aunque no se caiga. Usa valgrind para encontrar el error.

**Comment by vicentecastroa** [comment]
Vale gracias!
