### ISSUE TITLE
Gitignore compilados para linux

### ISSUE THREAD

**Issue by jmwielandt** [IIC2133-PUC/2019-1#5]
Hola,
Si quisiera hacer un archivo .gitignore para un repo donde compilo cosas escritas en C para windows, tendría que agregar el directorio donde se guardan los archivos .o y también todos los .exe, sin embargo, en linux los ejecutables no tienen extensión.
¿Cómo lo hago?

Gracias :D 

PD: la mejor solución que he encontrado en google es meter los nombres directamente en el .gitignore, pero me da la sensación de que es muy poco mantenible :/

**Comment by alopez7** [comment]
Con la makefile que te damos la mayoría de los compilados están en la carpeta obj. Además de estos se crea un archivo ejecutable sin extensión.
Puedes ignorar la carpeta obj pero solo puedes ignorar el ejecutable por su nombre

**Comment by vichoeq** [comment]
Para cerrar el tema: en los repositorios de las tareas va incluido un `.gitignore` que les debería servir.
