### ISSUE TITLE
Metodo collision

### ISSUE THREAD

**Issue by Dyoma3** [IIC2133-PUC/2019-1#50]
En el metodo collision, para calcular el centro, se encuentra el siguiente codigo:
// Calculo centro de la caja
  double bx = (Mx + mx) < 2;
  double by = (My + my) < 2;

No deberia ser / en vez de < ?

**Comment by alopez7** [comment]
Hola, el código original tiene el método collision mal. Hice un aviso un par de días después de la publicación de la tarea. Te recomiendo ver el estado nuevo de Base-T1-2019-1 y copiar le método nuevo.
