### ISSUE TITLE
Nuevo plazo T1

### ISSUE THREAD

**Issue by mcorreaiz** [IIC2133-PUC/2019-1#52]
@alopez7 podrías explicar por qué se decidió aplazar la tarea 1? Y hacer pública la decisión el mismo día de la entrega?

Saludos

**Comment by Dyoma3** [comment]
algun bonus a los que la terminaron hoy?

**Comment by alopez7** [comment]
Hola, el nuevo plazo se dio hoy porque hoy vi un issue en el que se pide más plazo. El objetovo de la extensión es para que todos puedan entregar la tarea y aprendan.
Ya hay suficientes bonus y beneficios para los alumnos responsables como para agregar otro para esta tarea.

**Comment by mcorreaiz** [comment]
Me parece bien el objetivo, pero no la medida tomada. De hecho me parece un fomento a la irresponsabilidad e injusta con quienes nos planificamos con tiempo, ya que ni siquiera vamos a tener un premio porque ya hay "suficientes". De haber sabido antes, avanzaba en la otra entrega que tengo para hoy.

**Comment by baarratia** [comment]
Me parece bastante egoísta tu postura, en mi caso personal, también me planifiqué con tiempo y me he esforzado harto por tenerla lista para hoy, y estoy casi, pero igual está enredada y la carga de ramos es dura para todos. Cada uno ve como maneja sus tiempos y se agradece si notan que el curso está complicado, tal vez no de flojos, si no que tal vez porque simplemente no han podido avanzar por distintos factores (Como adaptarse a programar en C). Es muy valorable que tomen en consideración al curso y que nos den de alguna forma un pequeño respiro para no recibir cosas implementadas a la rápida y poder entregar tareas decentes. #Care #ProudDecano

**Comment by mcorreaiz** [comment]
Gracias por tu comentario y concuerdo en que es valorable que tomen en consideración la sanidad de sus alumnos. Dejo en claro que no me opongo a la medida si no que quise saber la motivación detrás de esto y comentar que me sentí afectado en la forma en que se hicieron las cosas.
Pero es verdad, todos tienen sus situaciones .
