### ISSUE TITLE
Hay actividad mañana?

### ISSUE THREAD

**Issue by vicentecastroa** [IIC2133-PUC/2019-1#53]
Saludos!

**Comment by alopez7** [comment]
Si, la actividad de mañana es de hashing y es de mucha utilidad para la tarea 2. Si no pueden ir no es problema porque subiremos un power point y el código bien comentado.

**Comment by dedarritchon** [comment]
> Si, la actividad de mañana es de hashing y es de mucha utilidad para la tarea 2. Si no pueden ir no es problema porque subiremos un power point y el código bien comentado.

La actividad que hay que subir al siding vale solo para los que asistieron al taller? o no era obligatorio asistir? gracias

**Comment by alopez7** [comment]
Cualquiera puede subirlo ya que no se pasó asistencia en una sala
