### ISSUE TITLE
T1 - Informe - ¿solo esas variables?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2133-PUC/2019-1#54]
Hola
Haciendo pruebas me dí cuenta de que es muy relevante la cantidad de puntos por caja a la hora de medir el tiempo de ejecución, pudiendo pasar de menos de un segundo a más de un minuto, solo modificando ese valor.
¿Podemos añadirlo a la expresión del cálculo de la complejidad? ¿Debemos/podemos asumir un valor fijo?

Gracias.

**Comment by alopez7** [comment]
Puedes agregarlo pero no es necesario. Puedes asumir que tu programa funciona cpn ese valor fijo.
