### ISSUE TITLE
T1 - Pequeño error en código

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#56]
Hola!

Tengo la siguiente duda, revisando mi código me di cuenta que no arregle una linea de código que crei que había arreglado. Con el test case numbers me daba 100% independiente de ese pequeño error pero con otros es probable que falle. Cómo sería la recorrección en caso de que fuera así?, o se consideraría simplemente malo y con la nota que salga?

Gracias!

**Comment by alopez7** [comment]
En la recorrección podrás arreglar lo que tengas que arreglar pero se aplica descuento según lo que se cambie

**Comment by fdominguezclaro** [comment]
@alopez7 será posible que suban mas información acerca de la recorrección? 

Tengo un error pequeño (aún no se cuál) pero hace que mi programa demore mucho... Me gustaría saber desde ya para ponerme a buscar el error y no esperar a que entreguen las notas 

Saludos!

**Comment by alopez7** [comment]
Pucha, tendrás que esperar a que tenga el corrector listo para encontrar el problema. Te revomiendo medir el tiempo de las distintas operaciones o contar las llamadas a ciertas funciones importantes de tu programa para encontrar funcionamientos ineficientes

**Comment by fdominguezclaro** [comment]
Parece q me entendiste mal... Me refería a cuales serán los plazos y descuentos asociados al cambio de código, a ver si vale la pena recorregir.

**Comment by alopez7** [comment]
A partir del momento en que se publican las notas del código se da una semana para recorregir. El descuento es de 1% por statement cambiado en tu código. Un statement puede ser una asignación, una llamada a una función, una operación matemática, etc...
