### ISSUE TITLE
Multiples Repositorios T01

### ISSUE THREAD

**Issue by yerkko** [IIC2133-PUC/2019-1#57]
Al empezar la tarea se me crearon varios repositorios, siempre hice los commits al último más reciente (nunca acepté la invitación más de una vez).

Ahora veo otra Issue (#7 ) con respecto al mismo problema y que se debían hacer al primero. Existe alguna forma de hacer que se revise al que hice los commits? 😰

**Comment by alopez7** [comment]
Ok, se revisará tu código
