### ISSUE TITLE
Error en creación de repositorio de tarea 2

### ISSUE THREAD

**Issue by rihanuch** [IIC2133-PUC/2019-1#59]
Hola!

Al tratar de crearme el repo para la tarea me aparece lo siguiente

<img width="1067" alt="Captura de pantalla 2019-05-03 a la(s) 08 15 41" src="https://user-images.githubusercontent.com/26392931/57136728-b8c78800-6d7b-11e9-8355-4855740f0060.png">

Saludos!

**Comment by smargozzini** [comment]
a mi me pasa lo mismo, desde ayer en la noche

**Comment by savelozo** [comment]
+1

**Comment by alopez7** [comment]
Solucionado

**Comment by ranieto** [comment]
@alopez7 el link nuevo del anuncio es el mismo link viejo.

**Comment by fdominguezclaro** [comment]
@ranieto a mi si me funcionó, revisa bien

**Comment by ranieto** [comment]
Me había tirado error, pero parece que era mi navegador. Lo hice en otro y funcionó 😅
