### ISSUE TITLE
Tarea 0, Invalid read of size 4

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#6]
Hola!

Al compilar y probar el código base de la tarea me sale el error `invalid read of size 4` al momento de hacer `fscan` del largo y el ancho del tablero. Intente usar `malloc` pero el error persistió. Alguna idea de que pueda estar pasando?

Saludos!

**Comment by alopez7** [comment]
Hola
¿El invalid read te sale al ejecutarlo con valgrind?
¿En qué sistema operativo estás trabajando?
¿Compilaste el programa haciendo make?
Mándame un screenshot del invalid read con todo el mensaje.

**Comment by vichoeq** [comment]
¿Con que parámetros estas llamando a tu programa?

**Comment by KnowYourselves** [comment]
Estaba ingresando mal los argumentos de `./simulate`.

Gracias por la preocupación!, salu2
