### ISSUE TITLE
T2 - Uso de random en Zobrist

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#60]
Hola!

Mis dudas son dos:

1. En la solución del taller 4 se encuentra la siguiente línea de código:
```c
board.randoms[i][j] = (uint64_t) rand() * pow(2,32) + (uint64_t) rand();
```
No entiendo la lógica, por qué múltiplicamos un número aleatorio por 2 elevado a 32 y luego le sumamos otro número aleatorio?

2. En _Zobrist Hash_ la idea es guardar números aleatorios, pero al momento de hacer `xor` deberíamos trabajar en binario, sin embargo el código mostrado en 1 retorna un número en base 10 y el hash de la serpiente también se maneja en base 10. El operador _bitwise_ `^` funciona correctamente al usar décimales en vez de binarios?

Gracias!

**Comment by alopez7** [comment]
Lo que pasa es que el número añeatorio dado por rand() es solo de 32 bits entonces esa función concatena 2 números aleatorios.

En el código de la tarea está esa misma función implementada pero con pcg (da mejores números random)

**Comment by vichoeq** [comment]
El operador _bitwise_ hace `xor` bit a bit de los dos elementos dados (por eso se llama bitwise). Nosotros lo unico que hacemos es interpretar el resultado de esa operacion como un número en base 10, pero recuerda que en memoria todo está guardado en binario.

**Comment by KnowYourselves** [comment]
Gracias!
