### ISSUE TITLE
T2 - Tamaño 'razonable' de una tabla de hash

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#61]
Hola!

Estuve investigando acerca de los tamaños recomendados de las tablas de hash y casi todas las fuentes dicen lo mismo; apróximadamente 1.2 o 1.3 veces el tamaño máximo de elementos que esperas guardar. Sin embargo no encontré información respecto al límite **práctico** de este tamaño. 

1000 elementos?, 100K? 100M?, En qué momento una tabla de hash pasaría a ser "demasiado" grande?

Gracias!

**Comment by alopez7** [comment]
Lo que recomiendo es hacer una tabla de tamaño dinámico. La duplicas cuando se llena hasta cierto porcentaje.

**Comment by KnowYourselves** [comment]
Sii, voy a aplicar todo ese tema, pero mi pregunta va a que no se puede duplicar infinitamente el tamaño, hay un límite razonable o el límite es cuanta RAM tengas?

**Comment by alopez7** [comment]
Dudo que se pueda explorar mas de 10.000.000 en menos de 10 segundos
