### ISSUE TITLE
T2 - Frutitas y expansión de serpiente

### ISSUE THREAD

**Issue by diegoheg** [IIC2133-PUC/2019-1#62]
En el enunciado, en la sección de input, en ningún momento se mencionan las frutas que hacen crecer al snek, sin embargo, poseemos una función para expandir al pájaro, mi duda es ¿Dónde usamos esa función?¿Con qué número están representadas las frutas que hacen crecer el snek?¿Hay alguna otra forma de hacer crecer el snek?

**Comment by alopez7** [comment]
Hola, esa función se usa al crear la serpiente y no es necesario que la usen para nada
