### ISSUE TITLE
T2 - Error al hacer make

### ISSUE THREAD

**Issue by Tyrell-Wellick** [IIC2133-PUC/2019-1#63]
Hola, tengo el siguiente error al hacer make:

/usr/bin/ld: obj/beholder/drawing/drawing.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile con -fPIC

Mi SO: Ubuntu 18.04.2 LTS, arcquitectura x86-64.

Saludos

**Comment by KnowYourselves** [comment]
Hola!

No soy ayudante pero me salió el mismo error.

Cambiar la linea 29 del make por esto: 
![image](https://user-images.githubusercontent.com/26102039/57401550-e65d6880-71a3-11e9-90f5-cbe670aade4f.png)

Solucionó mi error (eso es lo que te pide el error, agregar el flag -fPIC), despues de haber hecho eso, saque el flag y no me volvió a salir el error.

**Comment by firulais33** [comment]
Eso es la linea 29 de que archivo? En el que tengo no haría mucho sentido cambiarla a eso ya que es una asignación...
