### ISSUE TITLE
Error al intentar usar board_move

### ISSUE THREAD

**Issue by Dunkan1** [IIC2133-PUC/2019-1#65]
Hola, estaba escribiendo el BFS, pero cuando intentaba usar board_move para generar la nueva serpiente me topo con el siguiente error:
![Screenshot from 2019-05-09 15-22-58](https://user-images.githubusercontent.com/26102365/57481108-5d136800-726f-11e9-9502-481aa234950d.png)
![Screenshot from 2019-05-09 15-23-11](https://user-images.githubusercontent.com/26102365/57481112-5edd2b80-726f-11e9-8abb-1668697840d9.png)
con board el que se crea en el main

**Comment by alopez7** [comment]
Pruba pasando un Dir en vez de un int. Puedes iterar por los dirs también.
For (Dir i = UP: i < HEAD; i++)

**Comment by alopez7** [comment]
También córrelo con valgrind para tener más información

**Comment by Dunkan1** [comment]
con valgrind no se cae

**Comment by vichoeq** [comment]
Y valgrind dice que no tienes errores de memoria?

**Comment by Dunkan1** [comment]
![Screenshot from 2019-05-09 18-58-25](https://user-images.githubusercontent.com/26102365/57491852-8393cc00-728c-11e9-88a4-40a546eeb455.png)

**Comment by Dunkan1** [comment]
ya cache usaba malloc equivocadamente, gracias
