### ISSUE TITLE
Uso de libreria search.h para impementar tabla de hash T2

### ISSUE THREAD

**Issue by timellado** [IIC2133-PUC/2019-1#66]
Hola!
Quería saber si se puede ocupar una libraría de tablas de hash para la implementación del BFS, o si es parte de la tarea crear una.
Referencia [http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/search.h.html](url).

Gracias :+1:

**Comment by vichoeq** [comment]
Es parte de la tarea implementar la tabla de hash.

**Comment by timellado** [comment]
Gracias!
