### ISSUE TITLE
T2 - cosa loca con makefile + preprocesador

### ISSUE THREAD

**Issue by jmwielandt** [IIC2133-PUC/2019-1#67]
Hola!
Estoy intentando implementar distintos modos de compilación, para facilitar el debugueo futuro, en concreto lo que quiero es:
```make```
Para el programa normal, que resuelva el problema.

```make user_mode```
o alternativamente
```make USERMODE=1```
para que defina una variable del preprocesador y en vez de ser el programa normal, sea la demo y poder yo testear si la solución encontrada es o no correcta. (esto se puede con un bloque
```
#ifdef USER_MODE
-code-
#else  
-code-
#endif  
```

Sé que se puede, pero no el cómo hacerlo y no encuentro algo que me sirva :(  

Gracias :D

**Comment by vichoeq** [comment]
Bueno, una búsqueda rapida en google explica como definir macros para lo que quieres

http://lampwww.epfl.ch/~fsalvi/docs/gcc/www.network-theory.co.uk/docs/gccintro/gccintro_32.html

Pero por como funcionan las reglas make, no es sencillo agregar eso sin tener que duplicar todo el código de la Makefile (el cual de por si ya es muy flexible)

**Comment by jmwielandt** [comment]
Hola, 
Lo de las macros en sí ya lo tengo, mi pregunta iba más por la parte de conectar los parámetros que le paso al make con las macros :(

**Comment by vichoeq** [comment]
Bueno, no quería ahondar en esto ya que escapa por completo al contenido del curso, pero ya que insistes:

[Disclaimer para los demás alumnos: No es necesario ni se espera que entiendan como funciona `make` con la Makefile. Me atrevería a decir que es tremendamente complicado y no me interesa explicarla 100%]

Lo que necesitas es crear una regla adicional, como `all` y `clean` (todo lo que está bajo all que no está indentado es una regla). Cuando dices `make clean` se llama a la regla `clean` y cuando dices `make` se llama a la primera regla que aparece en el archivo (en este caso `all`)

El formato de las reglas es:

```Makefile
regla: requisito1 requisito2 [...]
    comando
```

(`make` es _tab-sensitive_ así que ten precaución si vas a modificar algo en la Makefile)

Al llamar `make regla` se ejecuta el comando de la regla, pero primero se revisan los requisitos:

- Si `requisito` es el nombre de un archivo, revisa que haya sido modificado desde la última vez que se ejecutó esta regla. (esto es lo que se ocupa para recompilar sólo los archivos que cambiaron)
- Si `requisito` es el nombre de una regla, entonces llama a esa regla.

Las reglas pueden tener más de un nombre, como la regla `$(PROGRAMS)` que se ejecuta tanto al llamar la regla `solver` como al llamar la regla `beholder` `(PROGRAMS=beholder solver)`. Los comentarios de las reglas explican en detalle cuales son los requisitos de cada una.

Los parámetros que pueden verse extraños como `$@`, `$<` etc hacen referencia al lado izquierdo, primer parametro, lado derecho de la regla, etc. No recuerdo bien cual es cual, pero está todo en la documentación de `make`.

Básicamente lo que quieres es agregar tu flag al comando de compilación que está dentro de la regla `$(PROGRAMS)` y de la regla `obj/%.o`cuando estas se llamen desde la regla `user_mode`. No soy un experto de Makefile, pero me atrevería a decir que no se puede sin tener que duplicar cada regla por cada parámetro que quieras agregar, asi que no se si te sirva.

Lo siento.

Saludos,
Vicho
