### ISSUE TITLE
Asistencia Taller

### ISSUE THREAD

**Issue by Okhan97** [IIC2133-PUC/2019-1#68]
Hola,

Estaba revisando las asistencias a los talleres y noté que tengo una puesta como "no firma" el 04 de Abril, probablemente fue un error mio pero yo se que fuí a esa ayudantia, ¿hay algo que pueda hacer para tener esa ayudantia?

**Comment by alopez7** [comment]
La verdad no hay nada que hacer. Si te doy la asistencia se abre la opción para no ir a los talleres y hacer las actividades y es algo que no queremos como ayudantes

**Comment by Okhan97** [comment]
Se que esas son las reglas del curso, pero por eso mismo abrí la issue, pues te estoy diciendo que si fui a esa ayudantia solamente que se me fue firmar la lista, compañeros mios pueden dar fe de ello si es que no confias en mi (pero enserio que fui, he ido a todas desde que supe que la asistencia era obligatoria, por algo abrí la issue)

**Comment by alopez7** [comment]
El problema no es que no te crea sino que va contra las reglas del curso. Si yo rompo las reglas del curso para darte la asistencia tendría que seguir esa misma bara y darle la asistencia a todos los que no han firmado y han completado un taller. Si aún crees que deberías tener la asistencia habla con el profesor.
