### ISSUE TITLE
T2 - Plazo entrega

### ISSUE THREAD

**Issue by fguinez** [IIC2133-PUC/2019-1#69]
Hola!

Decidí hacer esta issue para saber si hay posibilidad de aplazar la fecha de entrega de la Tarea 2. La semana pasada estuve complicado de tiempos y esta semana tengo pruebas este miércoles y viernes, además de otra tarea. Por lo que he planificado de mis tiempos y lo que he avanzado de la tarea, estimo que con dificultad la terminaré de aquí al domingo.

Tomando en consideración que lunes y martes no hay clases, ¿hay posibilidad dar más plazo?

No pierdo nada preguntando🤷‍♂️ y de verdad estoy complicado😓
Un saludo

**Comment by JoseRomeroi** [comment]
Me sumo a la petición

**Comment by alopez7** [comment]
Hola, acabo de publicar una política de entregas atrasadas para las tareas

**Comment by santilaguna** [comment]
Hola, respecto a la entrega atrasada la nota se calcula como ¿min(6, nota_real) o max(nota_real - 1, 1)?, suponiendo que se entrega con 2 días de atraso.

**Comment by alopez7** [comment]
Si tu tarea tiene todo el puntaje tienes la nota máxima. Si tiene el mínimo tienes un 1. Es proporcional
