### ISSUE TITLE
Repositorios para T0

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2133-PUC/2019-1#7]
Entre a [este](https://classroom.github.com/a/QfhyVITU) link, y cree mi repositorio para la tarea.
Por alguna razón, ahora tengo 3 repositorios:

- T0-2019-1--MarceloSaldias 
- T0-2019-1--MarceloSaldias-1
- T0-2019-1--MarceloSaldias-2

Asumo que deberia tener solo uno, help

**Comment by HenryBlairG** [comment]
Me pasó lo mismo, yo tengo 4 Repos
* T0-2019-1--HenryBlairG
* T0-2019-1--HenryBlairG-1
* T0-2019-1--HenryBlairG-2
* T0-2019-1--HenryBlairG-3
Yo personalmente pienso usar el primero, pero si me parece bueno que lo revisen para que no haya un malentendido después

**Comment by frvalenzuela** [comment]
También tengo el mismo problema tengo 3 repos:


- T0-2019-1--frvalenzuela
- T0-2019-1--frvalenzuela-1
- T0-2019-1--frvalenzuela-2

Personalmente también ocuparé el primero.

**Comment by alopez7** [comment]
Hola,

Si se meten al link que crea repositorios múltiples veces se van a crear nuevos repositorios. Por favor usen el primero (no tiene número) y eliminen los otros.
