### ISSUE TITLE
T2 - Problema al compilar

### ISSUE THREAD

**Issue by firulais33** [IIC2133-PUC/2019-1#70]
Hola, 

Nose porque al compilar el main me escupe el error: `Undefined symbols for architecture x86_64`, siendo que antes funcionaba perfecto.

**Comment by fguinez** [comment]
Probaste con la solución dada en #63? También tuve un error al compilar (no recuerdo cual eso si) y se solucionó con eso!

**Comment by firulais33** [comment]
Si probé pero no ayudó. Estoy ocupando Mac OS X por si eso dice algo...

**Comment by fguinez** [comment]
Hola, también estoy trabajando en OSX y al parecer me está saliendo el mismo error:
![Captura de pantalla 2019-05-28 a la(s) 10 44 29 PM](https://user-images.githubusercontent.com/26127246/58525585-4f7c3e80-819a-11e9-9724-0e63170f70f3.png)

¿Finalmente pudiste solucionarlo?
