### ISSUE TITLE
T2 - Test Lunatic

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#71]
Hola!

Hay novedad respecto a cuando se subirán los test lunatic para el bonus?

Gracias!

**Comment by alopez7** [comment]
Hola, me he demorado porque tengo que asegurarme de que se puedan resolver uaando A* y no con bfs o IDDFS. Estoy casi listo.

**Comment by KnowYourselves** [comment]
Okay! Muchas gracias por la dedicación, la tarea esta muy buena!
