### ISSUE TITLE
Error con test lunatic_00

### ISSUE THREAD

**Issue by jerosalazar** [IIC2133-PUC/2019-1#72]
Al hacer correr el lunatic 0 como ```valgrind ./solver tests/lunatic/lunatic_00.txt output.txt```, me aparece este problema:

![image](https://user-images.githubusercontent.com/30667977/57707237-45ecc580-7635-11e9-80b6-18b4e4465750.png)

No se si será que el test tiene algo malo (con los demás lunatic no me ocurre)

**Comment by alopez7** [comment]
Necesito que seas un poco más específico en tu error ya que la línea 102 de board.c varía de código en código. Qué estás haciendo en esa línea?

**Comment by jerosalazar** [comment]
Mi punto es que board.c es el código que viene hecho (no le cambié nada) y es en la parte que hace board_init

**Comment by alopez7** [comment]
Por casualidad no habrás modificado el test de alguna forma? No logro encontrar el error.

**Comment by jerosalazar** [comment]
Está identico a como lo subieron

**Comment by alopez7** [comment]
Por casualidad modificaste algún enum del programa?

**Comment by tomasrivera** [comment]
``` 
CellType type = board -> cells[node -> row + 1][node -> col].type;
```
En esa línea `row + 1` queda fuera del tablero cuando el nodo está en la fila de más abajo :smile:

**Comment by jerosalazar** [comment]
@alopez7 era eso?

**Comment by alopez7** [comment]
Creo que arreglé eso en las primeras versiones del código base. El código base actual no debería tener ese problema.

**Comment by tomasrivera** [comment]
O sino, es ponerle un if antes de esa línea y funciona todo bien

**Comment by jerosalazar** [comment]
@tomasrivera en que linea está? porque estoy con la ultima versión del código base y me sigue tirando problema

**Comment by tomasrivera** [comment]
En la 102, yo lo dejé así:

``` C
    // Veo si el nodo se apoya en algo
    if (node -> row < board -> height - 1){
      CellType type = board -> cells[node -> row + 1][node -> col].type;
      if (type == WALL) board -> snek -> grounds++;
      else if (type == SPIKE) board -> snek -> spikes++;
    }
```

**Comment by jerosalazar** [comment]
Gracias!

**Comment by alopez7** [comment]
Tienen toda la razon. Nunca pushié ese cambio y quedó en el código base mal. Voy a visar en un issue el cambio.

**Comment by alopez7** [comment]
Oficialmente si el snek se apoya en el fin del mapa cuenta como espina
