### ISSUE TITLE
Problema con código original

### ISSUE THREAD

**Issue by Cschavez** [IIC2133-PUC/2019-1#73]
Hola! He intentado correr el programa con el código que ustedes nos dieron y solo llega a imprimir el número random y después se queda "pegado" y lo estoy probando con el test_00.txt, pensé que podía ser por el watcher pero le comenté esas lineas y sigue igual. No sé si podrán tener alguna idea de lo que es o si es normal.

Muchas gracias!

**Comment by alopez7** [comment]
Si lees los comantarios del main verás que espera que le des las direcciones como input

**Comment by Cschavez** [comment]
Ups verdad, gracias! Y otra duda, creo que lo leí por ahí pero para estar segura, puedo modificar todo lo que quiera de los archivos en la carpeta snekbird o no?

**Comment by alopez7** [comment]
Puedes modificar lo que quieras.
En qué sistema operativo trabajas?

**Comment by Cschavez** [comment]
windows

**Comment by alopez7** [comment]
Abriste xming y escribiste export DISPLAY=:0?
