### ISSUE TITLE
Duda taller 4

### ISSUE THREAD

**Issue by smargozzini** [IIC2133-PUC/2019-1#74]
Tengo una duda, en el archivo snake.h de este taller se define la función 
``` c
uint64_t incremental_board(Board* board, Dir movement);
```
pero nunca se define 
``` c
uint64_t incremental_snake(Snake* snake, Dir movement);
```
Existe alguna razón en especifico para eso? o da lo mismo que sea así?
gracias.

**Comment by alopez7** [comment]
Lo que pasa es que incremental_snake se llama desde la función incremental_board. Por lo tanto solo se usa dentro del archivo snake.c y no es necesario agregarlo al snake.h
