### ISSUE TITLE
Discrepancia con valgrind

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2133-PUC/2019-1#75]
Hola! Tengo el siguiente problema.
Reviso dentro de la tabla de hash la existencia o no de un valor. Cuando aparece, retorna el puntero de un objeto, mientras que cuando no, este retorna nulo (`nil`).

Tengo el problema que en varias ocasiones, donde debería haber un valor nulo, me es retornado un puntero que es equívoco (generalmente posiciones negativas) y el programa se cae. La situación curiosa es que cuando corro el programa con Valgrind, los valores mostrados son los correctos: casi todos nulos. 

Cómo es posible que el binario normal diga una cosa (y se caiga), mientras que con Valgrind el programa es ejecutado correctamente?? 

La sección problemática es esta. Y ocurre tanto para insertar, como para buscar.
```c
while (ht->items[index] != NULL) {
        // código
}
```

La solución parche que sólo funciona a veces, es forzar al puntero a ser positivo, quedando de la siguiente manera, pero no es la idea.
```c
while (ht->items[index] != NULL & (int)ht->items[index] > 0) {
        // código
}
```

Muchas gracias!

**Comment by alopez7** [comment]
Si no lle das un valor a los punteros luego de crear el arreglo van a tener el valor que venía ahí. Debes darles valor NULL si quieres que partan en NULL

**Comment by santiagocruzb** [comment]
Muchas gracias!
