### ISSUE TITLE
Informes

### ISSUE THREAD

**Issue by santilaguna** [IIC2133-PUC/2019-1#76]
Hola!
Me gustaría preguntar si vamos a seguir teniendo informes en futuras tareas.
En el caso de que existan nuevos informes, quería preguntar cuál era la posibilidad de que subieran una pauta de lo que se espera. A modo de ejemplo, yo me guíe por la pauta del informe de la T0 para hacer el informe de la T1 y en este último la pauta cambió (en particular, no se me ocurrió poner conclusiones). A otros compañeros, les ocurrió que no pusieron gráficos, pues no se pedía en el enunciado.

**Comment by alopez7** [comment]
Hola, no sabemos a ciencia cierta si se tendrá informe en las tareas que quedan ya que depende de los tiempos del semestre. Si se hace otra tarea con informe me preocuparé de ser más específico con lo que se pide.
