### ISSUE TITLE
Error recoleccion tarea 1

### ISSUE THREAD

**Issue by mfanselmo** [IIC2133-PUC/2019-1#77]
Hola, 
En la tarea 1 me (y a varios mas) pusieron un uno  porque supuestamente no entregue el codigo. Yo si hice la tarea y todo mi codigo esta en mi repositorio. Quizas paso algo cuando se me crearon mutilples repositorios y deje solo 1, como decia la issue [#7](https://github.com/IIC2133-PUC/2019-1/issues/7). Por favor revisar esto.

Como ya no les llego el codigo de mi tarea, no quise hacer la issue ahi mismo, porque quizas no la vean.

Gracias

**Comment by dedarritchon** [comment]
Me pasó lo mismo

**Comment by Tibrahm** [comment]
lo mismo

**Comment by alopez7** [comment]
Hola,

Al parecer la recolección de repositorios no funcionó bien por lo que voy a tener que revisar a mano los que no entregaron. Agradezco la paciencia.
