### ISSUE TITLE
T2 - Posibles claves duplicadas

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2133-PUC/2019-1#79]
Hola, quisiera saber si se puede asumir que la funcion de hasheo del taller de hash (xor entre el de snek y el numero random de la pos) no genera claves duplicadas.
Por lo que entiendo las claves distribuirán uniforme entre 0 y 18,446,744,073,709,551,615, lo cual es mucho más grande que las posibles combinaciones. Por lo tanto es poco probable que se repitan, pero aún así seguiría siendo posible.
Graciass

**Comment by ignaciohermosillacornejo** [comment]
Es posible pero poco probable como tu mismo dices.
