### ISSUE TITLE
Algunas formalidades T0

### ISSUE THREAD

**Issue by jmwielandt** [IIC2133-PUC/2019-1#8]
Hola, quería preguntar algunas cosas sobre la tarea, más allá del enunciado:

- ¿Nos pueden decir en cuánto les corre a ustedes el test de mayor tamaño? para tener un _target_ más real que "1 segundo x generación".
- ¿Dónde lo van a ejecutar? Porque puede que a mí se me demore menos de un segundo pero a ustedes más, o _vice versa_ y yo me esté complicando más de la cuenta. Sería bueno poder compilar y probar en el computador donde van a corregir las tareas.
- ¿Exigen algún tipo de implementación específica o puede ser totalmente libre? (Quizás quieran que sí o sí lo implementemos como un arreglo de arreglos, ni idea).
- ¿La interfaz viene lista para ser usada, sin _memory leaks_ ni errores de memoria?

Gracias~

**Comment by alopez7** [comment]
Hola,

* El 1 segundo por generación es una formalidad ya que en realidad se demora menos de un décimo de segundo por iteración.
* Se va a ejecutar en el computador de @ignaciohermosillacornejo. El te puede dar los detalles del PC.
* Vas a tener que usar matrices. Cómo las implementes depende de lo que te acomode.
* No tiene leaks ni nada.

De nada~

**Comment by ignaciohermosillacornejo** [comment]
Hola @jmwielandt 

Las tareas las voy a corregir en una maquina virtual ubuntu dentro de mi computador (un macbook pro 15'' 2016). Para que te hagas una idea de la velocidad, la solución que tengo como pauta corre el _test 7_ (200 x 200) con 50 iteraciones en 4 segundos.

**Comment by jmwielandt** [comment]
Hola @ignaciohermosillacornejo !
Un par de preguntas
1. ¿Qué usleep tienes fijado en la pauta?
2. ¿Ese tiempo es compilando con o sin optimizaciones?

Gracias :D

**Comment by ignaciohermosillacornejo** [comment]
> Hola @ignaciohermosillacornejo !
> Un par de preguntas
> 
> 1. ¿Qué usleep tienes fijado en la pauta?
> 2. ¿Ese tiempo es compilando con o sin optimizaciones?
> 
> Gracias :D

1. usleep(100);
2. sin optimizaciones

**Comment by rihanuch** [comment]
¡Hola @ignaciohermosillacornejo !

Dos dudas:

1. ¿Ese tiempo es solo considerando el comando `./simulate test/test_07.txt 50`? :thinking: 
2. De no ser así, sería con `valgrind ./simulate test/test_07.txt 50`, con `time ./simulate test/test_07.txt 50`, o con `valgrind time ./simulate test/test_07.txt 50` :computer: 

¡Saludos y muchas gracias!

**Comment by vichoeq** [comment]
Ojo, los sleeps son unicamente para poder alcanzar a ver las cosas en la ventana. A la hora de corregir se cambia el código del watcher de manera de registrar toda la interacción con la ventana pero sin realmente abrir una, por lo que los sleeps ya no son necesarios.

El límite de 1 segundo por generación es una formalidad, ya que si una tarea se queda pegada o demora mucho **tenemos** que poder cortarla.

Este límite es solo a cuanto demora tu programa al llamarlo normalmente, ya que valgrind hará que sea mucho mas lento.
Para asegurarnos de tener las notas este año, ejecutamos tu tarea con valgrind con un test sólo si no excedió el límite de tiempo para ese test.

Por eso el código base dice "el código que entregues no debe tener sleeps". Si los dejas corres riesgo de que cortemos la ejecucción de tu programa por demorar mucho.

**Comment by rihanuch** [comment]
Ok!

El código que se entregue tampoco debe tener usleep?

Gracias!

**Comment by alopez7** [comment]
No debes tener nada que detenga tu programa como usleep, sleep o get_char ya que el código se corrige automáticamente y espera que tu programa termine.

**Comment by fgbruna** [comment]
@ignaciohermosillacornejo, se que probablemente en este caso la eficiencia de los binarios puede ser marginal, pero vas a usar gcc o clang para compilar?

**Comment by vichoeq** [comment]
Se compila usando la Makefile de tu repositorio, asi que usa el que tu quieras. Si te preocupa la velocidad, mas que cambiar el compilador, recomiendo que compiles con el flag `OPT = -O3` en lugar de `OPT = -g` como viene por default en la Makefile de manera que el compilador optimice tu código. Asegurate de leer los comentarios para saber cual es la diferencia entre ambos.

En todo la diferencia entre `gcc` y `clang` es marginal para los programas que estamos haciendo.

**Comment by dedarritchon** [comment]
> * Vas a tener que usar matrices. Cómo las implementes depende de lo que te acomode.

Hola, es válido definir la matriz así: uint64_t board[height][width]? Por tro lado, es obligatorio el uso de punteros, mallocs/callocs y free? pregunto porque no los estoy ocupando, me corre el test07 en tiempo razonable y valgrind dice que no tiene errores o memory leaks. Gracias

**Comment by vichoeq** [comment]
Si, es valido, pero recomiendo aprovechar ahora para soltar la mano con punteros y malloc, ya que para la T1 no vas a tener alternativa.

**Comment by ignaciohermosillacornejo** [comment]
Para todos los que estan preocupados con la eficiencia de su programa, el margen que dejamos entre la solución oficial y la tolerancia del juez normalmente es de casi un orden de magnitud, por lo que no se procupen si su tarea es 10% o 20% más lenta que la pauta, preocupense si su tarea es 10x más lenta que la pauta, por que eso significa que estan haciendo algo mal. 
En general para las soluciones de las tareas les vamos a pedir que logren una **solución de la complejidad esperada**, y es normal que hayan diferencias entre distintas soluciones por los compiladores/computadores/VM/técnicas de programación en C, etc pero al corregir les dejamos suficiente margen para no tener problemas con esas cosas.

**Comment by B-Dominguez** [comment]
Hola, respecto al tiempo de ejecución y no usar usleep:
1.-  Sin usleep los tests pequeños corren y una bacteria "gana" muy rápido por lo que no se alcanzan a observar.

2.- Sin un sleep final el resultado final no se puede apreciar

El enunciado dice 
> debes asegurarte que tanto los estados intermedios como el resultado final se muestren correctamente
 Aún así no usamos sleep ni usleep para los casos 1 y 2?
