### ISSUE TITLE
Taller mañana

### ISSUE THREAD

**Issue by smargozzini** [IIC2133-PUC/2019-1#80]
Hola, 
hay taller o actividad mañana?
saludos

**Comment by ignaciohermosillacornejo** [comment]
Hola @smargozzini 

Mañana si habrá taller, se harán ejercicios de Kruskal y Dijkstra. Puedes asumir que siempre habrá taller a menos que digamos lo contrario.

Saludos

**Comment by smargozzini** [comment]
ok, gracias
