### ISSUE TITLE
Problema makefile (MacOs)

### ISSUE THREAD

**Issue by Okhan97** [IIC2133-PUC/2019-1#81]
![image](https://user-images.githubusercontent.com/26289334/57942461-83ed2200-789f-11e9-9c80-a4e1e92625c6.png)

Hola, al intentar hacer make me tira el siguiente error, ¿como lo soluciono? 

PD: Me cambié de sistema operativo ayer, asi que no se si debo preinstalar algo o si estoy haciendo algo mal

**Comment by fdominguezclaro** [comment]
Hiciste un `make clean`? Como cambiaste de SO ahora los archivos binarios son distintos, por lo que tienes que volver a generarlos.

**Comment by Okhan97** [comment]
Limpió los archivos, pero ahora me aparece este error

![image](https://user-images.githubusercontent.com/26289334/57948038-94f15f80-78ae-11e9-9845-6c378bfbcda8.png)


PD: Cuando dije que me cambie de SO me referia a que me cambié de pc (el otro murió) y ahora estoy con MacOs, por lo que no se si debo hacer algun seteo especial

**Comment by alopez7** [comment]
Instalaste GTK en tu nuevo pc?

**Comment by fdominguezclaro** [comment]
Corre en el terminal `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/`

Vas a tener que hacerlo cada vez que lo abras, así que mejor agrégalo al .bashrc (o a zsh en caso que lo uses)

**Comment by Okhan97** [comment]
No he instalado gtk, lo estoy intentando ahora pero el link para descargar el paquete (desde la documentacion oficial) está roto :/

**Comment by jerosalazar** [comment]
Yo tengo mac y para ambas tareas he tenido problemas con ese mismo paquete. Lo que hice finalmente fue comentar el include del watcher en el main y borrar la carpeta beholder del makefile. Con esto te corre todo bien, pero no puedes ocupar la interfaz

**Comment by Okhan97** [comment]
Muuuchas gracias, llevo toda la mañana intentando resolverlo

**Comment by Okhan97** [comment]
@jerosalazar hice como dijiste, pero em arroja el siguiente error de todas maneras:

sh: ./beholder: No such file or directory

Alguna idea?

**Comment by jerosalazar** [comment]
Quizás lo importas de algún lado

**Comment by vichoeq** [comment]
Borra las llamadas a `watcher`, ese error parece ser el watcher intentando abrir la ventana.

**Comment by vichoeq** [comment]
> el link para descargar el paquete (desde la documentacion oficial) está roto

uf

el comando de homebrew no te funciona? (no tengo Mac así que me es dificil probar estas cosas)

**Comment by Okhan97** [comment]
@vichoeq que comando de homebrew??

Acabo de borrar las llamadas a watcher y todo funcó :) (sin interfaz grafica claro xd)

**Comment by ignaciohermosillacornejo** [comment]
> @vichoeq que comando de homebrew??
> 
> Acabo de borrar las llamadas a watcher y todo funcó :) (sin interfaz grafica claro xd)

@Okhan97 prueba este comando `brew install gtk+3 gtk+ --without-x --without-x11`

**Comment by ignaciohermosillacornejo** [comment]
Si no también revisa #10

**Comment by nfbalbontin** [comment]
Hola! Yo igual ando teniendo problemas parecidos. Para la tarea pasada hice lo de editar el makefile de tal forma de no tener ni el watcher ni el beholder como parte de la compilación, pero ahora para esta me arroja el siguiente error al compilar: 
<img width="940" alt="Captura de Pantalla 2019-05-18 a la(s) 17 09 15" src="https://user-images.githubusercontent.com/26261777/57975016-cc840880-798f-11e9-8550-5b19cde1f80e.png">

**Comment by Okhan97** [comment]
@ignaciohermosillacornejo 
No pude ejecutarlo con las flags que tenias (--without-x/x11), instalé gtk sin esas flags y se demoró un monton pero seguia sin funcionar.
Finalmente fui a la issue que me decias y siguiendo los pasos de la ultima instruccion pude por fin correr bien el programa

Por fin puedo empezar la tarea :D

PD: @nfbalbontin prueba lo que dice en las issues si es que no te funca, ahora si puedo usar la interfaz grafica :)

**Comment by jerosalazar** [comment]
Para todos los que tengan problemas: les recomiendo que hagan una maquina virtual de ubuntu y trabajen ahi nomas. Yo lo hago así y es harto más cómodo, además tienes valgrind

**Comment by ignaciohermosillacornejo** [comment]
> Para todos los que tengan problemas: les recomiendo que hagan una maquina virtual de ubuntu y trabajen ahi nomas. Yo lo hago así y es harto más cómodo, además tienes valgrind

Si no pueden hacer funcionar la instalación en Mac es la mejor opción por que independiente de si les corre en mac o no, tienen que si o si correr por lo menos una vez su tarea en Ubuntu su tarea, para revisar que todo este bien y además tienen Valgrind ahí.
