### ISSUE TITLE
T2 - Uso de Branches en el repo

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#82]
Hola!

Actualmente para implementar _A*_ lo hice en un _branch_ para no modificar mi código original que estaba funcional. Mi pregunta es la siguiente, causaría algún problema con el proceso de recolección que dejara algún _branch_ sin _merge_?, Simplemente se recolectara _master_?

Gracias!

**Comment by alopez7** [comment]
Solo se recolecta master
