### ISSUE TITLE
get_random() números negativos

### ISSUE THREAD

**Issue by Tibrahm** [IIC2133-PUC/2019-1#83]
Hola !

Al ser el get_random() utilizando uint64_t me esta dando números negativos, pero cuando lo hago con uint32_t me da solo positivos. 

1. Esta bien que de números negativos? 
2. De no ser así, puedo ocupar uint32_t ?

**Comment by alopez7** [comment]
No es posible. Cómo los estás imprimiendo? Un uint64_t se imprime como %llu

**Comment by Tibrahm** [comment]
Eso era, pero al compilar me tira un warning que debería imprimir con ld

**Comment by Tibrahm** [comment]
Eso era, pero al compilar me tira un warning que debería imprimir con ldxf
