### ISSUE TITLE
Estructura de Repositorio - T2

### ISSUE THREAD

**Issue by IchottMano** [IIC2133-PUC/2019-1#86]
Buenas noches,

Abro esta issue porque tenía una duda sobre la estructura de mi repositorio, yo luego de haber terminado la tarea, elimino carpetas "innecesarias" como ```beholder``` y ```watcher```, eliminando también sus referencias dentro de mi código, además de modificar el Makefile para que no busque estas carpetas, lo cual hace que el Makefile funcione correctamente.

Además, no subo la carpeta con los tests.
Poniendo una carpeta de tests (o en su defecto, apuntando correctamente a los tests cuando se usa mi ejecutable), mi programa funciona correctamente.

Mi pregunta es, ¿es esto válido para la entrega? ¿O es necesario que incluya estas carpetas, aunque no influyan en la ejecución de mi tarea?

Muchas gracias.

**Comment by alopez7** [comment]
Mientras tu programa compile y se ejecute correctamente está bien.
