### ISSUE TITLE
T2 - Error en código base board.c

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-1#87]
Hola, me hicieron notar que en el código base hay un error que pensé que ya estaba solucionado pero nunca arreglé. Para que no tengan problemas con eso es en el archivo board.c en la línea 102.

Antes de acceder a la casilla de abajo de la posición del snek hay que revisar que no esté apoyada en el fondo del mapa. Si eso pasa entonces hay que hacer sumar 1 al contador de spikes del snek tal como se hace en las líneas siguientes.

Saludos

**Comment by baarratia** [comment]
Hola, gracias por la aclaración, estuve peleando de hecho con ese error hace unos días y se me fue subir un issue al respecto. Sería posible que subas el board.c actualizado con esto? o que por último pongas por acá qué se pone exactamente, porque lo implementé pero me daría más confianza si todos estuviésemos alineados con la misma base.
Muchas gracias!

**Comment by vichoeq** [comment]
Actualmente el código que falla dice:

```C
// Veo si el nodo se apoya en algo
CellType type = board -> cells[node -> row + 1][node -> col].type;
if (type == WALL) board -> snek -> grounds++;
else if (type == SPIKE) board -> snek -> spikes++;
```

Debería decir:

```C
// Veo si el nodo se apoya en algo
if (node -> row + 1 == board -> height) board -> snek -> spikes++;
else
{
    CellType type = board -> cells[node -> row + 1][node -> col].type;
    if (type == WALL) board -> snek -> grounds++;
    else if (type == SPIKE) board -> snek -> spikes++;
}
```

**Comment by baarratia** [comment]
Gracias!
