### ISSUE TITLE
Problema con test_05.txt, test_08.txt y test_10.txt

### ISSUE THREAD

**Issue by ajahr95** [IIC2133-PUC/2019-1#88]
Hola estoy teniendo problemas con los test_05.txt, test_08.txt y test_10.txt debido a que mi Open se queda sin estados que revisar, es decir nunca llega al ganador. El resto de mis test al parecer funcionan bien y entregan el resultado de manera rápida. Ya cambie la carpeta test por la subida en el siding y cambie la linea 102 del board.c por if(node-> row < board ->height-1). No entiendo cómo es que me funcionen bien el resto de los test y estos no. Lo único que podría pasar es que el board_move este desechando estados válidos posibles o que mi tabla de hash este retornando que ya existe ese hash y no lo agrega a Open, pero ya he revisado múltiples veces mi código y no he podido ver el problema. Además si fuera algo así de evidente supongo que no me funcionarían los otros test.

Quería saber si hay algo en especial que considerar que se me podría estar pasando y que afecte en estos test o si a alguien le paso algo similar y lo pudo arreglar. Gracias.

**Comment by alopez7** [comment]
El movimiento funciona bien. Se me ocurre que tal vez estás ignorando estados nuevos pensando que ya los viste. Revisa tu comparación en la tabla de hash. También puede ser que la cola funcione mal.

**Comment by ajahr95** [comment]
También pensé que sería lo de descartar estados pensando que ya los vi pero he revisado varias veces como reviso la tabla de hash y no veo el error. Lo mismo con la cola :(

**Comment by vichoeq** [comment]
El problema lo tienes solo en esos puzzles?

Quizás estás rompiendo tu tabla al hacerla crecer (haciendo mal el rehashing) si esos puzzles tienen muchos estados. Prueba darle un tamaño inicial más grande a ver si es eso.

**Comment by ajahr95** [comment]
Si son solo esos puzzles el problema, el resto funciona bien y rápido. Probe como dijiste, con una tabla inicial muy grande pero me sigue pasando lo mismo.

**Comment by vichoeq** [comment]
-> pero revisaste si en algun minuto la haces crecer?

**Comment by ajahr95** [comment]
En ningún momento le hago rehashing porque la modelé encadenada y me funciona de manera rápida entonces en ningún momento crece.

**Comment by alopez7** [comment]
Tal vez te falta iterar en alguna dirección de movimiento

**Comment by ajahr95** [comment]
@alopez7 tampoco, si el resto de los outputs de los otros test me dan, solo me pasa en los tests 05, 08 y 10 este problema.

**Comment by alopez7** [comment]
Puedes comprobar a mano una solución (es fácil) y ver si los estados de esa solución aparecen en tu lista open. Esto te debería llevar a encontrar el error rápidamente.

**Comment by ajahr95** [comment]
Creo que lo solucioné, viéndolo a mano me di cuenta que el hash incremental al parecer no me estaba funcionando bien porque 2 estados distintos me daban el mismo hash, y mi principal modificación( que creo que fue lo que lo arregló) fue actualizar el hash a la snek una vez que calculaba un incremental nuevo porque al parecer esto no se estaba haciendo bien. Al menos ahora los 10 test si me funcionan ahora. Gracias!

**Comment by alopez7** [comment]
Es normal que 2 estados distintos den el mismo hash. La función de hash no es perfecta. Debes comparar los estados cuandos cuando au hash es el mismo para asegurarte que son el mismo estado.
