### ISSUE TITLE
T2 - out of memory, igual cuenta para el bonus?

### ISSUE THREAD

**Issue by naquiroz** [IIC2133-PUC/2019-1#89]
Si mi tarea en algunos tests, con valgrind tira errores de `out of memory` pero si le doy mas memoria no me tira memory leaks, igual cuenta para el bonus?.

Pd: sin valgrind funciona.

**Comment by alopez7** [comment]
Mi pc tiene 8gb de ram por lo que si no te pasas de eso no debería haber problema. Para ver el bonus de valgrind se usará un test relativamente chico por lo que eso no es importante
