### ISSUE TITLE
T2 - Error rarisimo

### ISSUE THREAD

**Issue by Okhan97** [IIC2133-PUC/2019-1#90]
![image](https://user-images.githubusercontent.com/26289334/57996970-5d460b80-7a98-11e9-8f8e-9a2f5894d727.png)

Hola, he buscado y buscado y no logro solucionar este error, no se que hice pero ahora al hacer make nisiquiera me dice que los archivos se compilan :/

**Comment by ignaciohermosillacornejo** [comment]
Hola @Okhan97 

No se que cambios hayas hecho que rompio tu tarea pero dado que se entregaba ayer, te sugiero fuertemente programar en Ubuntu y dejar de gastar tiempo arreglandlo el problema en tu Mac para que no te baje más la nota por gastar tiempo en esto.

Después cuando tengas más calma, puedes ver con tranquilidad el error y arreglarlo.

Saludos
