### ISSUE TITLE
Guia de Preparacion Complejidad de Union/Find

### ISSUE THREAD

**Issue by nmaturana97** [IIC2133-PUC/2019-1#91]
En la guia de preparación para el control 5 se pide la complejidad de:

listas ligadas lineales: cada elemento de la lista tiene un
puntero al elemento que le sigue y otro al primer
elemento de lista (el representante)

En la solucion sale que son O(1) para Union y O(N) para Find.
Pero si tomamos en cuenta que se tiene un puntero hacia el representante, esto me hace pensar que el find es O(1) y se deben modificar los punteros de la otra lista ligada por lo que el union deberia ser O(N).

Entonces, como sería en ese caso?

**Comment by vichoeq** [comment]
Find en listas seria O(largo de la lista) ya que recibe como parametro un nodo de la lista, no la lista en si, por lo que para encontrar al representante debe recorrer la lista hacia llegar a la cabeza.

Si cada nodo tiene un puntero hacia el representante, entonces no te interesa la lista ya que tienes un arbol y claramente find seria O(1)

**Comment by nmaturana97** [comment]
Entonces estaria mal la definicion de lista ligada lineal que dieron en la guia de preparacion?

**Comment by vichoeq** [comment]
Sí, esa definición es incorrecta: si la lista ligada lineal va a tener un puntero al representante sería unicamente en el caso de que estemos intentando optimizarla.

Find sería O(1) por esa razón, y unión es O(n) ya que tienes que actualizar todos los punteros de la lista más corta tal como dices.

**Comment by vichoeq** [comment]
Están al revés las respuestas nomás.

**Comment by nmaturana97** [comment]
Vale, gracias!
