### ISSUE TITLE
Taller 24/05 - Duda Contenidos

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2133-PUC/2019-1#92]
Hola!

Quisiera preguntar cuales son los contenidos que se revisaran y serán evaluados en el taller del viernes.

Saludos y gracias por su atención!

**Comment by vichoeq** [comment]
Hola, se hará un taller de backtracking (ya que nunca se cubrió en un taller) enfocado en la Tarea 3. En particular, para su uso en los que llamamos "problemas de planificación". Desgraciadamente no tengo muchos ejemplos para darte sin hacerte leer los enunciados de tareas pasadas, pero echale una mirada a la guia de backtracking del repo.

**Comment by frvalenzuela** [comment]
Muchas gracias! Eso haré !

**Comment by vichoeq** [comment]
Aqui está el enunciado de la única tarea que hemos hecho con ese tipo de problema,

[Tarea 1 2016-2.pdf](https://github.com/IIC2133-PUC/2019-1/files/3210168/Tarea.1.2016-2.pdf)

**Comment by frvalenzuela** [comment]
Muchas gracias!!!
Lo revisaré para antes de ir al taller.

**Comment by nfbalbontin** [comment]
Qué sucederá con respecto al taller y el paro al que adhirió la institución? 
Saludos, 

Atte Nicolás Balbontín

**Comment by ignaciohermosillacornejo** [comment]
Se envio un anuncio al respecto
