### ISSUE TITLE
Me funcionó la interfaz gráfica

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2133-PUC/2019-1#94]
Hola!

No sé si habrán realizado algún cambio en el funcionamiento de la interfaz, pero es primera vez que me funciona (en Mac). Si es que hicieron algún cambio, ¡muchas gracias! 😄 

Saludos.

**Comment by vichoeq** [comment]
Todas nuestras interfaces tienen una gran parte de código comun y lo que cambia es lo que se dibuja nomas, asi que no tengo idea por qué podría pasar esto :(

Que bueno que te funcione :)
