### ISSUE TITLE
T3 - Máximo Tamaño de Test Case

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#95]
Hola!

Existe algún máximo tamaño con el cual testearan en esta tarea?, para saber si puedo ocupar el valor máximo de un `uint8_t` como valor reservado para la lógica de mi tarea.

Gracias!

**Comment by alopez7** [comment]
El tamaño del tablero puedes asumir que cabe en un uint8_t

**Comment by vichoeq** [comment]
Si, puedes usar valores altos como valor reservado, no vamos a probar con tests más grandes que los que subimos.
