### ISSUE TITLE
T3 - Duda Respecto al Preprocessor de C

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#96]
Hola!

Para analizar el efecto de las distintas podas y heuristicas de forma eficiente se me ocurrió la idea de ocupar macros (`#ifdef` especificamente) para poder modificar mi código de forma dinámica. 

Mi pregunta es, hay alguna forma de definir macros desde fuera del archivo c?, es decir, hay alguna opción que pueda agregarle al `makefile` o a la ejecución del programa para definirlos de forma eficiente?

La otra opción sería agregarle argumentos al programa pero quiero explorar la opción de usar macros primero.

Muchas gracias!

**Comment by vichoeq** [comment]
Es buena idea lo de las macros, pero ojo que tienes que tener cuidado con que no se te desordene el codigo.

Recomiendo definir todos los parametros que te interesen en un mismo archivo ".h" y comentarlos/descomentarlos para probar distintas cosas.

Definirlos desde la Makefile / make es muuuuuy complicado, no vale la pena el esfuerzo.

Ojo que las directivas de preprocesador se pueden poner en cualquier lado. Es especialmente util para los structs. Por ejemplo:

```c
#define PODA_X

typedef struct
{
    Position pos;

    // otros elementos del struct

    #ifdef PODA_X
        // variable que usas solo para la poda X
        int contador_especifico_para_poda_x;
    #endif
} Cell;

**Comment by KnowYourselves** [comment]
De momento cree una carpeta con mi archivo .h y .c con la representación del problema y todas las podas. Supongo que sería mejor práctica dejar todos los macros en el .h?

Mi problema con comentarlos y descomentarlos es que quería hacer un script en python que me generara un excel con símil al de la ayudantía, de ahí la necesidad de definir los macros "de aufera". 

Si es que es demasiado dificil/imposible, utilizaré los macros para testear y luego argumentos nuevos para generar el excel. Muchas gracias!

**Comment by KnowYourselves** [comment]
Alfinal probando logré hacerlo!

Bastó con agregar a los `CFLAGS` del Makefile una variable de la forma `$(MACROS)`, luego se pueden definir los macros al hacer `make MACROS="-DMACRO1 -DMACRO2 ... -DMACRON"`, sin embargo me nacen dos preguntas:

1. Está "bien" esto? (no me estaría echando nada?)
2. Por lo que veo el make está configurado para no volver a generar los .o a menos que estos cambien, que cambio debería hacer al Makefile para que los genere siempre? (Para asi poder hacer make cada vez e ir cambiando las podas y heurísticas dinámicamente)

Muchas gracias!

**Comment by vichoeq** [comment]
Si, recomiendo dejarlos en el .h de tu struct mas elemental, asi tienes acceso a los macros desde cualquier parte de tu codigo.

Modificar la makefile cada vez que quieras probar algo distinto es lo mismo que modificar los macros directamente en el .h

Pero no, agregarlo a los CFLAGS no va a romper nada.

Tambien se recompila todo si modificas la Makefile, por lo que deberia funcionar para lo que quieres.

Yo lo que hice fue un script de bash que corria el programa con todos los tests, imprimiendo los resultados a un csv. De ahi pasaba los datos a mano al excel grande.

**Comment by KnowYourselves** [comment]
El único problema es que como estoy seteando el valor de la variable desde fuera del Makefile no lo considera como un cambio. 

Lo que pasa es que si no tengo la carpeta `obj` y hago `make MACROS=-DTEST` lo compila, sin embargo si luego hago `make MACROS=-DTEST2` no lo recompila. Alguna idea de que hacer?

Respecto a lo demás, me quedó clarisimo!, Gracias!

**Comment by vichoeq** [comment]
Si no tienes la carpeta obj compila porque tener esa carpeta es requisito de la regla de compilación, pero realmente no se si se están definiendo esos macros.

Revisa este issue https://github.com/IIC2133-PUC/2019-1/issues/67 para una explicación más en detalle

Insisto en que es más desenredado comentar/descomentar las flags directamente en tu código, pero lo dejo a tu criterio,

**Comment by KnowYourselves** [comment]
Al final logre hacerlo!

Solo bastaba con agregar el flag `-B` para forzar la recompilación. Pude hacer el script en python también.

Muchas gracias por la paciencia!
