### ISSUE TITLE
T3 - Tamaño N en Análisis Teórico y Explicación Teórica

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2133-PUC/2019-1#97]
Hola!

Tengo dos dudas.

La primera es respecto al tamaño **N**: 
> Considera tambien el tamaño del problema **N** (cantidad de puentes posibles).

Este número vendría siendo la cantidad de puentes o todas las posibles combinaciones que esa cantidad de puentes implica? 

La segunda es respecto a la explicación teórica de las podas y heurísticas:
> Justificar desde un punto de vista teórico el por qué deberían ser de ayuda.

En este caso habría que hacer un estudio de complejidad (como en tareas pasadas) o es simplemente explicar por que la poda/heurística en cuestión debería ser útil dado las mecánicas del juego?

De antemano, muchas gracias!

**Comment by alopez7** [comment]
Hola
1. N es el número de puentes del tablero.
2. Ese punto que citaste se refiere a justificar porqué crees que tu heurística podría mejorar la velocidad con que se resuelve el problema de la forma más teórica posible. En general las heurísticas tienden a ser "tincadas" por lo que la justificación puede ser algo como: "estas heurística podría mejorar el tiempo de solución ya que el puzle tiende a tener X característica y esto hace que elegir primero Y sea una buena idea."

**Comment by vichoeq** [comment]
Un poco lo que vimos en la clase es hablar de cual es la **probabilidad** de equivocarte con cierta opcion, y justificar porque tal o cual decisión podría tener más probabilidad de llevar a una solución. 

La otra opción es **abusar** de la estructura del problema, por ejemplo sabemos que un puente que este alineado a la meta probablemente sea el que tienes que extender al final y en que dirección. Yo recomiendo este _approach_ para este problema, ya que te permite hacer podas y heurísticas muy poderosas, y muchas de ellas no cambian según cuantos puentes ya has extendido.
