### ISSUE TITLE
T3 - "Can't create obj/watcher/watcher.o"

### ISSUE THREAD

**Issue by firulais33** [IIC2133-PUC/2019-1#98]
Hola,

Al compilar me lanza este error, nose porque. Alguien sabe?

Gracias!

**Comment by alopez7** [comment]
Manda el mensake completo del compilador plz

**Comment by firulais33** [comment]
El mensaje completo es:

`Fatal error: can't create obj/watcher/watcher.o: no sudh file or directory
Makefile:113: recipe for target 'obj/watcher/watcher.o' failed
make: *** [obj/watcher/watcher.o] Error 1`

El makefile y todos los directorios estan tal cual venian en el repo base.
muchas gracias!

**Comment by alopez7** [comment]
Puede ser media mala mi respuesta pero intentaste hacer make clean antes dr hacer make? No se cual podría ser el error

**Comment by vichoeq** [comment]
Haz `make clean` y luego crea una carpeta llamada `obj` al lado de la Makefile.
