### ISSUE TITLE
Taller 6 - Enunciado

### ISSUE THREAD

**Issue by smargozzini** [IIC2133-PUC/2019-1#99]
hola, existe algún enunciado para el taller 6 del viernes pasado, para poder entender mejor el código y su finalidad.
gracias.

**Comment by alopez7** [comment]
El taller del viernes pasado fue resolver el puzle de cindy (es un ejemplo típico de backtracking). Este puzle es un poco distinto al resto de los puzles que resolvimos con backtracking porque acá importa el momento en el que haces cada acción (el estado del tablero te puede permitir o no hacer un movimiento). Es por esto que la implementación del taller evalúa las variables en orden temporal (la primera variable reprecenta el primer movimiento, la segunda el segundo movimiento, etc...).
El puzle de la tarea tirne esta misma propiedad. Importa el momento o el estado del tablero cuando usas una pieza en una dirección.
Un alumno mandó un buen resumen de la ayudantía al telegram (no oficial del curso). Trata de buscarlo.

**Comment by smargozzini** [comment]
Gracias.
Cual es el telegram del curso?

**Comment by alopez7** [comment]
https://t.me/joinchat/GeR-5Em-qLX_JoR2XydaZw
Ojo que no es un medio oficial del curso, gue creado por alumnos para los alumnos
